### ISSUE TITLE
Gated rail and gated one-way rail

### ISSUE THREAD

**Issue by CausticBURN** [CovertJaguar/Railcraft#201]
Don't seem to be connecting to fence like they should.
![2014-04-29_17 20 28](https://cloud.githubusercontent.com/assets/7432552/2835767/c2f7e6c4-cfee-11e3-8e90-0057be22ee89.png)
![2014-04-29_17 35 45](https://cloud.githubusercontent.com/assets/7432552/2835769/cae0867a-cfee-11e3-971d-f26de6fc26a9.png)

**Comment by liach** [comment]
The class BlockFenceReplacement is not implemented, I think. But how to implement that to make the @Override function properly?

**Comment by CovertJaguar** [comment]
Fixed for 10.0.0
