### ISSUE TITLE
Railcraft 9.2.2.0 tunnel bore protection issue

### ISSUE THREAD

**Issue by djoveryde** [CovertJaguar/Railcraft#280]
I'm currently using cauldron-1.7.10-1.1207.01.187 with Railcraft_1.7.10-9.2.2.0.

My current issue is that i cannot figure out how to prevent the tunnel bore from breaking through worldguard/faction protected areas. It just keeps on going.
Any help?

**Comment by liach** [comment]
As cauldron has been killed, any future investigation?

**Comment by CovertJaguar** [comment]
I believe they are Forge events.

**Comment by djoveryde** [comment]
Cauldron has been taken on by someone who has kept it updated. However the issue still exists. Its now called KCauldron, and is presently running on the latest forge version.

**Comment by liach** [comment]
Simply ban it. That's the best way to do.

**Comment by AEnterprise** [comment]
i think there are forge events, i know as of recently BC is respecting those protections

**Comment by mcsnetworks** [comment]
What forge Event is this suppose to fire?

**Comment by hea3ven** [comment]
This is what BC uses to break blocks, you can find the events there: https://github.com/BuildCraft/BuildCraft/blob/6.5.x/common/buildcraft/core/lib/utils/BlockUtils.java

**Comment by liach** [comment]
You mean [throwing a event with fakeplayer] (https://github.com/BuildCraft/BuildCraft/blob/6.5.x/common/buildcraft/core/lib/utils/BlockUtils.java#L91-L97)? Actually that does never help, You can extract the `GameProfile` information stored in the nbt of the cart and check whether the `GameProfile`'s owner has access to the protected area (exceptions might be the cart is still working while the owner is offline)

**Comment by AEnterprise** [comment]
using the owner when possible would indeed be better but falling back to a fake player when the owner is offline should also be included then, otherwise things will break if the owner goes offline on a server and the bore continues working

**Comment by mcsnetworks** [comment]
Keep in mind that blockdamage on the bukkit side doesn't carry a cause, wish it did.  I wish it would fire the ownersName in the event, this would solve the issue almost immediately.

**Comment by vpontin** [comment]
If this are a (K)Cauldron based issue, try posting this in prototik's KCauldron repo (google it). Maybe they can fix it

**Comment by mcsnetworks** [comment]
This isn't a Cauldron issue, this is Railcraft not firing events correctly.

**Comment by mcsnetworks** [comment]
Many Forge Developers developed their mods without ever thinking it could be used in a server based environment, therefore permissions were never included in the design.

If Mod developers fire the events correctly this isn't an issue.

**Comment by mcsnetworks** [comment]
Could you provide an update on this?

**Comment by mcsnetworks** [comment]
This issue can be resolve with something as easy as this:

http://pastie.org/10430521

Placed at line 717 of EntityTunelBore.java
