### ISSUE TITLE
Request: More types of chest carts

### ISSUE THREAD

**Issue by ace13** [CovertJaguar/Railcraft#362]
There are quite a lot of mods that add new chests and other storages to Minecraft, mods like Iron Chests, Factorization (barrels), or JABBA.

Would be nice if you could craft those into chest/barrel carts.

**Comment by wshadow** [comment]
As for visually different - would http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2091897-cartlivery cover your needs? (I don't know the mod, just found it on the forums)

**Comment by ace13** [comment]
I would like to mention that I - at least - consider this issue resolved as of 9.8.0.0

The cargo cart is almost exactly what I wanted when I posted this request.

**Comment by Vexatos** [comment]
Factoritzation added Barrel Carts months ago.

**Comment by shobu9** [comment]
There's a bunch of new mods coming with that sort of thing new types of carts , i agree with vexatos.
