### ISSUE TITLE
[Suggestion] Allow Comparators to read the amount of Fluid in a tank

### ISSUE THREAD

**Issue by wshadow** [CovertJaguar/Railcraft#364]
I think it would be really useful, if you could read the amount of fluid that is in an iron tank. Using a comparator (similar how it works with vanilla chests) seems like an ideal solution.

I already created the pull request #360 that does this, but need some help/ideas on how to fix a bug with missing block updates (more detail on this in the pr). I guess I should have created this issue first... Oh well, if this turns out to be a bad idea and my code is not accepted, then I just have to live with it.

**Comment by wshadow** [comment]
@Yopu thanks for your help on this issue. Only one small thing left. If you have a setup like ![in this screenshot](http://i.imgur.com/rQXEwkJ.png) the comparator doesn't update it's value unless it gets a blockupdate. With a vanilla chest this works just fine. So to be consistent with vanilla behavior we should also make setups like that work.

And yes, there is a valve behind the top cobblestone.

**Comment by CovertJaguar** [comment]
It worked fine in my testing.

**Comment by Yopu** [comment]
Investigating.

**Comment by Yopu** [comment]
Fixed: https://github.com/CovertJaguar/Railcraft/commit/dca915b9e1b7cb231432d854afbedf21ceaac3d5

**Comment by Yopu** [comment]
Thanks for the heads up @wshadow!
