### ISSUE TITLE
Metal Platforms not Dropping

### ISSUE THREAD

**Issue by slawr34** [CovertJaguar/Railcraft#387]
I am having a bug where metal platforms (grey metal platforms) don't drop when broken with a pickaxe. Not sure if this is intentional. 

Edit - 
Neither are grey metal posts.

**Comment by liach** [comment]
@slawr34 Does this still happen with latest verions for 1.7?

**Comment by liach** [comment]
Some Ticon picks dig platforms even slower than an empty hand for some reason. For those picks which break platforms and posts in a reasonable time (i.e. faster than bare hand) they drop platforms.

**Comment by CovertJaguar** [comment]
I redid all the harvest types for RC 10, maybe it fixed it.

**Comment by liach** [comment]
@CovertJaguar My test result is that this is working as intended. So I will close this issue.
