### ISSUE TITLE
[suggestion] Signal Block areas

### ISSUE THREAD

**Issue by Sidorion** [CovertJaguar/Railcraft#392]
In some track layouts it is hard or impossible to define a valid signal block with the current methods. So I thought, it would be nice to have an option to define a certain area in which every cart on any track is switching the aspect from green to red (maybe yellow if it's stationary).
I'm fully aware, that it is impossible to tell, if the cart is moving toward the block signal or not, but that's not important of such a complex structure as any cart moving in there is possible havoc.

E.g. my grand junction with double tracks and the ability to route every incoming cart to every outgoing track is an area of 10x10 blocks with eight switch motors, eight crossings, and 16 turnouts.

**Comment by wshadow** [comment]
When #455 is implemented this should not be needed anymore.
