### ISSUE TITLE
Crowbar Mining Tracks Slow

### ISSUE THREAD

**Issue by liach** [CovertJaguar/Railcraft#399]
When mining Railcraft Tracks(Only Tracks) , the crowbar is not quick! It works slowly. I want it to work quickly on tracks. 
There's no problem with vanilla tracks.

**Comment by purpleposeidon** [comment]
Would it be easy to have rails be broken just with the crowbar rather than a pickaxe?

**Comment by CovertJaguar** [comment]
Fixed by f346ba5a2ec3e41ae1248a9f74e34c07f4612535

**Comment by liach** [comment]
great thanks  to you!
