### ISSUE TITLE
[Suggestion] Make Post Gates And Post Gated Tracks

### ISSUE THREAD

**Issue by liach** [CovertJaguar/Railcraft#400]
Everyone sees that posts connect to gated tracks. So Post Gated Tracks may be a way to prevent the bug in #201 .

**Comment by liach** [comment]
Is this rejected or implemented on your side? I hope you could put a label to make things clear.

**Comment by CovertJaguar** [comment]
Rejected, at least until I decide I want to devote the effort to making gate track multi-material.
