### ISSUE TITLE
Having a locomotive drive up an elevator track breaks it

### ISSUE THREAD

**Issue by Forecaster** [CovertJaguar/Railcraft#414]
The locomotive gets stuck in the transition and refuses to move.

http://i.imgur.com/RVPrVkb.png

This is not what I meant when I said it breaks it though, for some reason it stops working when it gets stuck. It completely refuses to drive even if I dislodge it and push it to a straight track.

It will not move. It is producing and consuming steam and burning fuel, but the drive doesn't work. It also pops off the track sometimes if you push it for some reason. An unbroken locomotive (or other cart) doesn't. I've never seen anything do that before.

**Comment by CovertJaguar** [comment]
Solution was determined to be to not use the sloped elevator approaches and stick with flat approaches.
