### ISSUE TITLE
Flying Buildings

### ISSUE THREAD

**Issue by CovertJaguar** [CovertJaguar/Railcraft#432]
![flying](https://cloud.githubusercontent.com/assets/1521970/5426868/ff68f064-8329-11e4-9df0-186cb2df7072.png)

**Comment by liach** [comment]
Could it be reproduced? This is a rare case I think.

**Comment by CovertJaguar** [comment]
I've never seen it myself.

**Comment by liach** [comment]
Does this happen any more?

**Comment by CovertJaguar** [comment]
This is the only report of such I've ever gotten. It can probably be closed.

**Comment by liach** [comment]
Then I suggest to close this.
