### ISSUE TITLE
Routing Table not registering "NOT" Operator

### ISSUE THREAD

**Issue by kwstoudt** [CovertJaguar/Railcraft#445]
Just as the title says. My routing tables all of a sudden aren't registering the "NOT" operator and turning my trains when they aren't supposed to (using routing tables in routing switch motors).
Using Railcraft Version 9.4.0.0

**Comment by ssotangkur** [comment]
The routing table language uses a "prefix" operator format meaning that your operators go in the front and the parameter(s) of the operator go right after. If the parameter(s) happens to start with another operator then all the params of this new operator will also be a part of the first operator statement.
So...
```
NOT
Dest=Village2
NOT
Dest=Village10
```
Is the same as: `(NOT(Dest=Village2)) OR (NOT(Dest=Village10))`
And...
```
AND
NOT
Dest=Village2
NOT
Dest=Village10
```
Is the same as: `(NOT(Dest=Village2)) AND (NOT(Dest=Village10))`

**Comment by CovertJaguar** [comment]
Lacking any evidence that there is an actual bug here, I'm going to close this. Thank you for the report, best of luck in future projects.
