### ISSUE TITLE
Rendering problem with steel tank

### ISSUE THREAD

**Issue by HadesDurin** [CovertJaguar/Railcraft#449]
i edit some tank blooks and when i place down the last blocks it looks very stange to me and only a few blocks gets updated
![2014-12-31_11 31 38](https://cloud.githubusercontent.com/assets/5231067/5587067/31b3f4a0-90e1-11e4-95c3-907f4cb85a5e.png)

**Comment by purpleposeidon** [comment]
Does the texture update if you place blocks near the incorrectly textured areas?

**Comment by CovertJaguar** [comment]
Possibly fixed by 1fa265ff0d14dab2b71f0fae47417831da4361a7
