### ISSUE TITLE
Rock Crusher voids input inventory when destroyed

### ISSUE THREAD

**Issue by SirSmashy** [CovertJaguar/Railcraft#450]
As the title suggests, when a Rock Crusher Multiblock is destroyed (e.g. with a pickaxe), only the output inventory slots are dropped into the world, the contents of the input slots are simply destroyed.
I have checked all the other multiblocks and they all seem drop their inventories just fine.

Tested with Railcraft 9.4.0.0 on Forge 7.10.85.1270

**Comment by liach** [comment]
Oh, have you tried to build it again at the same place? Maybe you will find those things  in its inventory.

**Comment by SirSmashy** [comment]
Yes I have. This issue only occurs when enough blocks are broken to make the Rock Crusher eject its output inventory. As long as you only take out a few blocks both inventories are retained.

**Comment by Yopu** [comment]
I think this is a similar issue to the steam boiler bug I squashed a while back. It had to do with slave/master inventory issues when broken.

**Comment by liach** [comment]
So it'll be the bug of all the multiblock structures not only Rock Crusher.

**Comment by CovertJaguar** [comment]
Appears to be an issue with sided handling of the inventory.
