### ISSUE TITLE
NoClassDefFoundError when removing Buildcraft

### ISSUE THREAD

**Issue by Ianaver** [CovertJaguar/Railcraft#454]
when I remove buildcraft from my mods this crash happens (otherwise its fine)

link:http://pastebin.com/G6aLVFGg

**Comment by CovertJaguar** [comment]
Only way that could happen is if you modified the jar to remove the Buildcraft API folder.

**Comment by Ianaver** [comment]
sorry but I didn't modify the mod files, I also redownloaded and removed any previous files made by RailCraft and it still doesn't let me on unless buildcraft is installed :(

**Comment by Ianaver** [comment]
does uploading a video help just to prove I did nothing?

**Comment by CovertJaguar** [comment]
Try with only Railcraft installed. If that works, then likely some mod is crashing during init and interrupting the mod loader's classloading routine.

**Comment by Ianaver** [comment]
ok I will give that a shot

**Comment by Ianaver** [comment]
ok it must be another mod, My apologies.

**Comment by Ianaver** [comment]
its rotorycraft, I will go ask rieka about it
