### ISSUE TITLE
Steam trap issue

### ISSUE THREAD

**Issue by ipatrol** [CovertJaguar/Railcraft#457]
I was attempting to operate a manual steam trap, when I found that while it consumed steam, damaged entities, and made hissing noises, no visible steam came out, despite me having all particles enabled. If I broke the block as soon as it activated, I would see a ball of steam particles where the block was, as if they were trapped inside.
![Steam ball](http://ibin.co/1njepN5QxUx5)
The same thing happened with the automatic steam trap, and there are no obvious incompatibilities in my mod list.

Would suggest looking at the following lines (though neither of them seem to have changed recently):
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/client/particles/EntitySteamFX.java#L22
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/blocks/machine/alpha/TileSteamTrap.java#L69

**Comment by CovertJaguar** [comment]
I recently refactored the particle classes, its possible I messed something up.

**Comment by CovertJaguar** [comment]
Closed by 30a5aeab4cbb23c3160c1ae1419c04d61b3aa5af

**Comment by ipatrol** [comment]
Thanks, that was refreshingly quick.
