### ISSUE TITLE
UBC integration

### ISSUE THREAD

**Issue by Adaptivity** [CovertJaguar/Railcraft#458]
More information can be found here: https://github.com/ForestryMC/ForestryMC/issues/441

**Comment by CovertJaguar** [comment]
Does it work with custom renderers or will that need to be disabled? My ores already do overlay rendering.

**Comment by Adaptivity** [comment]
I'm not sure about it. Try to ask Zeno410 about it. He should know better.

**Comment by Adaptivity** [comment]
Handled by http://minecraft.curseforge.com/mc-mods/227992-ubc-ore-registrar now.
