### ISSUE TITLE
Support for Terrafirmacraft

### ISSUE THREAD

**Issue by dexman545** [CovertJaguar/Railcraft#459]
Would it be possible for Terrafirmacraft's fresh water to be viewed as vanilla water in railcraft?

**Comment by CovertJaguar** [comment]
What is the fluid tag for Fresh Water?

**Comment by dexman545** [comment]
I am not certain, but I believe the tag is Material.water 
TFC has also ore dictionaried there water buckets as vanilla water buckets.
This is the github for TFC since I do not know what a fluid tag is: https://github.com/Deadrik/TFCraft

**Comment by cabralRodrigo** [comment]
I guess is "freshWater" if I look in the right place.
https://github.com/Deadrik/TFCraft/blob/master/src/Common/com/bioxx/tfc/Core/TFCFluid.java
Line 22

**Comment by Vexatos** [comment]
@cabralRodrigo Then it would be "freshwater".

**Comment by cabralRodrigo** [comment]
@Vexatos Yeah... My bad :)

**Comment by CovertJaguar** [comment]
Could someone explain why TFC has "freshwater" and whether it also uses "water" and if converting from "freshwater" to "water" is bad?

I'm investigating how to support "freshwater" and its looking like the simplest way is to simply convert any "freshwater" inputs into "water" when filling my machines.

**Comment by cabralRodrigo** [comment]
@CovertJaguar I don't think the conversion is a bad thing, since the only use of fresh water is crafting and for drink in TFC

**Comment by dexman545** [comment]
There would be no problem with converting it, as long as this conversion only applies to fresh water and not salt water. Also, would it be possible for RC to recognize TFC barrels as valid liquid storage? Tanks can not currently draw liquid from them.

**Comment by vidaj** [comment]
Just to let you know, I have made a stopgap solution for TFC water and Railcraft (and other mods) as a separate mod. It just changes vanilla water in the fluid registry to be TFC fresh water. 

http://minecraft.curseforge.com/mc-mods/228547-tfcwatercompatibility
https://github.com/vidaj/TFCWaterCompatibility

It's a giant hack, but it works.

**Comment by liach** [comment]
TFC died at 1.7. Although there is a TFC2, create a new issue if this is still a problem.
