### ISSUE TITLE
Electric Locomotive pulling energy is very slow

### ISSUE THREAD

**Issue by Paul17041993** [CovertJaguar/Railcraft#461]
when an electric locomotive has a IC2 energy cart (MFE and CESU at least) and is pulling power from it it moves very slowly, but if the shutdown button is pressed it does a very sharp burst of speed before stopping, looks like each tick it fills its storage but then skips giving itself momentum, to then do so the next tick as the store was filled from the last, making it barely mobile.

**Comment by liach** [comment]
Not a bug but a feature, see post for Version 9.4.0.0 at http://railcraft.info/

**Comment by Paul17041993** [comment]
uh, where does it mention that the electric locomotive should move slowly or near not-at-all...?

**Comment by Paul17041993** [comment]
oh I see, it's mentioned for 9.3.0.0, not 9.4.0.0, but what in the world is the use of such a train then if it cant make a walking pace when given a capacity boost? and what if we wanted it to not drain from the cart at all?

Idea being we intended to use them on high-speed rail, of which electric rail is completely incompatible and it needs to make a good 500m distance at least without having to slow down every 100m. There's also a second use where we want to cart EU around, also at high speed and preferably in a train.

**Comment by CovertJaguar** [comment]
There has to be some drawback. Choices are necessary, there will never be a solution that is perfect for all cases all the time.

But yes, I'm aware that Electric Locomotives should have be able to travel at on High Speed Tracks somehow. I've just not decided how I want to do it.

**Comment by Paul17041993** [comment]
overhead wire, siderail, replace the electric track with an attachable 3rd rail that is essentially a macro-generated set of copy tracks of the rest (standard, reinforced, HS, etc), haven't looked at the specifics of how you use the metadata though, but if there's still one bit available that'll do.
or just simply add a power variant of the HS rails, considering the distance the internal storage lasts only the one powered HS track is really needed.

**Comment by wooky** [comment]
I actually like the overhead lines the best. Maybe make them to be setup easily but be really inefficient and store next to no energy.

**Comment by Paul17041993** [comment]
only problem being for overhead is how short these locos are, even when blocks above that's still very short compared to the average 4.4M height that most countries use...

side rail would work well though, to add to that it would be good if it were multi-sided so you could run it between two tracks one block apart and have it power both. Style for the side rail you could do akin to how the london underground does the outer rail on their 4-rail track (they have to use an extra negative rail to prevent current flowing through the tunnel walls and pipes).

**Comment by wooky** [comment]
We could put the line 3.5-4.5 meters above the track so that it would be sufficiently high, and then maybe add a pantograph which goes from the locomotive to the overhead lines. Right now, though, I can't really think of a way that won't look silly.

**Comment by Sidorion** [comment]
What about a powered railbed? There is already this cover for electric cables. This could power the rails from below. 
That way you could electrify your tracks with the undercutter and it would be no matter which track you lay above, it would be powered.

**Comment by Paul17041993** [comment]
that would actually fit the bill for the 3rd rail perfectly, render-wise it would only need to draw an extra quad a little above the rail above it...

**Comment by CovertJaguar** [comment]
Possibly solved by issue #480

**Comment by Paul17041993** [comment]
would this see the removal of draining from EU carts? because its kinda stupid if the loco can get adequate power itself but is still slowed down only because a EU cart (that its meant to be taking to the destination) is attached...

**Comment by wooky** [comment]
Perhaps the EU cart should be re-purposed as a general energy transfer cart to, for example, deliver energy from one plant to another by means of rail.

**Comment by Paul17041993** [comment]
exactly what I mean, not really any point having this feature anymore and EU carts have a lot of use on their own. Like carting crates of batteries (which could be done anyway mind you...).

**Comment by CovertJaguar** [comment]
Batteries are heavy, and have the lowest priority for power draw down. *Shrugs*
