### ISSUE TITLE
Chest carts and GregTech metaitems

### ISSUE THREAD

**Issue by retep998** [CovertJaguar/Railcraft#462]
GregTech metaitems implement IFluidContainerItem.
Railcraft doesn't allow fluid containers in minecarts by default to promote usage of tank carts.
As a result GregTech metaitems cannot be stored in minecarts, even those most are incapable of storing fluids.

**Comment by CovertJaguar** [comment]
@immibis If you want me to merge that you'll need to sign the CLA: https://www.clahub.com/agreements/CovertJaguar/Railcraft
