### ISSUE TITLE
Blocks missing step sound in multiplayer.

### ISSUE THREAD

**Issue by PaperTriangle** [CovertJaguar/Railcraft#464]
Some blocks are missing step sounds when played in multiplayer, namely any block that shares a blockID with "Block of Steel".

**Comment by CovertJaguar** [comment]
Do Posts, Stairs, and Slabs not have this issue? The do things slightly differently.

The Walls do things the same way as the Cubes (ie Block of Steel). Do they also have the issue?

**Comment by PaperTriangle** [comment]
Posts, Stairs, Slabs and Walls all seem to have the issue on Multiplayer, however Posts and Walls don't make step sounds in single player, either. The platforms on the same BlockID as "Wooden Post" and "Metal Post" also suffer from this, however the coloured Metal Platforms work fine on both.

**Comment by CovertJaguar** [comment]
Colored Metal Platform do not use any kind of custom sound handler as they have a single sound type for all varients, the others however intercept sound events and change the sound played.

**Comment by CovertJaguar** [comment]
Wish I knew how to fix this. =/
