### ISSUE TITLE
[Suggestion] Control the locomotive track with a signal controller

### ISSUE THREAD

**Issue by wooky** [CovertJaguar/Railcraft#468]
One thing I never understood about the locomotive track is how to start up the locomotive automatically after being stopped by the track. I propose for it to act as a signal receiver, and act according to the aspect it's receiving, along with being controlled by a redstone signal.

When unpaired, it should act normally, where you can change its behavior with a crowbar and activate it with a redstone signal.

But when it is paired, crowbar and redstone signals are ignored. Instead, when it receives a red aspect, it stops the locomotive, on yellow it makes it idle, and on green it makes it run. On any other aspect, it's turned off and acts as a regular track.

**Comment by CovertJaguar** [comment]
Generally Locomotives travel to fast to actually stop on the Locomotive Track. They typically stop on the track after. If this track is a Locking Track in Boarding Train mode, it can just boost the locomotive onto a following track set to turn the Locomotive on.

You suggestion would also require turning the Locomotive Track into some kind of Locking Track variant.

**Comment by Vexatos** [comment]
Maybe a combined track? The Locomotive Locking Track?
Anyways, I don't really like the idea, this would make the locomotive track far too special. Just do what CovertJaguar suggested, use a limiter track to make the locomotive pass the track at full speed and then use a locking track and another locomotive track. This will work just fine.
A signal-controlled would remove the need for exactly this kind of complex thinking, which pretty much is the entire point of this mod, in my opinion.

**Comment by wooky** [comment]
Alright, fair enough! Yeah, it makes sense not to make the mod too easy, and I suppose that your alternative solution is much easier to implement anyways.

I'll go ahead and close this.
