### ISSUE TITLE
Bug with DragonAPI

### ISSUE THREAD

**Issue by 4TheGame3** [CovertJaguar/Railcraft#472]
Halp! my world is bugged for a conflict with dragonAPI, here's the error:
http://pastebin.com/QaLZEvjD
Please answer soon!

**Comment by CovertJaguar** [comment]
Hi, I'm sorry, somehow you managed to get the wrong tile entity paired to a block. As a possible work around you can try disabling the residual heat block in the Railcraft block config.

**Comment by 4TheGame3** [comment]
its a common error, ive found other posts, please fix!

**Comment by AEnterprise** [comment]
@4TheGame3 this error isn't due to railcraft it's on the dragonAPI side of things, the crash is dragon api asuming the TE is one of it's own TE's but it's a railcraft TE so it crashes

**Comment by 4TheGame3** [comment]
ok thanks. i also posted this error on dragonAPI github.
