### ISSUE TITLE
Flux-infused pickaxe problem

### ISSUE THREAD

**Issue by marcin212** [CovertJaguar/Railcraft#473]
When using the Flux-infused pickaxe(from redstone arsenal) while empowered, if a block from Railcraft (e.g. any Steam Engine) is in the 3x1 area, it gets destroyed instead of picked up or ignored.
Railcraft Version: 	9.4.0.0

**Comment by CovertJaguar** [comment]
This is almost certainly an issue for Redstone Arsenal.

**Comment by marcin212** [comment]
@KingLemming  says that the issue is in in RailCraft.

**Comment by KingLemming** [comment]
One of our testers just tried it - can't make it happen, actually.

**Comment by marcin212** [comment]
before: http://i.gyazo.com/4c9888e20b6bc8ef7a1c258f15bff372.png
after: http://i.gyazo.com/e481d8ce565e506641f913ea887a1826.png
modlist:http://i.gyazo.com/f83e9bf568c174fb9769c8d40d002e25.png
