### ISSUE TITLE
[Suggestion] Add burntime bonus to blocks of CoalCoke

### ISSUE THREAD

**Issue by wshadow** [CovertJaguar/Railcraft#475]
In vanilla minecraft Coal blocks have a higher BurnTime then 9 individual pieces of Coal combined (smelts 10 times 8 Items vs. 9 times 8 Items in a furnace). I think it wold be nice to have a similar bonus with blocks of Coal Coke.

Quote from Gamepedia: "One block of coal smelts 80 items, which is more than the smelting time of the 9 coal items used to craft it."

**Comment by CovertJaguar** [comment]
What is the fuel value of a Block of Coal?

**Comment by wshadow** [comment]
I don't know the exact internal numbers, but a Block of Coal has 10 times the burn time compared to a single piece of coal.

Ps.: just noticed that that part of the original text got lost due to formating fails :(

**Comment by liach** [comment]
Coal Block: 80 items=32000 fuel value
Coke Block: 144 items=57600 fuel value
(in vanilla furnace)
That will make Coke more useful in Bores or Steam Boilers.

**Comment by wshadow** [comment]
Yes, a Coke Block is better then a Coal Block. But according to my experience and mods.railcraft.common.plugins.forge.FuelPlugin the burntime of a Coke Block is equal to 9 pieces of Coke.

**Comment by liach** [comment]
The purpose is to change the fuel value of coke block to 64000.

**Comment by liach** [comment]
And to change coke block into flammable block.

**Comment by CovertJaguar** [comment]
I hope its not 64000, because that massively overflows the short in the GUI burn progress packet.

**Comment by liach** [comment]
Oh I thought wrong, 57600 is the value in 1.6, which can cook a steel with a coal coke. Since one version in series 8 the heat reduced, it should be 32000 now.

**Comment by wshadow** [comment]
My pull request fixes the original issue. I didn't change anything regarding the suggestion from @liach: "change coke block into flammable block"
