### ISSUE TITLE
[9.4.0.0] Railcraft Disables NEI

### ISSUE THREAD

**Issue by MrBibliophile** [CovertJaguar/Railcraft#477]
Tested with: Forge 10.13.2.1236 and 1240
                    NEI 1.0.3.68 and 74
                    Railcraft 9.3.0.0 and 9.4.0.0

Upon installing Railcraft 9.4.0.0, NEI becomes entirely non-functional (not showing up in-game), not responding to any command and generally acting as if it was not installed at all, despite still being listed under the Forge mods list accessed from the Main Menu. This was tested with only Railcraft and NEI installed, as well as with other mods, and NEI functions normally under all circumstances where Railcraft 9.4 is not installed.

**Comment by Forecaster** [comment]
Provide logs.

**Comment by MrBibliophile** [comment]
Shiiiit. I feel really stupid right now. Was trying to get the logs on Pastebin when I realized that I hadn't tried regenning the configs. Needless to say, that fixed it. That's what I get for trying to trace down a bug a 1am. Sorry for wasting your time.

**Comment by Forecaster** [comment]
No worries. Please close the issue if it's not needed anymore.
