### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by Zaflis** [CovertJaguar/Railcraft#479]
Playing a custom pack, heavily modified from DW20's 1.7.10 pack, i have updated forge and almost every single mod. Whole config folder was deleted to let all mods regenerate their defaults. I was in my base, not doing much of anything when client suddenly crashed. It was after some hours of playing, so very rare. 1 other player crashed aswell on the server, which itself doesn't report anything else than player disconnecting. Also we have never built lanterns, so it's weird it's mentioning those in the log.

Current CompileTask:
C2:11886449 40931       4     mods.railcraft.common.blocks.aesthetics.lantern.BlockLantern::func_149666_a (64 bytes)

Full crash log from MultiMC:
https://www.dropbox.com/s/nsqj3kam20vd5qd/hs_err_pid5352.txt?dl=0

Also what seems duplicate issue from FTB:
http://support.feed-the-beast.com/t/dw20-v1-0-3-1-7-10-crash-to-launcher/9026

**Comment by liach** [comment]
Small Dumps? Available in Java but prohibited in windows? Wait to have a look.

**Comment by Yopu** [comment]
Looks like it's in the works.

**Comment by CovertJaguar** [comment]
There is a JVM command that can tell the JIT compiler to ignore that class, but I can't remember it off the top of my head.

**Comment by CovertJaguar** [comment]
Found it: 
```
-XX:CompileCommand=exclude,mods.railcraft.common.blocks.aesthetics.lantern.BlockLantern::func_149666_a 
```
