### ISSUE TITLE
Error in console.

### ISSUE THREAD

**Issue by Pilad** [CovertJaguar/Railcraft#482]
If not installed Thaumcraft, then many errors on Thaumcraft api.

**Comment by liach** [comment]
@Pilad 
1. Need more description, such as fml logs;
2. The api error is mostly on api provider side. If you tell more then we could look into it.

**Comment by Bug38** [comment]
I've the same errors, it seams to be directly from the thaumcraft api which is included inside a lot of mods. So this is not a Railcraft error, but a thaumcraft error I think...

**Comment by CovertJaguar** [comment]
Or DragonAPI, every API error I've seen in the past two months was caused by DragonAPI.
