### ISSUE TITLE
[Suggestion]: bigger Curved Rails&Switches and afew other things:

### ISSUE THREAD

**Issue by mariodk** [CovertJaguar/Railcraft#483]
alittle too lazy since the whole idea of this is here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/requests-ideas-for-mods/2336215-help-me-code-this-mod-i-even-made-textures-so-you#c7 i even made textures

this idea is meanly to make minecart trains to look better instead of only having 90 degrees curves&switches
or 45 degree up/down slopes aswell as no support blocks or anything under slopes and having diagonal rails aswell

this Track idea also kinda make it possible(or more make it look good) to have bigger trains/minecarts like a double minecart(2 mans or double chest or 1x player/single chest) minecart or locomotion+minecart in 1

anyway here is a preview of the textures i have made for bigger Curved Rails&Switches:
http://imgur.com/a/ykKTz#2 (i can send the real textures without iron blocks on the background soon)
i would have tried to make this myself as a standalone mod(but at same time a railcraft mod so the mod also add switches if railcraft installed) but i dont know a thing about Java/minecraft modding and coding

**Comment by CovertJaguar** [comment]
There are other mods that do this, Railcraft will stick with Vanilla style Tracks. What you describe isn't possible without completely rewriting all the minecart code. And there is a lot of it.

**Comment by mariodk** [comment]
but thats the problem there is infact no other mods that do this

**Comment by leagris** [comment]
trainncraft does it: https://www.youtube.com/watch?v=UyvF90w3hek

**Comment by mariodk** [comment]
its for 1.6.4 & does not work with minecarts & the locomotion from RC

**Comment by CovertJaguar** [comment]
> does not work with minecarts & the locomotion from RC

And that is exactly why it will probably never happen, because the only way to make it happen is to core-mod the heck out of EntityMinecart, RenderMinecart, and who knows what else and at what cost.
