### ISSUE TITLE
Rebar Ownership.

### ISSUE THREAD

**Issue by cainland** [CovertJaguar/Railcraft#485]
Rebar doesn't seem to be owned by a mod. If i use a mod based filtering system it shows up as UNKNOWN. I noticed this problem in particular with logistics pipes.

**Comment by CovertJaguar** [comment]
What version are you running?

**Comment by CovertJaguar** [comment]
Oops

**Comment by cainland** [comment]
9.4.0.0 sorry i didn't even think to put that on there.

**Comment by CovertJaguar** [comment]
I can't see any differences registration wise between the Rebar and say Plates or Gears.

**Comment by cainland** [comment]
just checked with ender io mod filter and their item conduits. it doesn't detect the mod as anything at with rebar. other railcraft items are detected tho. i don't know of any other mod filtering mods to test it with but it doesn't work with logistics pipes or ender io.

**Comment by cainland** [comment]
with some further testing locomotives, track relayer cart, electric meter, ,undercutter cart, remover cart and some other items also do not get detected. i don't know if this is related but @mod.Railcraft in nei omits these same items. it shows the others that are detected tho.

**Comment by CovertJaguar** [comment]
Well it appears I need to know more about how these mods are getting this information (or not getting it in this case).

**Comment by warlordjones** [comment]
This is how EnderIO does it: https://github.com/CrazyPants/EnderIO/blob/ccd589214ec1a7b7373ce49ae3a99203c0322c8f/src/main/java/crazypants/enderio/conduit/item/filter/ModItemFilter.java#L62

**Comment by CovertJaguar** [comment]
As far as I can tell that should work. Rebar is registered to the game registry like everything else.

**Comment by WoodStone** [comment]
This is fixed in 9.5.0.0
b0d131d27551e0f0bb464913d78e54f29c99c937

**Comment by CovertJaguar** [comment]
Oh, heh.
