### ISSUE TITLE
hs_err C2 Compiller Thread

### ISSUE THREAD

**Issue by ArcasCZ** [CovertJaguar/Railcraft#487]
Hello there!

My friend's game get crashed after opening inventory. He found hs_err in mc folder, so i asked him for this file and i found there is information about compiler task with some railcraft class. So i want to ask you, where i the problem? :-)

File: http://pastebin.com/L3WxS8p7

Thank you and sorry for my bad english ;)

**Comment by liach** [comment]
Glad to see you! You met a bug that had been fixed? As reported in #479. CovertJaguar fixed it in https://github.com/CovertJaguar/Railcraft/commit/32281d8cff0f6c360ad5baf83dbeb41b8b1002d4
Have a try in 9.5!

**Comment by ArcasCZ** [comment]
So where i can download it?

**Comment by liach** [comment]
Sadly the beta is not open to the community, except CJ's patreons.(means donators,wrong spellings) You can fork the project, run ./gradlew setupCIWorkspace build   to get one? Which has Modt features but cannot load existing world because sth wrong with the emblem.

**Comment by CovertJaguar** [comment]
/me needs to push beta's more often too
