### ISSUE TITLE
Unable to build Railcraft on Windows 10 with JDK 8 Update 31

### ISSUE THREAD

**Issue by KamranMackey** [CovertJaguar/Railcraft#488]
@CovertJaguar For some reason, when I'm trying to build Railcraft, Gradle skips most of the tasks such as decompiling Minecraft & Railcraft and the deobfuscateJar task, and I don't know why over 50% of the tasks are being skipped. Can we not use Java 8 to build Railcraft? I attached a photo of the tasks being skipped. I really want to build Railcraft, but stupid Gradle isn't letting me. Please help. :disappointed: 

![build issue](https://cloud.githubusercontent.com/assets/1617100/6037558/2efa6360-ac12-11e4-848a-15a9f8239742.PNG)

**Comment by KamranMackey** [comment]
@CovertJaguar Nevermind. All I had to do was do 'gradle cleanCache' and now it's working. :)

**Comment by KamranMackey** [comment]
@CovertJaguar Actually nevermind again. It still fails to build when I do 'gradle build'. For some reason it always fails at the ":compileJava" task, and I don't know why. Below is a screenshot of what happens. 
Could you please help?
![build issue](https://cloud.githubusercontent.com/assets/1617100/6037846/26966392-ac15-11e4-9479-cf97e3cfefe7.PNG)

**Comment by AEnterprise** [comment]
@KamranMackey it looks like the RC api is missing, that's a submodule, did you pull that in? git often misses that when cloning

**Comment by CovertJaguar** [comment]
Yeah, try 'git submodule init'

**Comment by KamranMackey** [comment]
@CovertJaguar @AEnterprise okay. Will do that, and then I'll try building again.

**Comment by KamranMackey** [comment]
@CovertJaguar @AEnterprise Tried it, still fails to build. Tried doing "git submodule update" and it keeps trying to use SSH to clone the repos. SSH is something I don't have set up.

**Comment by KamranMackey** [comment]
@CovertJaguar @AEnterprise Nevermind! I just had to open .git/config and then change all the SSH urls for the submodules to HTTPS ones and I was able to build Railcraft successfully. Thanks for all the help!
