### ISSUE TITLE
JVM Crash

### ISSUE THREAD

**Issue by Neodark7** [CovertJaguar/Railcraft#492]
I don't have a minecraft crash-report but a Java crash-report apparently, i don't know if it's caused by railcraft but railcraft is mentionned a the start and end of the seconde file :/

https://www.dropbox.com/s/sbx9xxcx258gd9v/hs_err_pid3436.log?dl=0

https://www.dropbox.com/s/wmp6kcd5u6op0w0/replay_pid3436.log?dl=0

**Comment by Neodark7** [comment]
PS maybe a java 8 issue i have this since i update java

**Comment by liach** [comment]
Duplicated with #479 and was fixed in https://github.com/CovertJaguar/Railcraft/commit/32281d8cff0f6c360ad5baf83dbeb41b8b1002d4

**Comment by Yopu** [comment]
See: https://github.com/CovertJaguar/Railcraft/issues/479#issuecomment-72161966
