### ISSUE TITLE
Crash with chisel after updating

### ISSUE THREAD

**Issue by Staegrin** [CovertJaguar/Railcraft#493]
After updating to Railcraft_1.7.10-9.5.0.0. The game would start loading and then crash to desktop. I've narrowed down the cause to the chisel mod  (Chisel2-2.3.4.30). Without this mod or downgrading to version (Railcraft_1.7.10-9.4.0.0) there is no crash.
crashlogs:
http://pastebin.com/gzNLrZPk
http://pastebin.com/2rv1ZDAW

Will cross-post this on their github as well.

**Comment by CovertJaguar** [comment]
I believe its already been fixed.
