### ISSUE TITLE
Liquid Firebox missing recipe

### ISSUE THREAD

**Issue by hanakocz** [CovertJaguar/Railcraft#499]
Hi, 
I just updated to the newest build and we fount that Liquid Firebox has no recipe.
We are good to write it back via MineTweaker, but somebody can be worse on that. 

And one question. <Railcraft:tile.railcraft.machine.alpha:15> disappeared, what was that machine? And did it changed name or was removed?
Thanks

**Comment by hanakocz** [comment]
We found a lot more recipes missing.

**Comment by liach** [comment]
You used CraftGuide or NEI? Or craft them following the recipes on the wiki?

**Comment by hanakocz** [comment]
We use NEI, but also tried recipes from wiki. They are just gone. Via Minetweaker, we found that Railcraft machines changed their IDs from Railcraft:tile.railcraft.machine.alpha:15 to Railcraft:machine.beta:15...
Also recipe cooperation with GregTech etc is broken. If you need whole list of mods, I can give you some, but probably the change of naming did that ? 
For now, we add our own recipes via minetweaker to be able to play, however it is the solution for somebody, who knows what is doing...

**Comment by CovertJaguar** [comment]
Changing the name should have no effect on the recipes.

**Comment by Dream-Master** [comment]
Maybe i can ask in GT Forum? . What is changed in 9.5 because all my Minetweaker Scripts give a tone of errors.

**Comment by CovertJaguar** [comment]
I removed the 'tile.railcraft.' prefix from all the blocks and block item stacks.

**Comment by hanakocz** [comment]
Dream-MAster, for Minetweaker you need to change item names, then it is Okay. 
Can be done that some recipes are changed by GT (for example to get oredicted steel plates) , even there is no visual change (valves) , and then change of prefix causes to not add the recipes? (But why they are removed then? )
For our measurement, just Steel items are missin recipes

**Comment by CovertJaguar** [comment]
Well Gregtech removes pretty much ALL my recipes then registers new versions with strange ore-dictionary entries...

**Comment by hanakocz** [comment]
Then some idea why only some items are affected? You made same change for Iron tanks and also for steel tanks, yet only steel ones are missing...
I bugged Greg, but he is "awesome" ...making yet another big not compatible rewrite -.-

**Comment by CovertJaguar** [comment]
Well "ALL" might be an exaggeration. He probably only removes one that wants to change, but the list is at least a hundred lines long so I didn't look too closely the one time I looked at it.
