### ISSUE TITLE
[Question] Output/ Input Tank Valves

### ISSUE THREAD

**Issue by Dream-Master** [CovertJaguar/Railcraft#501]
I dont find any information about Input and Output amount from Railcraft tanks.
How much mB Fluids or Gases the Tank Valves let through some pipes (Gt pipes for Buildcraft)?
Is there a difference between Iron and Steel tanks (Valves)?
I using Iron Tanks connected with Gt pumps and i want to know the Output Rate.

**Comment by hanakocz** [comment]
As we know, it is 250mB/t , I think :)

**Comment by CovertJaguar** [comment]
Nope, as of 9.5 its now 1k mb/t.

**Comment by Dream-Master** [comment]
OK thanks.
