### ISSUE TITLE
[Enhancement request] World Anchor limite / logging

### ISSUE THREAD

**Issue by demethan** [CovertJaguar/Railcraft#502]
Hi, 

I'm an admin/ owner for a few private servers.
I'm wondering if it would be possible to add some sort of permission to the world anchor. A limit on the number of world anchor a player can have and a form of logging to txt file on the server.  (exemple: dim# xyz ign )

Something similar to Dimensional Anchor but that works. (jab intended)

Thank you for your consideration.

**Comment by CovertJaguar** [comment]
Both already exist. Use the **Official Forge Chunkloading Configs** to limit the number of personal chunkloading tickets that Railcraft can hand out and the "print.locations" config option.

**Comment by liach** [comment]
It's for each person...

**Comment by CovertJaguar** [comment]
?

**Comment by liach** [comment]
He just want different team of players can own/place different number or type of anchors. And how about type a command to get the anchors' info instead of looking into the log filled with junks?

**Comment by CovertJaguar** [comment]
Very well, I'll make a request for more info and a clearer design goal.

**Comment by demethan** [comment]
Thank you for the answer.  So much stuff is hidden or hard to make sens of.  I'm glad you were able to share this info. We will be testing this, I am sure it will do what we require. 

Regards.
