### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by ArcasCZ** [CovertJaguar/Railcraft#505]
Hello there!

Im getting server crash - here you are -> http://pastebin.com/Zw6grpn0

**Comment by liach** [comment]
Zombie and heat block-- You need to disable them.

**Comment by CovertJaguar** [comment]
What does this have to do with Heat Blocks?

**Comment by CovertJaguar** [comment]
There is only one possible way that function could crash with a Null Pointer Error, and that's if someone made a Core Mod that alters Block.onEntityCollidedWithBlock(). And that's because by default, its an empty function.

**Comment by ArcasCZ** [comment]
So, what now?

**Comment by liach** [comment]
You need to remove other mods and choose each core mod once to test this error happens when which core mod is installed. Mostly Core Mods have names like "one's lib(rary)" "one's util" "one's core".

**Comment by ArcasCZ** [comment]
I updated Cauldron to newest version and it looks like all is right.
