### ISSUE TITLE
Iron Tanks not forming on world load [Closed?]

### ISSUE THREAD

**Issue by Doty1154** [CovertJaguar/Railcraft#506]
On world load iron tanks do not form for me
![2015-02-11_14 09 17](https://cloud.githubusercontent.com/assets/7087748/6157615/a459de02-b1f7-11e4-94dd-01cd017143ef.png)
![2015-02-11_14 09 23](https://cloud.githubusercontent.com/assets/7087748/6157617/a45c2c0c-b1f7-11e4-964c-dc128fa6df67.png)
![2015-02-11_14 09 26](https://cloud.githubusercontent.com/assets/7087748/6157616/a45bd018-b1f7-11e4-87ed-c4196418f19e.png)

Here is my config folder

https://dl.dropboxusercontent.com/u/135914713/railcraft.zip

Modlist(Cause i can not type it all out)
![screenshot 2015-02-11 14 13 16](https://cloud.githubusercontent.com/assets/7087748/6157666/2f47952c-b1f8-11e4-9a79-d042c4965b7d.png)
![screenshot 2015-02-11 14 13 19](https://cloud.githubusercontent.com/assets/7087748/6157667/2f487230-b1f8-11e4-888c-051c76ea027c.png)
![screenshot 2015-02-11 14 13 01](https://cloud.githubusercontent.com/assets/7087748/6157668/2f4970e0-b1f8-11e4-82fc-b6528c803488.png)

And i checked its all in one chunk

And im running 9.5 Version of railcraft.

**Comment by liach** [comment]
Do you mean one part of it is broken when world reloads?

**Comment by CovertJaguar** [comment]
Further testing in IRC revealed that it doesn't happen with just Railcraft installed, so its probably another broken core mod or something. Seems like those are the only "bugs" I get anymore. Core Mods are evil.
