### ISSUE TITLE
Remove API files from jar to reduce compatibility faults.

### ISSUE THREAD

**Issue by Paul17041993** [CovertJaguar/Railcraft#509]
Remove the API files from other mods in the build script and add cpw.mods.fml.common.Optional calls to the implementing classes and overrides necessary.

Helps prevent compatibility faults occurring due to API mis-matching.

**Comment by CovertJaguar** [comment]
Come back after you've done a detailed analysis of the situation and determined which APIs can be safely removed without sacrificing functionality, interoperability, or independence and have a detailed plan for how to implement this separation (its not as simple as slapping @Optional on everything).

**Comment by Paul17041993** [comment]
Ill have a mod up on github soon that contains complete modularity while only containing its own files, key points apart from @Optional are isolation and NoSuchMethodError checking. The IC2 API probably needs this the most due to the rate it still changes and only having small parts of an API is problematic even further. I cant confirm if I'll make my own patching to railcraft at this stage.
