### ISSUE TITLE
Railcraft iron tanks only outputting 250mb/t

### ISSUE THREAD

**Issue by slawr34** [CovertJaguar/Railcraft#511]
After some testing I've found that iron tanks only output 250mb/t. Is this intentional?

**Comment by wshadow** [comment]
@slawr34 which versions of minecraft and railcraft are you on? And is this for a single valve or the sum over multiple valves?

**Comment by slawr34** [comment]
Each valve outputs 250mb/t. 1.7.10 with the latest version of Railcraft.

**Comment by CovertJaguar** [comment]
What version is "latest"?

**Comment by slawr34** [comment]
9.5. I tried replicating the bug in a new world and it seems to be fixed/not present.

**Comment by AEnterprise** [comment]
@slawr34 in the old world where the bug is present break and replace the old valves, that should fix it

**Comment by CovertJaguar** [comment]
Well...I can't honestly explain how the flow rate could possibly be persistent, but if it works....
