### ISSUE TITLE
Most Recent Railcraft spamming console on World/Sever creation

### ISSUE THREAD

**Issue by sProgg** [CovertJaguar/Railcraft#512]
Plausible Cause: java.lang.ClassNotFoundException: mods.railcraft.common.plugins.craftguide.EmblemRecipesPlugin

Console Spam: http://pastebin.com/qaVQnBZU

Seems Railcraft doesn't like my modpack anymore.

**Comment by liach** [comment]
It's caused by CraftGuide api. The emblem class called it and caused the bug. CJ may have a look.

**Comment by CovertJaguar** [comment]
And you are using an official build of Railcraft? Not something cobbled together from GitHub?

**Comment by CovertJaguar** [comment]
Citing lack of response, I'm going to close this.
