### ISSUE TITLE
Railcraft stops loading The Dark Trilogy modpack

### ISSUE THREAD

**Issue by DreadBoy** [CovertJaguar/Railcraft#514]
My friend is experiencing problems while launching TDT modpack. Entire log is available here: 

http://pastebin.com/cyVBu2dz

As you can see loading stops at Railcraft so I posted this issue on Railcraft Github. Does anybody know why is that so and what he can do?

**Comment by CovertJaguar** [comment]
I don't know what's causing it to stop, but its probably BluePower. The messages you are Railcraft responding to BluePower registering things with the OreDictionary.
