### ISSUE TITLE
Hobbyist's Steam Engine does not transfer quickly enough

### ISSUE THREAD

**Issue by Nova001Sol** [CovertJaguar/Railcraft#516]
A simple issue, the engine constantly builds up power when running on water and coal, only releases part of that power to the emerald kinesis pipe I have linked to a diamond one and a few resonant energy cells. This results in a permanent loss of a considerable amount of power, as the power stored in the engine starts draining as soon as I shut it off, but it doesn't output into the cells either. I have tried it with BuildCraft piping, Ender IO and a direct engine-to-cell connection, but the problem persists.

**Comment by CovertJaguar** [comment]
Normal operation of the Engines (BC engines historically always operated like this).
