### ISSUE TITLE
Attempting to cast Heat Block TE to other mod TEs

### ISSUE THREAD

**Issue by warlordjones** [CovertJaguar/Railcraft#517]
I have encountered this bug in both Chisel (See github.com/TheCricket/Chisel-2/issues/#238) and my personal mod SC2 - in the bounding box method somehow the TileHidden is overwriting other tile entities. It needs further investigation, which I have been attempting myself.

**Comment by CovertJaguar** [comment]
Unfortunately, if that is true, its a bug in Forge. Make sure you have the latest version of Forge.

The reason I say this is that the code that places the heat blocks explicitly checks for normal vanilla Air before placing anything.

**Comment by warlordjones** [comment]
Ok.
