### ISSUE TITLE
Server crash if invalid Regex is supplied to routing table

### ISSUE THREAD

**Issue by cpw** [CovertJaguar/Railcraft#518]
https://gist.github.com/cpw/e5a1ddc39d4086b4b17f occurs and takes down the server if the routing table is not a valid regex. Probably should catch and ignore somehow. This is a server murderer btw - the server won't start without somehow deleting the block..

**Comment by ssotangkur** [comment]
Looks like you are using the Railcraft Beta release, is that correct?
I can't see CovertJaguar's code release for the beta, but the pull request that I created (https://github.com/CovertJaguar/Railcraft/pull/497/files) has the logic.isValid() check on TileSwitchRouting.java:120 which should keep that from happening. I'll check with CJ to see what's going on.

**Comment by CovertJaguar** [comment]
@ssotangkur the switch code is here: https://github.com/CovertJaguar/Railcraft/tree/switches

**Comment by CovertJaguar** [comment]
I think this might actually be my fault. I probably need to add some more error handling for the new Regex stuff. I don't recall specifically testing invalid Regex strings.

**Comment by CovertJaguar** [comment]
Hmm...this might be worthy of a hotfix.
