### ISSUE TITLE
Crowbar with Destruction turns Concrete block into Coke block

### ISSUE THREAD

**Issue by Xariyl** [CovertJaguar/Railcraft#519]
This was an fun one. I have a set of rails on a crushed obsidian path, with concrete blocks on either side of the obsidian. When removing the rails with a crowbar enchanted with Destruction, the surrounding concrete blocks break and turn into Blocks of Coal Coke.

This seems to only effect full concrete blocks; slabs, stairs, and walls are not affected.

Using version 'Railcraft_1.7.10-9.5.0.0"

**Comment by liach** [comment]
Does this bug also occur when destroying concretes with crowbars?

**Comment by Xariyl** [comment]
Didn't think of that before. Just tested now, and yes it occurs when destroying only the concrete blocks, even without rails on them.

**Comment by CovertJaguar** [comment]
I wonder if this is related to #387 or #389

**Comment by liach** [comment]
The method needs improvement. It doesn't return meta and destroying player.
