### ISSUE TITLE
Enchantments should be disableable and in the Magic Module.  

### ISSUE THREAD

**Issue by CovertJaguar** [CovertJaguar/Railcraft#521]
Just a todo, see title.

**Comment by liach** [comment]
Enchantment and firestone? A mess.

**Comment by CovertJaguar** [comment]
No?

**Comment by liach** [comment]
I'm wondering about some unimplemented features, such as magic locomotive, waterstone... And milestones. And 1.8. Lastly, it is really weird to put Enchantments and Firestone together.

**Comment by CovertJaguar** [comment]
Well the Firestone can still be disabled separate from the Module.
