### ISSUE TITLE
Train not departing when you put in the ticket

### ISSUE THREAD

**Issue by Johnne25** [CovertJaguar/Railcraft#522]
Then you put a ticket in the train it does not start to move.

**Comment by CovertJaguar** [comment]
Um...yes?

**Comment by Johnne25** [comment]
I have tried everything to get it to go.  Is there something I am missing?

**Comment by liach** [comment]
Did you give it electricity or water with fuel? Did you switch its mode to running? Did you place it on locking tracks?

**Comment by Johnne25** [comment]
Yes I have done all that.  I tried all the locking track modes as well.

**Comment by Forecaster** [comment]
You can't just say you've "tried everything". Either you need to explain what you're doing, or show us with screen shots or video. --------- Original Message ---------
From: Johnne25 
To: CovertJaguar/Railcraft 
Date: Mon Mar 02 05:02:34 CET 2015
Subject: Re: [Railcraft] Train not departing when you put in the ticket (#522)

Yes I have done all that.  I tried all the locking track modes as well.

**Comment by Johnne25** [comment]
I have a track using standard rail, the train stops on a locking track.  I have the locking track set to Hold Train Mode.  I get in the train cart then place the ticket into the train.  The train does not start to move.  There is text over the train which shows the destination I have in the ticket.    

I put a lever beside the track and when togged the train does start to move. 

I tried Train Boarding Mode and Train Lockdown Mode as well
