### ISSUE TITLE
Railcraft engines don't properly transfer RF to Thermal Dynamic's flux ducts.

### ISSUE THREAD

**Issue by l3CY** [CovertJaguar/Railcraft#523]
Steam engines don't seem to be passing their produced RF off into Flux Ducts and are instead storing a good portion of their energy then heating up to their maximum.  I've attached an image to show exactly what I'm referring too.  The flux ducts involved have a throughput of 800RF/t.

http://i40.photobucket.com/albums/e230/SlightlyVisible/2015-02-26_23.46s.00%20-%20Copy%20-%20Copy_zpskgibdcah.png

**Comment by Vexatos** [comment]
Isn't that intended behaviour?

**Comment by l3CY** [comment]
Perhaps I'm wrong.  Do Railcraft's, Build-Craft's, and Forestry's engines no longer all behave the exact same?  For instance, under the same conditions Build-Craft's combustion engines will not turn past green, while Forestry's will not turn past yellow.

**Comment by AEnterprise** [comment]
BC engines will turn past green like they used to, they won't explode anymore if they overheat but they will overheat, turning them black and then they need a hit with a wrench to work again

**Comment by CovertJaguar** [comment]
They have all evolved to the RF changes differently. This is intended behavior and imo the truest to the old implementations of MJ.
