### ISSUE TITLE
Railcraft steel tank valve receipe not working with GregTech

### ISSUE THREAD

**Issue by Auge103** [CovertJaguar/Railcraft#524]
Hi,
I'm using Railcraft 9.5.0.0 and GregTech 5.07.07.
Crafting steel tanks out of steel plates is possible, however, crafting steel tank valves and -gauges is not. The receipes dont show up in NEI as well.

This is what I tried to solve the problem (but it didn't work):
After disabling the steel plate unification from Gregtech, both receipes are showing up in NEI - but its not possible to craft them because there are only gregtech steelplates then.

Is this a bug or a feature? Why are tanks working but gauges/valves not?
(Iron tanks are working fine)

**Comment by CovertJaguar** [comment]
Sounds like gregtech bug to me.
