### ISSUE TITLE
Routing Switch Motor Crashes when determining faulty regex

### ISSUE THREAD

**Issue by SoulSkin** [CovertJaguar/Railcraft#527]
When a Routing Table has wrong regex and a cart comes by the Routing Switch Motor containing the faulty table, it crashes the game. This problem causes world "corutption" until switch motor is removed (I used MCEdit). The logic behind the regex code needs to catch the error and display an in-game error similar to syntax error. (error crash dump in http://pastebin.com/JRV9ZHtK) Problem at https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/blocks/signals/RoutingLogic.java

**Comment by liach** [comment]
Duplicate with #518 and had been fixed in 2b29dde6878d5f038950f77e6e10c6a7c61a165c
