### ISSUE TITLE
Question About Code Use/Licensing

### ISSUE THREAD

**Issue by yesimwearingpants** [CovertJaguar/Railcraft#528]
I am Writing A Mod (In Which I want too Have An ore generate only on the surface of caves). my Question is Can I use a Single unchanged class file from your mod, or is the 50% per class (rather than per program/mod [overall]) I'm not clear as to how that works.

**Comment by liach** [comment]
No. It should be less than 33% per class. If you disobeyed the LICENSE CovertJaguar will treat you like https://github.com/github/dmca/blob/c26be0862134cab97e27f04dff0c3855d64c73d9/2013-02-08-Railcraft.markdown

**Comment by yesimwearingpants** [comment]
Ok Thanks for Clearing that up, also my mistake must be another mod that said 50

**Comment by CovertJaguar** [comment]
@liach No its less that 25% of you mod can consist of my code (ie no repackaging Railcraft as your own mod with minor changes).
