### ISSUE TITLE
[Enhancement] Code Style improvement

### ISSUE THREAD

**Issue by liach** [CovertJaguar/Railcraft#529]
http://google-styleguide.googlecode.com/svn/trunk/javaguide.html
As I have seen now, Railcraft needs a house-cleaning. Use Intellij magic to clean up those imports, and add javadocs for every public/protected method, following the google java style?

**Comment by liach** [comment]
More, I think applying a plugin called "checkstyle" just like that one in Buildcraft and Sponge would improve the style.

**Comment by CovertJaguar** [comment]
Oh come on, its not that bad.
