### ISSUE TITLE
smoke from smoker stops working

### ISSUE THREAD

**Issue by TheQuadShot** [CovertJaguar/Railcraft#530]
If smoker gets covered with snow, it stops emiting smoke.

**Comment by Yopu** [comment]
[At the moment thats working as intended.](https://github.com/CovertJaguar/Railcraft/blob/2b29dde6878d5f038950f77e6e10c6a7c61a165c/src/main/java/mods/railcraft/common/blocks/machine/alpha/TileSmoker.java#L49)

However I could see it being something that might warrant an exception. 
That would be up to @CovertJaguar of course.

**Comment by liach** [comment]
`isTranslucent`?

**Comment by wshadow** [comment]
@liach I was also thinking about sth. like that. But there are several transparent blocks in the game that really should block the smoke e.g. glass, glowstone. On the other hand, there are some more examples which (probably) should not block the smoke e.g. glass pane, fence post, chest?

Also: I'm not sure how ```isTranslucent``` works on all of those blocks, and how other mods use this.

**Comment by liach** [comment]
Then the best idea is to prevent snow summon on the smoker.
