### ISSUE TITLE
Routing Switch not working on some computers

### ISSUE THREAD

**Issue by Johnne25** [CovertJaguar/Railcraft#533]
A desktop is running the Forge server.  I installsed Minecraft/Forge client as well on the desktop and copied the Mods frolder from the server to the client folder.

Everything works well except that the routing switches do not function.   The train always turns down the track regardless of the routing table.   

I installed Minecraft client on my laptop and also copied over the MODS folder.  I connect to the forge server on my desktop.  On the laptop the routing switch works.  

I have noticed that on the desktop the lights on the routing switch are flashing very quickly.  On my laptop the lights on the routing switch toggle slowly back and forth.

All computers running the same version of forge and connecting to the desktop forge server.

**Comment by Johnne25** [comment]
I managed to reproduce the problem using a MacBook Pro as well.  

I completely removed Minecraft from the Mac, redownloaded and installed.
I downloaded and installed Forge client.
I copied over the MODS folder.

Now all seems to be working again.    Seems older installs of Minecraft have something different or missing.

I will test reinstalling Minecraft on my desktop to see if it also resolves the issue there as well.

**Comment by liach** [comment]
Maybe the computer is not that good. Train passed before the routing table has given a result.

**Comment by Johnne25** [comment]
The desktop computer is by far the best out of all the computers I am using.  As I mentioned I seem to have solved the issue by reinstalling minecraft, forge and the mods.  I will test on the desktop computer this evening.  If so, I will let you know an this ticket can be closed.

**Comment by liach** [comment]
You set up servers on all of them or just on the desktop?

**Comment by Johnne25** [comment]
Only the desktop is running the server.  The laptop, Mac and desktop Minecraft clients all connect to the same server.

**Comment by liach** [comment]
So you should run the server on mac and connect using the desktop :shipit:

**Comment by ssotangkur** [comment]
There's a small window of opportunity where the routing switch motor has to calculate whether to switch the track or not and then set the track to that state before the cart reaches the switch track. If your server lags at all, it can miss that window.

The latest beta release has a fix for this. If you're using the beta, then its probably my fault, since I put it in.

**Comment by Johnne25** [comment]
Although the lights on switch motor still flash really fast the switch seems to be working.  You can close this issue.

**Comment by CovertJaguar** [comment]
um ok
