### ISSUE TITLE
Suggestion: Make Etched and Ornate stones more varied

### ISSUE THREAD

**Issue by purpleposeidon** [CovertJaguar/Railcraft#534]
The Etched and Ornate stones are all just recolors! So boring! The blocks mostly suggest their theme, perhaps someone can make cool textures?

Etched Blood Stained: Vampire Face
Ornate Blood Stained: Bloody swirls?
Etched Nether: Blaze Face
Ornate Nether: Nether Portal?
Etched Abyssal: Tentacles
Ornate Abyssal: Giant squid eye?
Ornate Infernal: Wither skeleton skull
Etched Infernal: ???
Etched Sandy: Keep the creeper
Ornate Sandy: Keep the chiseling
Etched Bleached Bone: Skeleton skull
Ornate Bleached Bone: Vertebra?
Etched Quarried: ???
Ornate Quarried: ???
Etched Frostbound: Cracked ice?
Ornate Frostbound: Snowflake?

**Comment by wshadow** [comment]
Should be possible to do with a resource pack? Or am I missing something? Cool idea for themed maps/servers though.

**Comment by CovertJaguar** [comment]
For the record, I am only using about a quarter of the metadata. I'm open to adding more variants (Carved?), but I don't think my art skills are quite up to the task.

**Comment by Generalcamo** [comment]
I can handle this, but I would prefer consistency between cosmetic blocks. I am perfectly open to additional cosmetic variants (Creeper Etched vs. Blaze Etched), but I am against this specifically.

I recommend closing this, but if someone were to open a new issue for general new variants, I would be perfectly willing to tackle that.

**Comment by liach** [comment]
Superseded by #1120
