### ISSUE TITLE
Train detector bug or linking bug?

### ISSUE THREAD

**Issue by BlizzardPenguin** [CovertJaguar/Railcraft#536]
I made a video to quickly show what the problem is http://youtu.be/YUCQ_hALm_c

**Comment by CovertJaguar** [comment]
Oh! Good catch! Looks like I need to rebuild the Train object when a cart dies.

**Comment by CovertJaguar** [comment]
Only problem is that there doesn't seem to be an event for that...

**Comment by ssotangkur** [comment]
This is a very well done example of how to show us a bug. Thank you for making the effort to file the issue.

**Comment by cpw** [comment]
I'm gonna speculate that this fix has broken trains completely in 9.5.0.2, sadly. They no longer work for anything at all, except perhaps this scenario?

**Comment by CovertJaguar** [comment]
Haha, yeah. That's what I get for not testing changes. 9.5.0.3 should work.
