### ISSUE TITLE
Add links to Crafting Guide http://crafting-guide.com

### ISSUE THREAD

**Issue by andrewminer** [CovertJaguar/Railcraft#538]
I've been working on a project to make it easier to deal with complex mods (especially tech mods), and I recently added support for Railcraft. The gist of the site is that you tell it what item(s) you want to make, and it will figure out all the raw ingredients you need along with step-by-step instructions. For example, here's how you make a [bunch of tracks, a couple of item loaders, and a few carts](http://crafting-guide.com/craft/16.minecart:2.item_loader:locking_track:64.track).

The maintainers of mods I've added (e.g., BuildCraft / Applied Energistics / EnderIO) have found it useful to include links to Crafting Guide in their official documentation, and I was hoping you would feel the same.  I'd be happy to make the changes to the wiki myself if you like the idea.

Thanks!

**Comment by wshadow** [comment]
So, this is the software you are running on that site: https://github.com/andrewminer/crafting-guide ?
I think I'll have to open some bug reports. Nice idea btw.

**Comment by andrewminer** [comment]
Yup, that's the one.  I'm using [Trello](https://trello.com/b/s9N0aTYd/crafting-guide) for my own planning, but it's read-only.  i've turned on the GitHub issue tracker so you can file whatever issues you notice.  Much appreciated!

**Comment by CovertJaguar** [comment]
This is really cool! I need to think about where I want to put some links, but for sure it will happen!

**Comment by andrewminer** [comment]
Thanks!  If you need help updating wiki pages (should you decide that's where it best fits), let me know.  I'd be happy to help get them in.

**Comment by andrewminer** [comment]
Any update on adding that link?  It would be much appreciated!

**Comment by andrewminer** [comment]
@CovertJaguar Any update?  I don't want to be a pest, but I can see how things might easily slip through the cracks.  As I said, I'd be happy to help make the edits if you'd like to give me permissions in your wiki.

**Comment by CovertJaguar** [comment]
@andrewminer  Yeah, sorry. It was pretty far down on my endless todo list. I've gone ahead and added a link on the wiki main http://railcraft.info/wiki/start

But if you'd like to do more with it, feel free. You don't even need an account to edit most pages.

**Comment by andrewminer** [comment]
Thanks!  I'll see what I can do.

**Comment by andrewminer** [comment]
@CovertJaguar FYI—I've finished adding in links in relevant places across the website.  Along with way, I fixed up whatever small inconsistencies / errors I saw.  Let me know if anything seems out of place.  Thanks!

**Comment by CovertJaguar** [comment]
Awesome!
