### ISSUE TITLE
Expanding the Metals chest & a couple locomotive ideas.

### ISSUE THREAD

**Issue by Opiboble** [CovertJaguar/Railcraft#540]
Hello! First off love the mod! Keep up the awesome work! Now on to my thoughts!

I would love to see the Metals chest condense more ore's! Kind of like how packagers work, were it condenses things that have a 3x3 recipe. That is how I do things now, with a couple dozen packagers and the Logistics pipes to go with it, but man would it be awesome to just pump it into the metals chest and extract the blocks!

We have the awesome electric trains (I use them moving things around my base) but they are kind of limited on travel distance unless you have IC2 installed, which is a bummer. So I was thinking about a power cart. No other mod needed, just stores the power type used by the train and could charge up when on powered rail. Then I started thinking far out of the box, like being able to add a solar panel as an upgrade, blah blah blah, I could go on for days, but I wont.

The last thought I wanted to toss out there was a new locomotive: Diesel/Diesel electric. I have all this Buildcraft oil around my base, and no use for it since I run solar power. AH HA! I need a diesel locomotive, then I could pollute the skies with it! Forecaster said something about it on IRC, but I thought I would toss it into my ideas list here.

Anyway, thanks for the great mod, it is tons of fun! 
-Opiboble

**Comment by CovertJaguar** [comment]
I rewrote the Metal's Chest a while back to support various "algorithms" simply and easily. I'm not a opposed to accepting new algorithms for compression, but they need to be performant and rock solid and continue to prefer Railcraft's Metal Items/Blocks.

https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/blocks/machine/beta/TileChestMetals.java#L42

Other energy storage carts are planned, and are quite high on the todo list.

Diesel Locomotives are also on the todo list, but I have a lot of infrastructure that I need to put in place for Fuel creation before I can even think about adding the Locomotive. The ChemLab for example, which is my current big project.

**Comment by Opiboble** [comment]
I know very little java/programming, but I see that there is a filter mentioned, is there any way to edit this in a config to add metals on my own? Is it something you could add as a config option?

The more carts/diesle/ChemLab sounds awesome! Cant wait to see it! Thanks for the great mod!

**Comment by CovertJaguar** [comment]
There is no config option no, its based on the Ore Dictionary tags. Which works great, but the problem is that I only support metals that have Railcraft equivalents because of the complexity of deciding what to output if Railcraft doesn't provide something.

**Comment by Opiboble** [comment]
AAah, okay, bummer. All well, I shall live with the packagers, thank you got the great mod CovertJaguar! Hoping for a pay raise soon so I can put some money in the jar for you : )
