### ISSUE TITLE
Quarried/Abyssal stone is unsmeltable with factory module disabled

### ISSUE THREAD

**Issue by PikadudeNo1** [CovertJaguar/Railcraft#541]
With the factory module disabled, a vanilla furnace cannot smelt quarried/abyssal stone. NEI shows that their cobblestone variants can be smelted, but as the cobblestone variants are unobtainable without the factory module (even a non-ST pickaxe yields the smooth variants), there is no way to get the Block variants.

**Comment by CovertJaguar** [comment]
Thanks for the report!
