### ISSUE TITLE
Void Crowbar lacks self-repair of typical Void Tools

### ISSUE THREAD

**Issue by mallrat208** [CovertJaguar/Railcraft#543]
Small one here...

All Void weapons and tools in Thaumcraft passively repair themselves at about a rate of 1 point of damage a second, the Void Crowbar does not. As a Void Item, should it have that particular trait or is it intended to not have it?

**Comment by liach** [comment]
Nice point. @Yopu Will you look into this one?

**Comment by Yopu** [comment]
Life's been busy. But I'll investigate.

**Comment by Yopu** [comment]
Looks like thaumcraft just does it manually via onUpdate()
