### ISSUE TITLE
Disabling the magic and/or void crowbar messes up Thaumcraft

### ISSUE THREAD

**Issue by doushio9967** [CovertJaguar/Railcraft#546]
MC will end up crashing with
http://pastebin.com/4JaZNnj7
when you scan certain things or when hungry nodes try to figure out the aspects on on some things they ate.
RC still end up adding (messed up) arcane crafting recipes for the crowbars when they are disabled, I guess.

**Comment by liach** [comment]
It seems that the recipe is not removed. A mess.
