### ISSUE TITLE
Throw some forge events when crowbar breaking blocks

### ISSUE THREAD

**Issue by liach** [CovertJaguar/Railcraft#547]
It seems that the breaking function of the crowbar doesn't call any event. Maybe call some would improve compatibility.

**Comment by CovertJaguar** [comment]
This was added to 1.7, but it still needs to be applied to 1.10. Unfortunately the two code bases have diverged to the point where this becomes difficult to do using git merge.

**Comment by liach** [comment]
I believe we should test with sponge before actually commiting that.

**Comment by liach** [comment]
@CovertJaguar I believe this is already handled in 1.7 and it should not happen in 1.10 (Sponge add event hooks in `setBlock` methods).
