### ISSUE TITLE
Bug: Filling Railcraft liquid-containers with water bottles does not return an empty bottle

### ISSUE THREAD

**Issue by MalkContent** [CovertJaguar/Railcraft#550]
This includes (maybe not exclusively) Steam Locomotives, Boilers and Hobbyist's Steamengines

**Comment by liach** [comment]
Actually if you put in ic2 cells, you get the same result. What a ..?

**Comment by CovertJaguar** [comment]
Many fluid containers are intended to be single use. Railcraft simply follows the standard that if the bottle wants to return something after being emptied, it needs to implement Item.getContainerStack().

**Comment by MalkContent** [comment]
fair enough
