### ISSUE TITLE
Request: allow track layers to run down plants (maybe with toggle inside its gui)

### ISSUE THREAD

**Issue by MalkContent** [CovertJaguar/Railcraft#551]
As title. Track Layers stopping because of flowers or saplings or pam's harvestcraft gardens in the way is rather annoying.
Please make it possible to allow track layers to break the blocks and continue.
Attached request: make the broken plant's drop their drops, too. I noticed that track layers can replace grass but it would never drop seeds.

**Comment by liach** [comment]
Dreaming. If you want this to be fixed, then you should ask Mojang to allow gravels to replace the flowers. :sweat_smile:

**Comment by MalkContent** [comment]
err >_> i politely but firmly disagree.
In any case, I asked in the forge channel how to detect plants. While there was ideas to detect plants specifically, the best idea that came out of this, that I think is to go by block hardness. Super low block hardness like the one of flowers and bushes and saplings feel natural to be run over by the track layer. But this also means that it can run over torches, and even better, redstone and possibly other frail player built things :D
It would feel natural for the whimsy stuff to be flattened by the track layer and I can imagine one or two careless players having some "oh no..." moments with it :)

**Comment by liach** [comment]
Then it's also an improvement for tunnel bores. Very good. :smiley:

**Comment by CovertJaguar** [comment]
I thought @Yopu fixed this already.

**Comment by Yopu** [comment]
[It was fixed by utilizing the existing functionality in the tunnel bore.](https://github.com/CovertJaguar/Railcraft/blob/2b29dde6878d5f038950f77e6e10c6a7c61a165c/src/main/java/mods/railcraft/common/carts/EntityCartTrackLayer.java#L81)

**Comment by Yopu** [comment]
[Valid replaceable blocks via the tunnel bore.](https://github.com/CovertJaguar/Railcraft/blob/2b29dde6878d5f038950f77e6e10c6a7c61a165c/src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java#L138)

**Comment by Yopu** [comment]
The block hardness idea would be a nice solution.
It might lead to some weird mod interactions though.

**Comment by Yopu** [comment]
@MalkContent could you put together a quick list of the blocks that were causing you issues and the mod they come from?

**Comment by MalkContent** [comment]
Minecraft: Flowers, Saplings
Pam's Harvest Craft: Gardens

Admittedly didn't really test all that much. Was playing around in creative super flat and harvest craft's gardens were still everywhere and cramped the track layers style. Only tested poppies and an oak sapling to be sure it isn't a problem with harvest craft.

**Comment by Yopu** [comment]
Yeah I was aware it wouldn't replace saplings.

**Comment by MalkContent** [comment]
I can try and grow the list, if you want to.

**Comment by Yopu** [comment]
Nah, I have a pretty good idea as to what it needs.

**Comment by MalkContent** [comment]
<3 :) am i gonna be able to let my track layers smush trough my pretty redstone?

**Comment by Yopu** [comment]
At the moment it's checking for IPlantable and IShearable. Redstone is a possibility. The hardness idea seems too broad for my taste. @CovertJaguar thoughts?

**Comment by Vexatos** [comment]
@Yopu `Block.isReplacable()` (not sure how exactly the method is called)

**Comment by Yopu** [comment]
Aha, I was hoping there would be a simpler method.

**Comment by Vexatos** [comment]
However, IPlantable and IShearable need to be handled separately as most of those return false in that method.

**Comment by Yopu** [comment]
Right, however it would cover some of the other cases.

**Comment by MalkContent** [comment]
I would dislike the blocks simply being replaced. Breaking them and dropping their .. drops would seem fairer.

**Comment by Yopu** [comment]
Well then it's likely good that I'm already fixing that. :P

**Comment by Yopu** [comment]
Fixed https://github.com/CovertJaguar/Railcraft/commit/0e2de087beb0b1df6e9cf4874e6e5d65fdc0b107

**Comment by Yopu** [comment]
It should fix most of the cases you listed. It's worth noting that it won't replace blocks that are planted in tilled soil since that isn't a valid block for rails to be placed on.

**Comment by MalkContent** [comment]
awesome :)
