### ISSUE TITLE
Black Screen on Mac?

### ISSUE THREAD

**Issue by xaleb** [CovertJaguar/Railcraft#553]
http://pastebin.com/Jb3NVhFV Here is the log, my friends are having trouble running this collection of mods all together on their macs..and the issue seems to be when railcraft is included. But all Windows and Linux operating system are running them all smoothly and efficiently. They are getting black screens when clicking single or multiplayer, and the game is just hanging up. The only out is to force quit. Suggestions? Sorry for double post..Lag

**Comment by liach** [comment]
Maybe that's a conflict between Railcraft and one of those coremods. Could you try one by one?

**Comment by liach** [comment]
But I didn't see anything wrong on the log...

**Comment by xaleb** [comment]
If it is a conflict, I have no way of knowing, because it works on all my server's members that have windows/linux operating systems..just not the mac users. It would have to be done at a later date, and they're not too happy, because I already spent time uninstalling and reinstalling stuff and such. Is there a mod conflict checker or something? Or better yet, a way to make mac run Java better?..lol clairfy core mods, if that will lower the work load.

**Comment by CovertJaguar** [comment]
Sorry, the only solution is to have someone who is experiencing the problem debug it by removing/adding mods until they can identify the specific combination of mods that causes it. That is of course assuming that a clean Railcraft install with NO other mods works fine.

**Comment by xaleb** [comment]
I'm installing a Mac OS onto virtual box and testing all my mods.

**Comment by xaleb** [comment]
Alright if this is still being watched, I have possibly deduced the mods down to thaumcraft latest version, thaumic tinkerer latest version and railcraft..Any conflicts on Mac in particular, or I suppose you wouldn't know.

**Comment by xaleb** [comment]
Update: It is a failure. I bet it has something to do with the way Mac interprets Java. If you can supply various code fixes, I can have them tested if you don't have a Mac os. It'd be helpful to a handful of players on my server.

**Comment by liach** [comment]
Maybe this is related to Java6 support?

**Comment by xaleb** [comment]
In which case, a possible solution is to find a way to use the latest Java.

**Comment by xaleb** [comment]
For now, I'm disabling the mod, is there anything that could devastate my game by removing it? Nothing from the mod was touched all that much. My friend said something about bed rock pockets, but I can just call a global purge of bedrock with admin controls that isn't suppose to be there..

**Comment by CovertJaguar** [comment]
While we now have more information that we did before, it is still not sufficient to isolate the problem to a specific line of code or even which of the three mods you mentioned are causing it.
