### ISSUE TITLE
Signals occasionally disconnect from each other

### ISSUE THREAD

**Issue by Spauldo** [CovertJaguar/Railcraft#554]
On a server running 9.5.0.0, the signal blocks occasionally "undefine" themselves.  Most of the time they're fine, but I'll log into the server about twice a week and find one that's blinking red with a train waiting at it.  It's ususally the same signal, placed near a villiage (with witchery hobgoblins) - it contains a 1 block rise, a liquid loader, and an item loader (both with train locking tracks).  The other one that gives me trouble has a rise, but no loaders or special tracks, and is in the middle of a roofed forest with no structures around.

Both areas (and almost all my signal blocks) are defined between a block signal two blocks above the track (i.e. you can walk under it) and a signal block relay placed beside the track and one block down (for aesthetic reasons).  On top of the relay is a signal receiver box tuned to the next block signal.  Neither area is chunkloaded, but my signals are on chunk boundaries and the trains have anchor carts (with anchor fuel disabled - it's a private server, chunkloading isn't a problem).  The signal receiver boxes stay tuned.

There's no error messages in the log that I can find that relate to Railcraft.

The server's had a lot of updates and had at least two versions of Railcraft.  The signal that's been doing it lately, however, was placed after I updated to 9.5.0.0.  It's not caused by server restarts - I rarely restart the server.  My server's mostly tech mods - think a cut down version of the direwolf20 pack.

![railcraft_block](https://cloud.githubusercontent.com/assets/7151836/6765847/511eee8c-cfbe-11e4-9472-15f5b9d35bf8.png)
Attached is a picture of the block in question.  The arrows point to the block signal and the relay that define the block (the relay is underneath a signal receiver box).

**Comment by CovertJaguar** [comment]
There is a debug setting in the config that you can turn on that will print information to the log about when signal pairing fail. 

"tweaks.blocks.signals.printDebug"

**Comment by CovertJaguar** [comment]
This should be fixed by 1bd1246664aeba29b56d58f451716de269ed5d80 and 1bd1246664aeba29b56d58f451716de269ed5d80
