### ISSUE TITLE
Railcraft not recognising modded carts as inventories

### ISSUE THREAD

**Issue by ganymedes01** [CovertJaguar/Railcraft#556]
I got a report on my mod IronChestMinecarts (source here: https://github.com/ganymedes01/IronChestMinecarts) saying that some Railcraft features (tunnel bore, undercutter, relayer, etc) aren't recognising my carts as inventories.
My minecart classes all extend EntityMinecartChest, because I thought that would be enough to ensure compatibility. Am I missing something?

**Comment by octarine-noise** [comment]
You'll need to implement **mods.railcraft.api.carts.IItemTransfer** from the Railcraft API.

**Comment by ganymedes01** [comment]
Ah okay.
Thanks for letting me know :)

**Comment by CovertJaguar** [comment]
I should really kill that API...
