### ISSUE TITLE
Request: Rolling machine do not constantly consumes energy or make it on/off on redstone

### ISSUE THREAD

**Issue by InsKill** [CovertJaguar/Railcraft#558]
Subject. I don't know why rolling machine need to consume energy even it not make a job.

Sorry for bad  english.

**Comment by Opiboble** [comment]
What version are you using? I am pretty sure this is not how they work in 9.5

**Comment by LizzyTrickster** [comment]
IIRC RailCraft machines have a (small) idle power usage. When they're doing work they consume a lot more power. Not sure what you're refering to by the redstone stuff

**Comment by Amelia-** [comment]
I remember them using power when idle when they still used MJ as a power source a while ago but all machines I can think of that used MJ did that.
Since they use RF for power I have not noticed any power use when the machines are idle.

Are you using an old version?

**Comment by InsKill** [comment]
The Newest One, I think: Railcraft_1.7.10-9.5.0.0.jar

**Comment by Amelia-** [comment]
How much energy are they consuming for you?
I just cut an idle rolling machine with full energy from its energy source but its energy has not gone down at all over the last like 10 minutes. It just stays at 5000 RF so from what I can tell it is not consuming any energy.

Are you sure it is the railcraft machines that are using the energy?

**Comment by CovertJaguar** [comment]
They do not. That was always a function of the MJ Power API, not the machine.
