### ISSUE TITLE
[Enhancement] Multicolored tuning particles

### ISSUE THREAD

**Issue by Forecaster** [CovertJaguar/Railcraft#560]
When you're building a larger signal system such as within a station the Trackman's Goggles quickly become useless due to the fact that all the particle trails look the same.

It would be a lot more useful if there were different colors. Then it'd be a lot easier to follow a trail from one end to the other even if it happens to be close to other trails.

Alternatively/additionally there could also be different particles. This may be more colorblind friendly as well as additionally enhance ones ability to distinguish between the trails.

**Comment by Yopu** [comment]
This appears to have been implemented in 9.7.0.0
