### ISSUE TITLE
server crash when breaking rideable cart on top of player detector

### ISSUE THREAD

**Issue by robotbrain** [CovertJaguar/Railcraft#562]
WTTS
http://puu.sh/gU6qR/6829050346.log < logfile
http://puu.sh/gU6H0/7e3f7bf1cc.txt < crash report

**Comment by liach** [comment]
Could you upload the stuff in the routing table... It may help I think. As I could see, killing a cart make a "null" in the train and caused NPE?

**Comment by robotbrain** [comment]
was
NOT
Dest=null

**Comment by liach** [comment]
Nope, on both log and crash-report, it shows that you used AND?
And it was checking whether the cart was ridden...

**Comment by robotbrain** [comment]
hmm
I thought I changed it, before that it was
AND
NOT
Dest=null
Ridden=true
