### ISSUE TITLE
Sugestion to helping to avoid the Thaumcraft "too many tabs" issue

### ISSUE THREAD

**Issue by Nocty201** [CovertJaguar/Railcraft#565]
The TL,DR; is as follows:

TC4 has limited tab slots, and adding too many mods for it will overfill them making some inaccessable. I have suggested to Azanor that perhaps he could allow some mods with fewer researches to add themselves to the vanilla pages via a config option to free up the tab slot.

I have posted this on the Thaumcraft Github as well here -> https://github.com/Azanor/thaumcraft/issues/1654#issuecomment-87992984

Given you have two research items in the book, perhaps you could ask Azanor for permission to move them to the Artifice page as a config option?

**Comment by liach** [comment]
Oh, Azanor said that other mods shouldn't put their stuff in Thaumcraft's tab. So you see, Railcraft does have one tab, only one. New stuff related to Tc in Rc will be put in that tab.

**Comment by Nocty201** [comment]
Yes, that is pretty much the core of the problem.

Each mod has one tab that they put stuff into.

Railcraft has two items in the one tab.

Add enough mods, and there is no space for tabs anymore - the extras overlap and prevent you clicking other tabs.

Azanor has mentioned he wishes to change how the Thaumonomicon works, to prevent this happening.

As an interim "fix", I have suggested he allow some mods to not need their own tab. Railcraft and AOBD spring to mind as likely candidates because they have so little in their tabs. I have posted here and on the AOBD page with links to my suggestion so (hopefully) the mod authors will consider this as a temporary thing.

Cheers :)

**Comment by Adaptivity** [comment]
There is no API function for that. But you can do it if have [Minetweaker and Modtweaker](https://www.reddit.com/r/feedthebeast/comments/2xwc6p/too_many_thaumcraft_addons_nah_too_much_warp_maybe/cp4bl41) Can be closed I guess.

**Comment by Dream-Master** [comment]
http://minecraft.curseforge.com/projects/notenoughthaumcrafttabs

**Comment by liach** [comment]
Well, I don't think Railcraft is going to make change on other mods' existing stuff. So closing.
