### ISSUE TITLE
Anchors not following forgeChunkLoading.cfg

### ISSUE THREAD

**Issue by bookerthegeek** [CovertJaguar/Railcraft#569]
Tested in single player with latest:
* Railcraft
* Forge
* ChickenChunks and associated code files

Found that railcraft anchors do not follow the "I:playerTicketCount" found in the "forgeChunkLoading.cfg".

We are attempting to limit each player to only be able to load 9 chunks. As it is we are not able to enforce that limit with anchors and as such have had to, sadly, disable the ChunkLoading Module from 'modules.cfg'

How we tested:
* Set "I:playerTicketCount=**0**" in "forgeChunkLoading.cfg"
* Created new world with only the mods listed above.
* Travel 125 chunks to leave spawn chunks
* Place an enderchest with a hopper going into it. FIll the hopper with items of your choice.
* Travel 125 chunks in any direction
* Open ender pouch linked to chest and watch items fill the chest

Thank you for taking the time to read this and thank you for the wonderful mod.

**Comment by liach** [comment]
How about w/o chickenchunks? CodeChickenCore is a coremod though.

**Comment by bookerthegeek** [comment]
The question would be in how you would like me to test.

My thought is, one with an anchore and one without.
1. Each setup would have a furnace with stack of fuel and hoppers feeding
and removing cobblestone.
2. Afk 125 chunks away for 15 min
3. See how much is smelted in each

If this would work for you I'll test tonight.

**Comment by bookerthegeek** [comment]
Same result. The chunk wit the anchor smelted the coal even with the player limit set to zero

**Comment by CovertJaguar** [comment]
Player Tickets are only used by Personal Anchors.

**Comment by bookerthegeek** [comment]
Sorry if my post was a little unclear.
1. First test was with chicken chunks.
2. Second test was on a clean install with only forge and railcraft were installed.
3. Personal anchors were the one used for the testing. 

Once again sorry if that information was not clearly defined in my previous posts.

**Comment by CovertJaguar** [comment]
Well I'd talk to @cpw about that, I just ask Forge for the Ticket. Its up to Forge to decide whether to give me one.

**Comment by bookerthegeek** [comment]
Thank you for taking another look.
