### ISSUE TITLE
Anchors fuel modification

### ISSUE THREAD

**Issue by Powerpin** [CovertJaguar/Railcraft#570]
I have the lastest railcraft version and i am trying to get the industrial credit from IC2 be the fuel for the anchors. Ive tried maybe 20 different ways to change it and in all case, the server was crashing on startup.

* the number of hours that an item will power a Personal Anchor or Personal Anchor Cart
* this is an approximation only, actual duration is affected by number of chunks loaded and tick rate
* if the list is empty, World Anchors will not require fuel, default = 12
* Entry Format: <modid>:<itemname>#<metadata>=<value>
* Example: personal.fuel= minecraft:ender_pearl=12, minecraft:coal#0=4

S:personal.fuel= minecraft:ender_pearl=1

Its supposed to be: S:personal.fuel= IC2:ITEMCOIN=1
And like i said i had tried alot more ways to try to make it work.

Crash report: http://pastebin.com/B0LKEEHn
This crash report is ONE example of many i got, so don't bother with ic2:coin#0

**Comment by Powerpin** [comment]
No answer??

**Comment by liach** [comment]
Please wait. CJ is always so busy... And it seems some other people who met this crash haven't got a reply yet.

**Comment by CovertJaguar** [comment]
The following should work.
```
S:personal.fuel= IC2:coin=1
```

**Comment by liach** [comment]
Um.. Maybe something to prevent that crash?

**Comment by CovertJaguar** [comment]
Why? If you are messing with configs, crashes are more informative. This only happens if you get it wrong.
