### ISSUE TITLE
Compatiblity

### ISSUE THREAD

**Issue by zHawky** [CovertJaguar/Railcraft#572]
Hi! Do you planned for adding compatiblity in Mekanism and Metallurgy ingots?

**Comment by CovertJaguar** [comment]
No? I don't understand the question.

**Comment by liach** [comment]
Yep CJ doesn't play mekanism... You can or someone else could make an addon.

**Comment by zHawky** [comment]
Well, i mean make railcraft rails from these mods>ingots, but anyway i got the answer, close request.
