### ISSUE TITLE
Fluid Crash

### ISSUE THREAD

**Issue by DPxKnightxZero** [CovertJaguar/Railcraft#575]
One of the players broke a fuel tank and they quickly crashed client side with this error.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/8/15 8:39 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraftforge.fluids.FluidRegistry.isFluidRegistered(FluidRegistry.java:97)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:30)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:58)
	at mods.railcraft.common.fluids.TankManager.processGuiUpdate(TankManager.java:192)
	at mods.railcraft.common.gui.containers.ContainerEngineSteamHobby.func_75137_b(ContainerEngineSteamHobby.java:110)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidRegistry.isFluidRegistered(FluidRegistry.java:97)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:30)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:58)
	at mods.railcraft.common.fluids.TankManager.processGuiUpdate(TankManager.java:192)
	at mods.railcraft.common.gui.containers.ContainerEngineSteamHobby.func_75137_b(ContainerEngineSteamHobby.java:110)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['GamerGirl9219'/12984, l='MpServer', x=43.26, y=74.62, z=220.89]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 05 - Highlands, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-64,64,59), Chunk: (at 0,4,11 in -4,3; contains blocks -64,0,48 to -49,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 36638 game time, 36638 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 191 total; [EntityItem['item.tile.waterKelpGiantGRN'/16897, l='MpServer', x=86.03, y=51.13, z=271.03], EntityItem['item.tile.waterKelpGiantGRN'/16899, l='MpServer', x=85.59, y=51.13, z=269.41], EntityItem['item.tile.waterKelpGiantGRN'/16904, l='MpServer', x=85.19, y=52.13, z=267.94], EntitySquid['Squid'/18441, l='MpServer', x=86.31, y=58.22, z=255.28], EntitySquid['Squid'/18443, l='MpServer', x=87.66, y=57.91, z=252.31], EntitySquid['Squid'/18445, l='MpServer', x=89.72, y=55.34, z=258.88], EntityItem['item.tile.waterKelpGiantGRN'/16909, l='MpServer', x=84.38, y=51.13, z=269.19], EntityItem['item.tile.waterKelpGiantGRN'/16910, l='MpServer', x=93.97, y=54.13, z=261.38], EntityItem['item.item.calamarcru'/18958, l='MpServer', x=99.81, y=60.13, z=244.91], EntityTrickster['Trickster'/21006, l='MpServer', x=7.30, y=10.00, z=283.74], EntitySquid['Squid'/18447, l='MpServer', x=91.50, y=60.31, z=243.28], EntityTrickster['Trickster'/21007, l='MpServer', x=2.52, y=10.00, z=290.51], EntityItem['item.item.dyePowder.black'/18960, l='MpServer', x=99.63, y=60.13, z=245.03], EntityTrickster['Trickster'/21008, l='MpServer', x=5.27, y=10.00, z=288.47], EntityItem['item.tile.waterKelpGiantGRN'/16913, l='MpServer', x=92.53, y=54.13, z=261.09], EntityTrickster['Trickster'/21009, l='MpServer', x=2.50, y=10.00, z=287.50], GCEntityClientPlayerMP['GamerGirl9219'/12984, l='MpServer', x=43.26, y=74.62, z=220.89], EntityItem['item.tile.waterKelpGiantGRN'/16917, l='MpServer', x=70.22, y=48.13, z=277.78], EntityItem['item.tile.dirt.default'/20502, l='MpServer', x=52.47, y=77.13, z=246.31], EntityItem['item.tile.mushroom'/15382, l='MpServer', x=-15.13, y=11.13, z=276.13], EntityItem['item.tile.mushroom'/15383, l='MpServer', x=-17.66, y=11.13, z=278.81], EntityItem['item.item.redstone'/15384, l='MpServer', x=-18.88, y=12.13, z=280.72], EntityItem['item.tile.waterKelpGiantGRN'/16922, l='MpServer', x=70.19, y=48.13, z=276.75], EntitySkeleton['Skeleton'/21025, l='MpServer', x=3.50, y=19.00, z=204.50], EntityItem['item.tile.extrabiomes.waterplant.eelgrass'/16932, l='MpServer', x=49.19, y=60.13, z=284.13], EntityFacelessRunner['Faceless Runner'/20524, l='MpServer', x=17.88, y=30.00, z=288.88], EntityFacelessRunner['Faceless Runner'/20525, l='MpServer', x=30.81, y=30.00, z=284.69], EntityCaveSpider['Cave Spider'/1582, l='MpServer', x=-26.76, y=-0.02, z=-5.30], EntityFacelessRunner['Faceless Runner'/20526, l='MpServer', x=12.41, y=30.00, z=289.97], EntityBat['Bat'/19001, l='MpServer', x=77.88, y=19.10, z=193.38], EntityGhost['Ghost'/20542, l='MpServer', x=74.94, y=14.00, z=230.50], EntityGhost['Ghost'/20544, l='MpServer', x=73.28, y=17.00, z=237.16], EntityBat['Bat'/21064, l='MpServer', x=84.07, y=43.36, z=247.83], EntityBat['Bat'/21066, l='MpServer', x=90.86, y=42.92, z=251.49], EntityPainting['Painting'/14687, l='MpServer', x=8.06, y=71.00, z=207.00], EntityItem['item.tile.waterKelpGiantGRN'/16972, l='MpServer', x=104.81, y=54.13, z=260.78], EntityPainting['Painting'/14688, l='MpServer', x=8.06, y=71.00, z=207.00], EntityCreeper['Creeper'/20558, l='MpServer', x=88.50, y=43.00, z=251.50], EntityCreeper['Creeper'/20560, l='MpServer', x=87.50, y=43.00, z=250.50], EntitySquid['Squid'/18529, l='MpServer', x=93.13, y=58.00, z=236.88], EntityClown['Clown'/20065, l='MpServer', x=93.50, y=18.00, z=244.50], EntitySquid['Squid'/18530, l='MpServer', x=89.50, y=59.38, z=236.50], EntityLinger['Linger'/21101, l='MpServer', x=72.50, y=58.00, z=200.50], EntityGaiaMimic['Mimic'/20080, l='MpServer', x=105.50, y=22.00, z=207.50], EntityGaiaMimic['Mimic'/20081, l='MpServer', x=105.50, y=21.00, z=202.50], EntityFrostweaver['Frostweaver'/21107, l='MpServer', x=12.48, y=30.00, z=272.48], EntityItem['item.tile.waterKelpGiantYEL'/17527, l='MpServer', x=67.56, y=47.13, z=286.03], EntityItem['item.tile.shrubButterfly'/19576, l='MpServer', x=14.06, y=74.13, z=212.78], EntityItem['item.tile.shrubButterfly'/16507, l='MpServer', x=8.66, y=72.13, z=212.19], EntityItem['item.item.calamarcru'/18043, l='MpServer', x=4.75, y=71.13, z=168.19], EntityItem['item.tile.waterKelpGiantYEL'/17532, l='MpServer', x=67.38, y=47.13, z=286.94], EntityItem['item.item.dyePowder.black'/18044, l='MpServer', x=3.41, y=71.13, z=168.53], EntityZombie['Zombie'/1661, l='MpServer', x=-27.58, y=-26.62, z=28.01], EntityItem['item.item.dyePowder.black'/18048, l='MpServer', x=-3.94, y=72.13, z=168.25], EntityItem['item.tile.torch'/14980, l='MpServer', x=25.13, y=20.13, z=249.25], EntitySquid['Squid'/18567, l='MpServer', x=88.81, y=59.81, z=249.84], EntityVillager['Villager'/148, l='MpServer', x=15.50, y=74.00, z=190.72], EntityVillager['Villager'/149, l='MpServer', x=23.50, y=72.00, z=191.50], EntityItem['item.item.HeartStone'/150, l='MpServer', x=23.16, y=72.13, z=190.03], EntityItem['item.tile.flowers2.minersdelight'/16540, l='MpServer', x=-21.75, y=23.13, z=200.72], EntitySquid['Squid'/18596, l='MpServer', x=90.97, y=60.31, z=249.03], EntityBat['Bat'/17575, l='MpServer', x=10.26, y=50.00, z=230.71], EntityZombie['Zombie'/5346, l='MpServer', x=-19.82, y=-44.62, z=41.54], EntityItem['item.item.calamarcru'/18660, l='MpServer', x=85.53, y=58.13, z=251.38], EntityItem['item.item.dyePowder.black'/18661, l='MpServer', x=84.66, y=58.13, z=252.72], EntityItem['item.item.calamarcru'/18664, l='MpServer', x=85.19, y=63.13, z=241.28], EntityCartChest['entity.MinecartChest.name'/17640, l='MpServer', x=118.50, y=28.50, z=155.50], EntityItem['item.tile.gravel'/16617, l='MpServer', x=6.41, y=20.13, z=238.38], EntityItem['item.tile.gravel'/16618, l='MpServer', x=9.63, y=20.13, z=235.63], EntityItem['item.item.dyePowder.black'/18666, l='MpServer', x=85.16, y=63.13, z=249.50], EntityItem['item.tile.gravel'/16623, l='MpServer', x=6.41, y=20.13, z=233.44], EntityItem['item.tile.gravel'/16624, l='MpServer', x=6.13, y=18.13, z=239.63], EntityItem['item.tile.gravel'/16625, l='MpServer', x=7.56, y=18.13, z=236.13], EntityZombie['Zombie'/4855, l='MpServer', x=-30.49, y=-55.62, z=9.30], EntitySkeleton['Skeleton'/4856, l='MpServer', x=-28.49, y=-55.62, z=9.30], EntityItem['item.item.calamarcru'/18681, l='MpServer', x=89.84, y=63.13, z=232.16], EntityItem['item.item.dyePowder.black'/18683, l='MpServer', x=91.22, y=63.13, z=235.13], EntityBat['Bat'/19216, l='MpServer', x=40.95, y=62.97, z=155.51], EntitySkeleton['Skeleton'/19745, l='MpServer', x=21.50, y=40.00, z=271.50], EntitySkeleton['Skeleton'/19746, l='MpServer', x=30.50, y=40.00, z=269.50], EntitySkeleton['Skeleton'/19747, l='MpServer', x=26.50, y=40.00, z=271.50], EntitySquid['Squid'/18762, l='MpServer', x=80.47, y=57.31, z=255.50], EntityZombie['Zombie'/19282, l='MpServer', x=103.50, y=54.00, z=166.50], EntityItem['item.item.calamarcru'/18772, l='MpServer', x=90.91, y=59.13, z=237.03], EntityItem['item.item.dyePowder.black'/18773, l='MpServer', x=93.16, y=57.13, z=234.94], EntityCartChest['entity.MinecartChest.name'/15192, l='MpServer', x=103.50, y=26.50, z=186.50], EntitySquid['Squid'/18776, l='MpServer', x=91.09, y=57.38, z=250.59], EntityItem['item.item.string'/15193, l='MpServer', x=96.38, y=22.13, z=188.16], EntitySquid['Squid'/18777, l='MpServer', x=92.91, y=57.34, z=256.72], EntitySquid['Squid'/18779, l='MpServer', x=88.66, y=54.00, z=260.88], EntityItem['item.item.calamarcru'/18780, l='MpServer', x=92.28, y=59.13, z=242.59], EntityVillager['Villager'/14685, l='MpServer', x=21.72, y=72.00, z=194.50], EntityVillager['Villager'/14686, l='MpServer', x=24.94, y=72.00, z=191.44], EntityItem['item.item.dyePowder.black'/18782, l='MpServer', x=92.38, y=59.13, z=242.94], EntityPainting['Painting'/14687, l='MpServer', x=8.06, y=71.00, z=207.00], EntityPainting['Painting'/14688, l='MpServer', x=8.06, y=71.00, z=207.00], EntityVillager['Villager'/14689, l='MpServer', x=4.86, y=69.00, z=206.16], EntityVillager['Villager'/14690, l='MpServer', x=5.82, y=69.57, z=206.52], EntityVillager['Villager'/14691, l='MpServer', x=15.50, y=69.00, z=208.25], EntityCartChest['entity.MinecartChest.name'/15203, l='MpServer', x=100.50, y=28.50, z=147.50], EntityVillager['Villager'/14692, l='MpServer', x=16.34, y=76.00, z=200.34], EntityItem['item.tile.rail'/15204, l='MpServer', x=96.84, y=30.13, z=213.75], EntityVillager['Villager'/14693, l='MpServer', x=12.50, y=75.50, z=207.69], EntityItem['item.tile.rail'/15205, l='MpServer', x=105.38, y=30.13, z=214.09], EntityGoron['Goron'/14694, l='MpServer', x=6.94, y=75.00, z=202.95], EntityVillager['Villager'/14695, l='MpServer', x=21.54, y=73.00, z=200.72], EntityVillager['Villager'/14699, l='MpServer', x=19.28, y=71.00, z=220.50], EntityVillager['Villager'/14700, l='MpServer', x=14.78, y=71.00, z=219.56], EntityBat['Bat'/19820, l='MpServer', x=-4.25, y=55.10, z=235.50], EntityVillager['Villager'/14701, l='MpServer', x=24.50, y=71.00, z=221.50], EntityVillager['Villager'/14702, l='MpServer', x=24.50, y=71.00, z=222.50], EntityVillager['Villager'/14703, l='MpServer', x=12.83, y=73.00, z=217.50], EntityVillager['Villager'/14704, l='MpServer', x=33.60, y=69.00, z=213.38], EntityZombie['Zombie'/4464, l='MpServer', x=-33.01, y=-54.62, z=6.39], EntityVillager['Villager'/14705, l='MpServer', x=21.65, y=73.00, z=216.45], EntityVillager['Villager'/14706, l='MpServer', x=28.43, y=72.00, z=202.24], EntityItem['item.item.emerald'/14707, l='MpServer', x=13.38, y=30.13, z=239.22], EntityItem['item.item.zss.potion_blue'/14708, l='MpServer', x=12.13, y=30.13, z=239.38], EntityItem['item.item.expBottle'/14709, l='MpServer', x=11.13, y=30.13, z=239.13], EntityItem['item.item.apple'/14710, l='MpServer', x=13.31, y=30.13, z=237.84], EntityItem['item.item.zss.sword_broken'/14711, l='MpServer', x=11.13, y=30.13, z=238.31], EntityItem['item.item.string'/14717, l='MpServer', x=6.13, y=18.13, z=239.19], EntityItem['item.item.string'/14718, l='MpServer', x=7.88, y=18.13, z=236.13], EntityItem['item.item.arrow'/14719, l='MpServer', x=13.13, y=76.13, z=224.09], EntityItem['item.item.Corpse'/14720, l='MpServer', x=13.75, y=72.13, z=239.34], EntityBat['Bat'/19328, l='MpServer', x=96.50, y=48.10, z=210.50], GCEntityOtherPlayerMP['P3rf3ct_Zer0'/1565, l='MpServer', x=-71.16, y=104.91, z=2.66], EntityBat['Bat'/20356, l='MpServer', x=21.51, y=31.67, z=239.47], EntityBat['Bat'/20357, l='MpServer', x=21.31, y=30.00, z=244.90], EntityBat['Bat'/20358, l='MpServer', x=15.57, y=31.02, z=268.51], EntityItem['item.item.zss.potion_red'/14728, l='MpServer', x=66.13, y=33.13, z=159.19], EntitySkeleton['Skeleton'/3465, l='MpServer', x=-18.49, y=-28.62, z=8.30], EntityItem['item.tile.gravel'/16779, l='MpServer', x=-8.59, y=20.13, z=252.63], EntityCartChest['entity.MinecartChest.name'/14732, l='MpServer', x=66.50, y=18.50, z=191.50], EntityItem['item.item.string'/14734, l='MpServer', x=2.41, y=18.13, z=240.34], EntityItem['item.item.emerald'/14735, l='MpServer', x=10.13, y=50.13, z=251.94], EntityItem['item.item.zss.heart'/14736, l='MpServer', x=14.88, y=50.13, z=255.19], EntityItem['item.tile.GraveStone.Gravestone'/14737, l='MpServer', x=16.59, y=72.13, z=238.53], EntityItem['item.tile.mushroom'/14739, l='MpServer', x=-8.13, y=69.13, z=244.69], EntityItem['item.tile.rail'/14740, l='MpServer', x=-2.13, y=18.13, z=237.88], EntityBat['Bat'/19861, l='MpServer', x=-5.40, y=30.48, z=235.19], EntityItem['item.tile.rail'/14741, l='MpServer', x=-2.94, y=18.13, z=233.13], EntityItem['item.tile.rail'/14742, l='MpServer', x=-4.88, y=18.13, z=233.16], EntityItem['item.tile.rail'/14743, l='MpServer', x=-4.88, y=18.13, z=228.75], EntityItem['item.item.expBottle'/14744, l='MpServer', x=-0.22, y=20.13, z=231.72], EntityItem['item.item.zss.bomb.standard'/14745, l='MpServer', x=-3.25, y=18.13, z=233.13], EntityItem['item.item.bread'/14746, l='MpServer', x=-2.13, y=18.13, z=231.13], EntityItem['item.item.zss.bomb.standard'/14747, l='MpServer', x=-2.75, y=18.13, z=231.13], EntityItem['item.item.saddle'/14748, l='MpServer', x=-2.28, y=18.13, z=231.13], EntityItem['item.item.zss.sword_kokiri'/14749, l='MpServer', x=-1.56, y=20.13, z=231.13], EntityItem['item.item.zss.bomb.standard'/14750, l='MpServer', x=-2.34, y=20.13, z=233.41], EntityItem['item.item.ingotIron'/14751, l='MpServer', x=-3.41, y=19.13, z=230.53], EntityItem['item.item.zss.arrow_ice'/14752, l='MpServer', x=-2.13, y=18.13, z=231.13], EntityItem['item.item.string'/15265, l='MpServer', x=27.16, y=19.13, z=265.28], EntityItem['item.tile.shrubButterfly'/19361, l='MpServer', x=11.16, y=73.13, z=213.19], EntityItem['item.item.zss.heartpiece'/14753, l='MpServer', x=-2.19, y=18.13, z=231.13], EntityItem['item.item.emerald'/15779, l='MpServer', x=29.88, y=24.13, z=277.13], EntityCartChest['entity.MinecartChest.name'/14755, l='MpServer', x=-16.50, y=20.34, z=247.50], EntityItem['item.item.zss.deku_nut'/15780, l='MpServer', x=30.69, y=20.13, z=283.94], EntityItem['item.item.emerald'/14756, l='MpServer', x=-17.13, y=20.13, z=244.81], EntityItem['item.tile.notGate'/15781, l='MpServer', x=26.88, y=16.13, z=279.88], EntityBlackUrsa['Black Ursa'/18342, l='MpServer', x=-21.50, y=20.00, z=225.50], EntityItem['item.item.apple'/14758, l='MpServer', x=-21.88, y=25.13, z=249.75], EntityItem['item.item.seeds_pumpkin'/14759, l='MpServer', x=-21.88, y=20.13, z=250.38], EntityItem['item.item.emptyMap'/14760, l='MpServer', x=-21.88, y=20.13, z=248.56], EntityItem['item.item.zss.shield_8bit_small'/14761, l='MpServer', x=-21.88, y=27.13, z=247.78], EntityItem['item.item.zss.sword_kokiri'/14762, l='MpServer', x=-21.88, y=25.13, z=249.97], EntityItem['item.item.arrow'/14763, l='MpServer', x=-21.88, y=25.13, z=249.88], EntityItem['item.tile.waterKelpGiantGRN'/15788, l='MpServer', x=78.53, y=50.13, z=268.66], EntityItem['item.item.ingotGold'/14764, l='MpServer', x=-20.91, y=20.13, z=250.88], EntityItem['item.item.zss.arrow_light'/14765, l='MpServer', x=-21.56, y=25.13, z=249.94], EntityItem['item.tile.waterKelpGiantGRN'/15790, l='MpServer', x=76.47, y=50.13, z=268.44], EntityItem['item.item.zss.arrow_bomb'/14766, l='MpServer', x=-21.63, y=20.13, z=248.13], EntityItem['item.tile.waterKelpGiantGRN'/15795, l='MpServer', x=78.75, y=51.13, z=268.03], EntityItem['item.tile.extrabiomes.waterplant.eelgrass'/14772, l='MpServer', x=95.19, y=60.13, z=239.88], EntitySquid['Squid'/18868, l='MpServer', x=99.44, y=60.19, z=245.97], EntityItem['item.tile.waterKelpGiantGRN'/15797, l='MpServer', x=76.63, y=51.13, z=266.63], EntityZombie['Zombie'/1462, l='MpServer', x=-10.46, y=-22.62, z=30.86], EntityItem['item.tile.waterKelpGiantGRN'/15798, l='MpServer', x=77.16, y=50.13, z=267.44], EntityItem['item.tile.waterKelpGiantGRN'/15803, l='MpServer', x=77.38, y=50.13, z=270.03], EntityItem['item.item.zss.heart'/15804, l='MpServer', x=11.13, y=35.13, z=276.88], EntityItem['item.tile.notGate'/15805, l='MpServer', x=13.06, y=33.13, z=283.81], EntitySkeleton['Skeleton'/3534, l='MpServer', x=-31.45, y=-28.62, z=-0.33], EntityItem['item.tile.notGate'/15321, l='MpServer', x=33.66, y=21.13, z=240.75], EntityItem['item.tile.notGate'/15322, l='MpServer', x=40.34, y=19.13, z=241.88], EntityItem['item.tile.notGate'/15323, l='MpServer', x=42.97, y=19.13, z=240.09], EntityItem['item.tile.notGate'/15324, l='MpServer', x=42.13, y=19.13, z=243.13], EntityItem['item.tile.notGate'/15325, l='MpServer', x=44.63, y=23.13, z=241.13], EntityShambler['Shambler'/1009, l='MpServer', x=3.50, y=-806.73, z=8.50], EntityItem['item.item.calamarcru'/16380, l='MpServer', x=3.09, y=71.13, z=180.72], EntityItem['item.item.dyePowder.black'/16381, l='MpServer', x=-3.53, y=71.13, z=182.66]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 668082848 bytes (637 MB) / 1306705920 bytes (1246 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used

**Comment by liach** [comment]
Um...Any mod list? Or try w/o some other mods?

**Comment by DPxKnightxZero** [comment]
Can you explain what your saying I don't have a clue what your saying ... I think your saying forge is the cause. I am using forge 10.13.3.1358

**Comment by CovertJaguar** [comment]
This crash is in Forge code with a generic error message. I don't think its Railcraft fault.
