### ISSUE TITLE
Railcraft is wrongly shipping IC2 API

### ISSUE THREAD

**Issue by Vexatos** [CovertJaguar/Railcraft#579]
Firstly, the jar file contains both .java and compiled .class files of the IC2 API. Secondly, the API is not shipped completely, leading to issues with other mods checking for the API to be present and expecting every class to be there.

My recommendation would be to not be shipping the API at all and instead using `@Optional` and `ModAPIManager.INSTANCE.hasAPI("IC2API")` where necessary.

**Comment by liach** [comment]
Then that's an IC2 issue. @sfPlayer1 puts both java files and class files in the jar.

**Comment by CovertJaguar** [comment]
So much shit explodes....

**Comment by GregoriusT** [comment]
The removal of unneeded Classes is perfectly okay with the IC² API, as far as I know (unless Player changed his mind on that recently, what I doubt).

However it is not okay to contain outdated APIs, like you do (or did in version 9.5.0.0) with the RF API, what breaks compatibility. If you wanna include APIs, such as Interfaces and I mean only Interfaces, then please update them at least.

**Comment by Vexatos** [comment]
I just relayed this here, there were some crashes regarding other mods I don't know detectung IC2API and expecting the entire API to be there.

**Comment by CovertJaguar** [comment]
9.5 as far as I know was current on the RF api at the time of release.

**Comment by GregoriusT** [comment]
Really? I had problems with the Rolling Machine not accepting any RF
and when I did that I downloaded the latest RF API, which had things
moved from IEnergyHandler to seperate emitter and receiver interfaces.
I need to check for both Interfaces in order to convert GT-KU into RF
properly.

2015-04-13 21:44 GMT+01:00, CovertJaguar <notifications@github.com>:

**Comment by GregoriusT** [comment]
I need to check both because of these deprecated API cases.

**Comment by CovertJaguar** [comment]
Yes, there was an issue with my engines grabbing the wrong interface, but the API was definitely updated.

**Comment by liach** [comment]
Fixed by #697
