### ISSUE TITLE
[Bug] Enchantment Table

### ISSUE THREAD

**Issue by ProRedHD** [CovertJaguar/Railcraft#580]
Hey, when I shift click a locking track for example in a enchantment table the track turns into a "tile.railcraft.default.name".

-ProRed

**Comment by CovertJaguar** [comment]
Odd.

**Comment by Ianaver** [comment]
hmmm unable to reproduce

**Comment by ProRedHD** [comment]
Here I recorded a video of it: https://youtu.be/pJbBzafSlD0

**Comment by CovertJaguar** [comment]
I've managed to duplicate it in my dev environment. It seems to only happen when shift clicking a stack. Shift clicking a single track works as expected. It seems to be stripping them of NBT data. This is probably a vanilla or Forge bug.

**Comment by CovertJaguar** [comment]
Yes, this seems to be a Vanilla bug. The same thing will happen to any stackable item with NBT data. In fact the code almost likes like its intentional....
