### ISSUE TITLE
Fluidstack problem with new forge

### ISSUE THREAD

**Issue by Tsunayoshi** [CovertJaguar/Railcraft#581]
Crash-report happend on right-click on an iron tank with ehtanol
http://pastebin.com/VZCRGzny

Forge forge-1.7.10-10.13.3.1370-1.7.10
Railcraft Railcraft_1.7.10-9.5.0.0

edit: info for other users:
Build 1.7.10-10.13.2.1352-1.7.10 should work as I can see from the changelog (haven't tested yet)

**Comment by liach** [comment]
Fixed in dev... Please wait for 9.6 or use forge-1.7.10-10.13.2.1291.

**Comment by Tsunayoshi** [comment]
Thank you!!! I can't downgrade anymore cause CoFHCore/Lib. I will try the dev version :)
