### ISSUE TITLE
Mekanism integration for Dark ores.

### ISSUE THREAD

**Issue by halvors** [CovertJaguar/Railcraft#583]
I think that there should be possible to enrich dark ores in the enrichment chamber, vanilla diamond ores and lapis lazuli can be enriced into dyeBlue/lapizlazili dust and diamonds into diamond gem.

**Comment by liach** [comment]
Ask aidan instead of CJ.

**Comment by halvors** [comment]
Why? It's railcraft that is addin the ore, so have it here makes most sense. You have integration with other mods right?

**Comment by CovertJaguar** [comment]
I already register the Ores with the Ore Dictionary, any further integration would have to be on the Mekanism side.
