### ISSUE TITLE
Crash when opening Coke Oven GUI - Illegal Argument Exception - [Cannot create a fluidstack from a null fluid]

### ISSUE THREAD

**Issue by Cooolaid** [CovertJaguar/Railcraft#586]
I constructed a Coke Oven and when trying to access its GUI, I get an Immediate crash.
Illegal Argument Exception: Cannot create a fluidstack from a null fluid

I am using (Railcraft_1.7.10-9.5.0.0)
my forge is - v10.13.3.1370

http://pastebin.com/75tqRG0H
.

**Comment by CovertJaguar** [comment]
Don't update forge yet.

Duplicate of #581
