### ISSUE TITLE
Railcraft 9.5.0.0 internal server error

### ISSUE THREAD

**Issue by LizzyTrickster** [CovertJaguar/Railcraft#588]
When right clicking on a chest in the world with a minecart, a player got kicked for "internal server error" and spat out an error in the server console

Error report + full mods list:
http://puu.sh/hjMSe/b23d5bafea.txt

Steps to reproduce:
1. get above mods
2. place chest in world
3. right click with minecart in hand
4. probably be kicked for "internal server error"

Also running on forge 1352

**Comment by CovertJaguar** [comment]
Cannot reproduce with just Railcraft, probably a broken core mod's fault. I can attempt to add a null check, but being unable to reproduce it I can't be certain that I'm null checking the correct object.
