### ISSUE TITLE
Make Magnifying glass respect addon mods

### ISSUE THREAD

**Issue by Vexatos** [CovertJaguar/Railcraft#589]
Currently, the Magnifying Glass [only prints the owner of the block if it's a RailcraftTileEntity](https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/items/ItemMagnifyingGlass.java#L112). I'd like it to use IOwnable instead. Since you cannot call `getName()` on those, I recommend either adding a new interface `INameable` to the API or a `getName()` to IOwnable. Otherwise, maybe default to the localized block name if `INameable` can't be found.

**Comment by liach** [comment]
I think here will be two variables: `IOwnable tile` and `TileEntity t`. So we could use some way to get the localized name on the variable `t`? And print the name of the `GameProfile` of the `tile`.

**Comment by CovertJaguar** [comment]
There is a bigger problem...this is currently utterly broken. The server can't localize things and the client doesn't have the necessary info, so the messages are not properly localized right now.

The only way I can think to fix it is to create a new chat packet.

**Comment by Vexatos** [comment]
@CovertJaguar player.addChatMessage(new ChatComponentTranslation("the.chat.key", the, format, parameters))
Done.

**Comment by CovertJaguar** [comment]
Oh, I had no idea you could nest them. The chat code after Mojang's last rewrite was unintelligible to me. =P

**Comment by CovertJaguar** [comment]
Um...I tested your PR. It doesn't work....

**Comment by CovertJaguar** [comment]
In fact it breaks all my chat messages...

**Comment by CovertJaguar** [comment]
I think I've got it figured out.
