### ISSUE TITLE
Coke Oven IllegalArgumentException

### ISSUE THREAD

**Issue by denoflionsx** [CovertJaguar/Railcraft#590]
Forge Version: 10.13.3.1381

Railcraft Version: 9.5.0.0

Steps to reproduce:
1.) Build a coke oven.
2.) Right click the oven to open the gui.
3.) Crash.

Crash report: http://pastebin.com/zKV2epxA

**Comment by Forecaster** [comment]
Newer forge builds changed how fluids work. Railcraft 9.6 will switch to how it works in these. Until that is released stay on a lower version.

I believe the change was introduced in Forge 1354. Versions prior to this one should work.

**Comment by denoflionsx** [comment]
Unfortunately not an option since the other big mods are already updated
for the change and require the higher forge version. I'll just have to
remove rc for now. Thanks.
