### ISSUE TITLE
Block ID conflict without Block ID's?

### ISSUE THREAD

**Issue by accessdenied0** [CovertJaguar/Railcraft#592]
Dear Railcraft-developing-Team,

I did an update to the latest Railcraft (9.6.0.0) recently and as I tried to start up I got this crash report: http://pastebin.com/AtAPrFPm. The reason now I why I wrote this issue is: I'm not sure what to do exactly. I know that the Block ID's are removed since 1.6 and I do not know if there is an option to prevent this to happen. It looks a bit strange to me and I hope I can get a bit of a suggestion of you guys...

thanks for the help,

access_denied

**Comment by CovertJaguar** [comment]
Disable the steam block in the blocks.cfg in older Forge versions if you have multiple types of Fluid blocks or update Forge. Side effect of the Forge changes.

**Comment by rob5251** [comment]
I'm getting the following message during game startup, notifying me that railcraft and thermalfoundation are both trying to register steam.

> [15:14:26] [Client thread/WARN] [FML]: A mod has attempted to assign Block mods.railcraft.common.fluids.BlockRailcraftFluidFinite@691a7180 to the Fluid 'steam' but this Fluid has already been linked to the Block cofh.thermalfoundation.fluid.BlockFluidSteam@3894f32f. You may have duplicate Fluid Blocks as a result. It *may* be possible to configure your mods to avoid this.

However disabling steam in the "railcraft.cfg" causes this:
http://pastebin.com/5E0dZUHm

`fluids {
    B:creosote=true
    B:steam=false
}`
