### ISSUE TITLE
Duplication bug with Bottles in the Coke Oven in Railcraft 9.6.0.0

### ISSUE THREAD

**Issue by Dream-Master** [CovertJaguar/Railcraft#593]
If you put Glass Bottle, Buckets or Cans in a empty Coke Oven Slot (no Creosote inside) it will copy the full stack of the item. So you can duplicated those items very easy. I think this is a bug.
(tested with Forge 1291 and railcraft 9.6.0.0

**Comment by Divineaspect** [comment]
We're getting that as well.

**Comment by liach** [comment]
9f91c4d2d973fd33f34a67016b1517fb8bfc5beb?

**Comment by CovertJaguar** [comment]
This appears to be a case of the beta testers not doing their job. ;)

**Comment by CovertJaguar** [comment]
Scratch that, I cannot duplicate. Video anyone?

**Comment by liach** [comment]
I think they can get a bottle with 1 milibucket? Maybe like that.

**Comment by CovertJaguar** [comment]
Ah, the initial post is incorrect. It does not work when the Coke Oven is empty. There must be some Creosote in it.

**Comment by Dream-Master** [comment]
Work only with a empty coke oven.

**Comment by CovertJaguar** [comment]
No, it does not...

**Comment by Dream-Master** [comment]
If there is creosote inside it works  well.

**Comment by Dream-Master** [comment]
Forge 1291

**Comment by CovertJaguar** [comment]
Only happens when there is some fluid in the tank, but not enough to fill a bucket.

**Comment by liach** [comment]
Or different version of forge?

**Comment by Dream-Master** [comment]
Tomorrow I can make a video to prove it if you need.

**Comment by CovertJaguar** [comment]
Not needed. I've duplicated and fixed already.

**Comment by CovertJaguar** [comment]
Thanks for the report. ^^

**Comment by liach** [comment]
9.6.1.0?

**Comment by CovertJaguar** [comment]
Maybe tomorrow. Busy tonight and want to wait and see if there are more.

**Comment by CovertJaguar** [comment]
Fixed in 9.6.1.0

**Comment by Dream-Master** [comment]
Thanks for fixing
