### ISSUE TITLE
[Question] Can I get newest dev build on mavens?

### ISSUE THREAD

**Issue by liach** [CovertJaguar/Railcraft#599]
If yes, could you cj give me the maven site and the artifacts? Thanks.

**Comment by Forecaster** [comment]
Railcraft doesn't have a build server. CJ produces all builds manually.

**Comment by liach** [comment]
So... I should use this repository as a submodule or just put in a Railcraft dev jar?

**Comment by liach** [comment]
@CovertJaguar Any suggestions about that?

**Comment by CovertJaguar** [comment]
A dev jar is provided alongside the downloads on my blog.

**Comment by liach** [comment]
I know that... Now I'm putting it inside the "lib" folder. There might be nothing wrong if I choose to use this as submodule right?

**Comment by Vexatos** [comment]
This repo does not contain everything you will find in the dev jar, it won't work very well, if at all.

**Comment by liach** [comment]
@Vexatos You mean those things in the `emblem` folder?

**Comment by Vexatos** [comment]
If I recall correctly, some assets aren't there either.

**Comment by CovertJaguar** [comment]
If needed, I can get you access to beta version dev builds. I tried setting things up to upload the Forge maven once, but the way my build script works was causing major issues and I gave up.

You can compile Railcraft yourself if you wish. Submodule might work, I dunno, never tried. Submodules with submodules? 

All you will be missing is sounds and the Emblem code. I often run it without those when I'm developing.

**Comment by liach** [comment]
Thanks CovertJaguar. I now know how to compile Railcraft properly with gradle.
