### ISSUE TITLE
Server crash on boiler explosion

### ISSUE THREAD

**Issue by toarii** [CovertJaguar/Railcraft#603]
Hi,
I have a problem, when the boiler explode, my server crash after that. I have this log : http://pastebin.com/dgs6MXus
I have post the problem for Ender IO to : https://github.com/SleepyTrousers/EnderIO/issues/2422

Thank you.

**Comment by liach** [comment]
Railcraft Boiler...But it seems to be a BuildCraft bug, for the ticked tile is BuildCraft's and there're stacks of BuildCraft source files. [Post it to BuildCraft] (https://github.com/BuildCraft/BuildCraft/issue/new). You might put the full log not only the crash report. Logs are in `logs` folder. Put `fml-server-latest.log`.

**Comment by tterrag1098** [comment]
Buildcraft is only the source of the water, thus initiating the fluid conduit's action. Railcraft seems to be destroying the conduit in the middle of its update cycle, causing this crash.

**Comment by tterrag1098** [comment]
I'm also not sure why he posted that log, this is the relevant one: http://pastebin.com/9ti8vKJE (from the EIO issue)

**Comment by liach** [comment]
Could anyone try Forge 1388, 1400 or 1401?

**Comment by tterrag1098** [comment]
This has nothing to do with forge, it's Railcraft causing an explosion outside of its logic update...

**Comment by toarii** [comment]
I use FML with the Infinity Mod pack from Feed The Beast. I have try with a thermal expansion Aqueous Accumulator and Ender IO fluid conduit, and I have the same thing when the boiler explode.

The Crash Log : http://pastebin.com/P326uH8b
The Full Log : http://www.filedropper.com/fml-server-latest
