### ISSUE TITLE
Railcraft related crash ?

### ISSUE THREAD

**Issue by Carbon-Ghost** [CovertJaguar/Railcraft#604]
Using latest railcraft version, I get this : http://paste.ee/p/olFMS, any ideas on what is causing this ? 

It seems related with fluids, and MAYBE mfr or mekanism, but I am not 100% sure, that's just a guess.

**Comment by liach** [comment]
CovertJaguar has said that you might need to disable steam block if you are using forge 10.13.2.x. That's all. The fluid conflict with MineFactoryReloaded.

**Comment by CovertJaguar** [comment]
Duplicate of #592
