### ISSUE TITLE
Better electricity interaction with other mods

### ISSUE THREAD

**Issue by l3CY** [CovertJaguar/Railcraft#606]
Edit.  See below comment for post.

**Comment by l3CY** [comment]
Since the mobile site won't let me properly edit, I'll post in the comments.  

As it currently stands, Railcrafts electricity seems somewhat taped on.  For instance, why does the RF converter multi block only produce Railcraft Charge when the steam turbine can produces either Charge or EU.  Inversly, why are their carts for EU but not charge.    Why not just let the two systems be used interchangeably.

**Comment by Landrash** [comment]
This might not be 100% accurate but it's hopefully close enough.

Railcraft from the beginning was using the now defunct Minecraft Joules(MJ) power system.
With time the steam turbine came and added a way for us to generate EU with Railcraft.
Time passed and Thermal Expansion and ultimately COFH introduced RF.
Suddenly the Electrical locomotive was introduced and it needed a power system that was made for interacting with he rails etc. Neither EU or MJ fit the bill here so the Charge system was introduced.
RF after some time got adopted into Railcraft and MJ went away.  

So today we have ways of generating RF with engines from steam, EU and Charge with the Turbine.   

On the horizon are RF battery carts so maybe in time we wont have the EU system involved at all.

**Comment by CovertJaguar** [comment]
The bigger question is why it doesn't work with Electric Age and Factorization too. Though the main answer there being that they lack an easily accessed and public API.

**Comment by l3CY** [comment]
As a long time player of IC2 and Railcraft, I'd kindly ask (BEG) that you didn't dump EU outright.  IC2 and Railcraft have traditionally played very well together, and I don't see any benefit -player perspective- in removing electrical compatibility from minecraft's biggest electricity mod.  If anything, I think  the current RC charge implementation should be more seamless with IC2's EU.  For instance, It would make a lot of sense if Railcraft's Flux transformer could output both EU or RC Charge just as Railcraft's Steam turbine currently does.

**Comment by Forecaster** [comment]
That's not going to happen. The Flux transformer produces charge so that you may use RF to power the electric tracks. It will not be made into a way to convert RF into EU.

**Comment by CovertJaguar** [comment]
If you want to use IC2 cables, you already can. As you said, the Turbine outputs EU, and the Electrical Feeder Unit converts EU to Charge.

**Comment by l3CY** [comment]
I respect your decision as mod authors, but may I ask why the strict opposition to add Flux conversion to EU?  I suppose I had hoped that in conjunction with Forestry's electric engine, the Flux Transformer would bring conversion between mechanical and electric energies full circle.

**Comment by CovertJaguar** [comment]
Its just not something that Railcraft needs, and I'd rather leave such balance tipping functions to mods with more stake in the involved power systems. Or in other words, I don't need it and I'd rather not step on anyone's toes by adding it.
