### ISSUE TITLE
Item Loader/Unloader does not recognise carts from other mods

### ISSUE THREAD

**Issue by cloakable** [CovertJaguar/Railcraft#607]
In my case, a Diamond Chest Minecart from the Iron Chests Minecarts mod.

Not sure if this would count as a bugreport or a feature request, but either way it would be nice if it recognised the cart and held it! It goes -into- the cart filter happily enough though.

**Comment by liach** [comment]
They do not implement Railcraft API. That's all.

**Comment by cloakable** [comment]
Aha, I'll go post this on their github page then, thanks!

**Comment by CovertJaguar** [comment]
They should. The only API the loaders care about is IInventory.

**Comment by cloakable** [comment]
Yeah, the loaders will push items into the cart, they just don't recognise them when put into the filter to stop the loaders snagging the locomotive!

**Comment by CovertJaguar** [comment]
Ah...that requires that the cart implements EntityMinecart.getCartItem(). Which it does not appear that they do.

**Comment by CovertJaguar** [comment]
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/carts/CartUtils.java#L92-92
