### ISSUE TITLE
Crash when spawning mobs

### ISSUE THREAD

**Issue by uhsting** [CovertJaguar/Railcraft#608]
Hi, there is a crash when I spawn mobs in the Overworld. However, it shows Railcraft cannot cast the furnace cart into living base. What happened?

Error log: http://pastebin.com/4xM1mYvx

**Comment by Forecaster** [comment]
When you spawn mobs how? With a mod? When they spawn naturally? With a vanilla spawn egg?

**Comment by uhsting** [comment]
1. I switched my Minecraft world from peaceful to normal and it crashed.
2. There are a lot of mods
3. They should spawn naturally.
4. Not even a single egg is used.

**Comment by CovertJaguar** [comment]
The server should have crashed before it could ever send a S0FPacketSpawnMob with a Minecart in it...

**Comment by uhsting** [comment]
I'm trying to find the culprit of the crash.

**Comment by CovertJaguar** [comment]
It kind of smells like a entity ID conflict.

**Comment by uhsting** [comment]
If you like, you may install my modpack through this link: http://api.technicpack.net/modpack/the-big-modpack-10

Please remove Extended Potions as it crashes with the other mod. That crash has been verified though.

I'm also suspecting an ID conflict with some of the mods which have standardized entity ID.

**Comment by CovertJaguar** [comment]
Well that specific Minecart should have an entity ID of 44, or more specifically, I unregister the vanilla implementation and register my own in its place with the entity ID of the original.

**Comment by uhsting** [comment]
Actually the mod works fine without other mods, so it may be the mods which may caused the crash.

**Comment by CovertJaguar** [comment]
Mods should in nearly every case use mod-local unique entity IDs, and not populate the global entity ID list.

**Comment by uhsting** [comment]
Hi I have narrowed down my list of mods which would cause the problem. Together with these mods, the problem occurred once again:

Ars Magica 2
Additional Buildcraft Objects
Advanced Genetics
AgriCraft
Animation API
Applied Energistics 2
AsieLib
BuildCraft Utilities
Buildcraft
Buildcraft Additions
Buildcraft Compatibility
Coroutil
Deeper Caves
DragonAPI
EnderIO
EnderZoo
EnviroMine
Eureka
GalacticraftCore
GalacticraftPlanets
Gems Mod
GeoStrata
Halocraft
Headcrumbs
IC2 Nuclear Control
Industrialcraft
MicdoodleCroe
More Planets
Necromancy
RotaryCraft
Statues
Thaumcraft
Thaumcraft Mob Aspects
Thaumic Exploration
Thaumic Tinkerer
Tropicraft
Twilight Forest
Underground Biomes Constructs
Witchery
Zombie Infection

And also I have tried other modpacks with Railcraft on, and it seems these mods should not cause the crash:
Advanced Genetics
Applied Energistics 2
AsieLib
Buildcraft
Buildcraft Compat
Coroutil
EnderIO
EnderZoo
GalacticraftCore
GalacticraftPlanets
IC2 Nuclear Control
Industrialcraft
MicdoodleCore
More Planets
Necromancy
Statues
Thaumcraft
Thaumic Exploration
Thaumic Tinkerer
Twilight Forest
Witchery

Now my list of suspects are as follows:
Ars Magica 2
Additional Buildcraft Objects
AgriCraft
Animation API
Buildcraft Additions
BuildCraft Utilities
Deeper Caves
DragonAPI
EnviroMine
Eureka
Gems Mod
GeoStrata
Halocraft
Headcrumbs
RotaryCraft
Thaumcraft Mob Aspects
Tropicraft
Underground Biomes Constructs
Zombie Infection

Will do more tests tomorrow. I would like to reiterate again that Railcraft alone would not cause the crash.

**Comment by AEnterprise** [comment]
it can't be BCA nor eureka, they don't touch any of that code, pretty sure the same goes for ABO and BCU

**Comment by CovertJaguar** [comment]
I'd suggest you look up how to do a binary search...it might save you some effort.

**Comment by uhsting** [comment]
Found what is causing the crash:

Headcrumbs is causing the crash.

**Comment by ganymedes01** [comment]
The mob added by headcrumbs probably has the same ID as the minecart. Strange that the game didn't crash on load, which is what usually happens when an entity is registered with an ID that's taken...
