### ISSUE TITLE
Buildcraft robots duplication with Railcraft anchors

### ISSUE THREAD

**Issue by RofElMao** [CovertJaguar/Railcraft#611]
Hi there,

I'm not sure, wether this bug is BC or RC related, so I'm going to post this on both trackers. *apologizes*
While robots are on their docking stations in a chunk that is kept loaded by an anchor of Railcraft (I'm using the personal anchor), each time I relog in those chunks the robots are popping of the docking stations (incl. the holded / stored items). The docking stations itself stays occupied (indicated by the red "LED") and I'm not able to place them on the docking stations again. So I have removed the station which resulted in not only one docking station popps off: Instead I gained the docking station, a duplicate of the robot (identic energy level) and also duplicates of the items that the robot was holding / storing. (Yeah... Theoretically I now have an unlimited amount of everything ^^)
This was reproducable each time I removed the anchor, relogged, replaced and relogged again.

Forge version: 10.13.2.1291
Buildcraft version: 6.4.15
Railcraft version: 9.6.1.0

Best regards to all the devs! :)

**Comment by CovertJaguar** [comment]
Well its either Forge or Buildcraft who would have to fix it as I all I do it tell Forge which chunks to load.
