### ISSUE TITLE
Ticking Entity crash

### ISSUE THREAD

**Issue by jordsta95** [CovertJaguar/Railcraft#612]
Whenever anything has steam in it (boiler, steam engine, etc.) I get this crash:
http://pastebin.com/JifSTqbW

This is using the latest release of Railcraft (as of the time of posting)

**Comment by CovertJaguar** [comment]
Try updating your Forge.

**Comment by Speiger** [comment]
@CovertJaguar @jordsta95 i think you have to downgrade your forge because of that fluid update.
^^" At least it seem like that
