### ISSUE TITLE
Minecart dupe bug

### ISSUE THREAD

**Issue by AlphaEnigma** [CovertJaguar/Railcraft#613]
In version 9.6.1.0 anytime someone places a minecart it duplicates and places 2 carts. sometimes when breaking the 2nd cart you will receive a 2nd cart back. This has been tested on multiple servers with other mods and with only this mod.

**Comment by CovertJaguar** [comment]
This is a bug on Cauldron's end. It cannot/will not be fixed.

**Comment by liach** [comment]
@Prototik Any ideas?

**Comment by CovertJaguar** [comment]
Cauldron doesn't properly cancel the item use event that Railcraft uses to spawn its cart implementation instead of vanilla's. It works fine in Forge.

**Comment by Prototik** [comment]
Fixed in KCauldron#cfda3c2dca

**Comment by AlphaEnigma** [comment]
Really? this does not happen in version 9.5.0.0 of railcraft only the 9.6+ versions

**Comment by CovertJaguar** [comment]
@AlphaEnigma because I didn't use the event in those versions of Railcraft. It was added to fix other bugs that arose from not using Railcraft's cart implementation.
