### ISSUE TITLE
Placing a minecarts on track places two minecarts.

### ISSUE THREAD

**Issue by mmance** [CovertJaguar/Railcraft#616]
Railcraft_1.7.10-9.6.1.0.jar

Only happen to the vanilla minecarts, but only with railcraft installed.

I am running cauldron-1.7.10-1.1381.06.221-server.jar if that is helpful.

**Comment by liach** [comment]
Duplicated with #613 and #614. Use newer cauldron.

**Comment by mmance** [comment]
many things
