### ISSUE TITLE
[9.6.1.0] Routing blocks and redstone signals

### ISSUE THREAD

**Issue by RoqueDeicide** [CovertJaguar/Railcraft#619]
According to the "Help" section in the Routing Table item, "Redstone=&lt;true, false&gt;" allows routing block to react to redstone signals. I tried using that and it simply didn't work, redstone signal or lack of it doesn't seem to be detected by Routing Switch Motor of Detector - Routing no matter where the signal is coming from (tested sides and bottom). Maybe the operator is different?

**Comment by Forecaster** [comment]
Please show us your setup and the routing table.

It's worth noting that the redstone condition doesn't work on it's own. You need another condition present as well.

**Comment by RoqueDeicide** [comment]
The Routing Table:

```
Dest?=.*East
AND
Redstone=true
```

Without last 2 lines it works just fine.

The setup is

```
    T
T - W - T
    R - S
```

Where W - wye track, T - normal track, R - routing switch motor, S - Signal Receiver Box that is set to output Redstone signal on the green (and the Block Signal is green).

The test-case ticket destination is coolantEast.

**Comment by Forecaster** [comment]
Operators (AND, OR & NOT) operate on the following operands (conditions).

i.e.
Operator
  Condition
  Condition

Your example should look like this:
```
AND
Dest?=.*East
Redstone=true
```

**Comment by RoqueDeicide** [comment]
OK, so it has to be paired with something? Also, I don't remember this information in the Help section, I think it only said, that it also redstone signal to be detected, maybe this should be mentioned in there?

**Comment by CovertJaguar** [comment]
There is syntax checking. An error should have been shown next to the slot when you put it in the Routing Detector.

And no, it doesn't need to be "paired with something" whatever that means....the AND operator must have two operands. The manual explicitly states this.

**Comment by RoqueDeicide** [comment]
Ok, I did some tests.

1) When Redstone=true is used alone the detector will only go off when it detects the cart on the track, which is counter-intuitive since switch motors are guaranteed to switch the track when getting the signal. If this is not mentioned in the Help section of the Routing Table, it should be.
2) The error shows up as a tool-tip for the red cross next to the item slot for the table, which makes the error message resource pack dependent: GUI texture in mine doesn't have that Cross texture at the rop-right corner, so the cross is invisible for me. Also, right-clicking on the motor or detector with routing table puts the table into the block without opening GUI. I suggest making open GUI when there are errors in the table.

**Comment by CovertJaguar** [comment]
Nothing I can do about misleading Resource Packs. You'll need to take it up with the pack developer.

But what you say about opening the GUI makes sense, I'll investigate the feasibility.

As for the behavior, I can't really comment on that until I can try it myself (still need to reconstruct my dev env).
