### ISSUE TITLE
[Request] Railcraft Steel + Tinkers Construct Support

### ISSUE THREAD

**Issue by Razorskills** [CovertJaguar/Railcraft#620]
Hello, basically I would love if when I put my railcraft steel tools, armor, ingot, block etc in the smeltery. It would melt down into steel like steel normally would if it was tinkers construct steel.

So far, it is the only metal in my pack that does not melt down in a smeltery correctly. I suggested this for ExtraTiC since it seemed like something the mod does. But, then it would be even better if the support was in the actual mod itself and not in a 3rd mod you would need.

Here was my suggestion there:
https://github.com/Glassmaker/ExtraTiC-Localization/issues/25#

**Comment by CovertJaguar** [comment]
Its already possible to recycle the tools back into Steel Ingots in the Blast Furnace. And it appears that the Ingots are compatible with Tinkers, so I'm going to close this.
