### ISSUE TITLE
[Feature] Change direction of locomotive

### ISSUE THREAD

**Issue by DireTry20** [CovertJaguar/Railcraft#621]
Add a new track that change the direction of a steam locomotive (sends it into reverse).

EDIT: There is currently a way to make it start going forwards but not backwards.

**Comment by Vexatos** [comment]
Uuuh, control tracks set in the opposite direction will make the locomotive slow down until they make it turn, don't they?

**Comment by Forecaster** [comment]
He means setting it to the reverse speed, not turning it around.

**Comment by DireTry20** [comment]
thx, ill try harder in future

**Comment by DireTry20** [comment]
I hope that this is not any trouble, but is there an ETA, im just curious about how dev happens

**Comment by Forecaster** [comment]
Sorry, no ETA. Releases happen semi-sporadically, and since CJ has had a harddrive failure recently and lost a lot of stuff including some railcraft dev stuff it may be a while before the next one.

**Comment by DireTry20** [comment]
it would doesn't need to be a new track but a change made to the limiter track
