### ISSUE TITLE
Crashing on load due to NoClassDefFoundError

### ISSUE THREAD

**Issue by craft90** [CovertJaguar/Railcraft#622]
So I recently tried to play RailCraft in my personal modpack. But for some reason the game crashes on load. Here's the crash report http://pastebin.com/zUxd53Eh

It seems to be an issue with the crowbar as far as I can tell. I guess it could be an issue with Reikas DragonAPI and RotaryCraft? I'm not sure how to fix it tho.

**Comment by Forecaster** [comment]
Looks like something is trying to use an api but can't find the right classes. You may have to binary search to find which mod is causing it.

**Comment by craft90** [comment]
I'd a search by activating and deactivating mods and nailed the issue down to Reika's ElectriCraft. On closer inspection it seems to try to make a call out or something to buildcraft api. I guess I should get in touch with Reika about this issue

**Comment by CovertJaguar** [comment]
DragonAPI breaks everything...

**Comment by ReikaKalseki** [comment]
Caused by: java.lang.ClassNotFoundException: buildcraft.api.tools.IToolWrench
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 54 more

Seems like the crowbar has a hard dependency on BC.


Also, "Breaks everything"? Just like that hidden block, right? :P

**Comment by liach** [comment]
Different API shipped or what? Looks like a mess.
Note: Railcraft ships BuildCraft API.

**Comment by ReikaKalseki** [comment]
I do not include the BC API at all.

**Comment by CovertJaguar** [comment]
Well I'd need a full log to say exactly what is happening.
