### ISSUE TITLE
Locked/Private (electric) locomotives do not accept tickets from locked routing tracks by the same owner.

### ISSUE THREAD

**Issue by tyrope** [CovertJaguar/Railcraft#623]
The tooltip on locked locomotives state: `It will only accept Tickets issued by them or an Op.`
Tooltip of a locked routing track states: `Only the owner or an Op can manipulate it`
Since both of these have a similar permission description ("owner or an op"), one could assume that it would work.. alas, it does not. Forcing people to keep automated cargo locomotives, for example, to public.

**Comment by Forecaster** [comment]
What version is this and what else do you have installed?

This works fine for me. If you are using cauldron that might be messing with the ownership detecton I would guess.

**Comment by tyrope** [comment]
FTB Infinity pack version 1.6.2 with no modifications other than the Ender Zoo's Concussion creeper teleport range.

**Comment by Forecaster** [comment]
Allright... you may have to binary search through that to find what is causing the issue. Although you should start by removing everything except Railcraft and ensure it works then.
