### ISSUE TITLE
Railcraft plates not oreDict

### ISSUE THREAD

**Issue by Tsunayoshi** [CovertJaguar/Railcraft#624]
Hi,

I had the problem thate RC (tin,copper,iron,steel) plates are not in the oredictionary. I had used mine/modtweaker to change it. Now I can use the RC plates for IC2 recipes and a few IC2 plates for RC recipes, but there are also recipes in RC that are not compatible the oreDict (e.g. Flux Transformer).

Is this intended?

Here the things I have changed with mine/modtweaker:

//Adding Railcraft Plates to oreDictionary
oreDict.plateIron.add(<Railcraft:part.plate>); //ironPlateRC
oreDict.plateSteel.add(<Railcraft:part.plate:1>); //steelPlateRC
oreDict.plateTin.add(<Railcraft:part.plate:2>); //tinPlateRC
oreDict.plateCopper.add(<Railcraft:part.plate:3>); //copperPlateRC

**Comment by Forecaster** [comment]
Working as intended.
