### ISSUE TITLE
Drum and Tank Interaction allows duplication of fluids and drums

### ISSUE THREAD

**Issue by Quetzi** [CovertJaguar/Railcraft#625]
There are some unexpected behaviours when using Extra Utilities drums with Railcraft Tanks. Drums are able to be stacked and interact with the Tanks interface.

1. If you put a stack of 64 drums in the tank GUI you will only get the fluid for 1 tank although all empty.
2. If you right click a tank with a stack of empty drums one drum is removed (and 5000mb from the tank) from the stack and fails to render in your inventory as a partially filled drum. On double clicking the first empty space in your inventory a stack of drums gets rendered, each with 5 buckets of fluid in, which can then be emptied individually for a fluid gain. You also double the drums you had before.

forge-1.7.10-10.13.3.1401-1710ls-universal.jar
Railcraft_1.7.10-9.6.1.14.jar
extrautilities-1.2.5-fc2build-2.jar

Corresponding issue on XU tracker: https://github.com/rwtema/extrautilities/issues/630

**Comment by jaz000** [comment]
I was surprised to find that I can put an extra utilities drum into the UI of the multiblock tank and have it empty it into the tank - but it only worked for the first one then I have the following problems:

Subsequent drums empty but no liquid is inserted into the tank (liquid vanishes)
The tank now refuses to accept liquid from drum-> extra utils transfer node -> valve
The tank now refuses liquid from drum -> bc pipe -> valve
In fact using either bc pipe or extra utils the first insertion works but subsequent ones the liquid stays in the pipe
(all the above done with galacticraft oil)
I didn't notice it happening but it has also duplicated a couple of the extra utils drums presumably when inserting into the UI

this is using beyond reality modpack 2.3.0b

forge 1403
extra utils 1.2.6
railcraft 9.6.1.0
