### ISSUE TITLE
Furnace recipe config effect flipped

### ISSUE THREAD

**Issue by PikadudeNo1** [CovertJaguar/Railcraft#627]
Setting the config line for the furnace cart recipe to true *disables* it, while leaving it false *enables* it. Tested in Railcraft 9.6.1.0.

**Comment by Yopu** [comment]
I believe I've located the bug at:
[ModuleCore line 191](https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/modules/ModuleCore.java#L191)
Condition needs to be inverted.

Of course the default value would need to be changed at:
[RailcraftConfig line 320](https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/core/RailcraftConfig.java#L320)

However this would likely cause issues with people loading from previous configs. Thus it would likely be simpler to change the config description.
