### ISSUE TITLE
Placing Buildcraft tank beside a Railcraft track causes world crash

### ISSUE THREAD

**Issue by neograymatter** [CovertJaguar/Railcraft#629]
Crashlog: http://pastebin.com/f7nLQVXb
Forge: 10.13.3.1428
Railcraft: 9.6.10
Buildcraft: 7.0.8
Buildcraft compat: 7.0.7

Have a few pieces of track down, place a tank right beside them, World crashes and cannot be reloaded until you remove the tank or track via MCedit. After it took down my server, I reproduced the problem in new single player creative world as well.

**Comment by asiekierka** [comment]
@neograymatter  - nevermind, further debugging pointed out it's likely BC's fault after all so close this issue please and look at https://github.com/BuildCraft/BuildCraft/issues/2781
