### ISSUE TITLE
Unable to open chest carts (9.6.1.0)

### ISSUE THREAD

**Issue by Ianaver** [CovertJaguar/Railcraft#631]
when chest carts are in the world, you are unable to open them.

**Comment by liach** [comment]
Are you using a client connecting to a server?

**Comment by Ianaver** [comment]
nope :/

**Comment by liach** [comment]
Any more descriptions?

**Comment by Ianaver** [comment]
just won't open, simple as that really. all single player

**Comment by wshadow** [comment]
Works fine here, with Railcraft 9.6.1.15 (also Singleplayer)

**Comment by Ianaver** [comment]
@wshadow You have to realize that you are a donor and have beta releases available to you, I am a standard user therefore I have to wait weeks even months before I am allowed to access a new version with bug fixes

**Comment by wshadow** [comment]
@Ianaver I was just trying to point out, that this issue no longer exists in the latest beta. So if this is indeed an issue with v. 9.6.1.0 and not just an issue with your modpack/client/computer/whatever, then you can look forward to the next release, where this will be fixed.

**Comment by Ianaver** [comment]
@wshadow derp on my part, closed

**Comment by Ianaver** [comment]
it happened earlier in mineshafts but I guess I just derped
