### ISSUE TITLE
[Mod Interaction] misuse of dragonAPI causes crash (this mod and ender IO are culprits)

### ISSUE THREAD

**Issue by Ianaver** [CovertJaguar/Railcraft#636]
An issue with rotarycraft recipes causing crash; something about null item stacks? Either way you may want to at least look and see what on your side is causing this issue, also if you plan on testing this this mod appears to make the game stall after load

paste: http://pastebin.com/1w1TYxVX

also see on enderIO repo (same as here)

SleepyTrousers/EnderIO#2587

**Comment by abalabahaha** [comment]
Nowhere in the crash log is there anything about Railcraft,,,

**Comment by liach** [comment]
> Not related to Railcraft
Reika's bug? Somewhat weird.

**Comment by Ianaver** [comment]
@liach I reported it here because with my pack for some reason something within the mod makes this happen.

mods:
![mods](https://cloud.githubusercontent.com/assets/8153290/8177283/fa041350-13b7-11e5-9184-61fbd7c35aaa.PNG)

**Comment by Ianaver** [comment]
@CovertJaguar  if EIO or railcraft and NEI (and core) and rotarycraft and liteloader are present, crash occurs. Why? I am not sure. I don't even know anymore so I might as well close this before my brain explodes.... :P I hate when an issue instead of only being 2 mods max its 4 or more because it actually took me legit 3 hours of constant searching to find this.... I am sorry....

**Comment by LizzyTrickster** [comment]
Reika's mods are known for breaking everything around them

**Comment by Ianaver** [comment]
@LizzyTrickster I understand the whole breaking thing but I don't get why a modding API (liteloader) could cause recipe crashes when it doesn't even use NEI or rotarycraft?
