### ISSUE TITLE
Destruction of protected species

### ISSUE THREAD

**Issue by leagris** [CovertJaguar/Railcraft#637]
It has come to my attention: Railcraft Mod. generate pockets of toxic Oil where inoffensive protected animals species members called bats, dies by thousands.

In the name of the Protected Species of Minecraft Fantasy Organization, I pose you an ultimatum to:
- Either find a solution to save those poor bats from your deadly chemicals.
or
- Take a deep breath before rolling on the floor laughing.

-- 
Your dear annoying prank bug reporter.

**Comment by Forecaster** [comment]
Railcraft doesn't generate any oil...

:P

**Comment by liach** [comment]
It might be A.F. day or @leagris' account was stolen by someone.
