### ISSUE TITLE
I can not remove a recipe using ModTweaker2

### ISSUE THREAD

**Issue by Tsyklop** [CovertJaguar/Railcraft#643]
Recipes are not deleted from all the machines. He writes this:

![2015-06-28_09 05 19](https://cloud.githubusercontent.com/assets/6783568/8395352/e93d3ff8-1d74-11e5-9450-e763b0556a3e.png)

ModTweaker and RailCraft laset versions

**Comment by Tsyklop** [comment]
https://github.com/jaredlll08/ModTweaker2/issues/117

**Comment by liach** [comment]
Guy those recipes are only available when IndustrialCraft 2 is installed. I don't think you have this mod installed.

**Comment by Tsyklop** [comment]
@liach it is installed. In the picture you can see from the MFSU IC2

**Comment by liach** [comment]
Ok, I didn't see that modtweaker issue. It's their bug.

**Comment by jaredlll08** [comment]
Yea, I am sorry, this guy doesn't seem to understand that some people actually have a real life and he demands that we fix it asap, needless to say, every-time he asks, I delay it.

**Comment by Tsyklop** [comment]
Excuse me, please.

**Comment by liach** [comment]
Actually I am also careless that I didn't take a look at ModTweaker repository. My bad.
