### ISSUE TITLE
[Suggestion] Energy Cell minecarts similar to IC2 batbox carts?

### ISSUE THREAD

**Issue by McSharidan** [CovertJaguar/Railcraft#644]
RailCraft supports stuffing IC2 batboxes into minecarts, to further supply electric loco's with power on unpowered rails. Given that mr. CovertJaguar very kindly granted us support for Redstone Flux (though at a reduced rate: 80% - sadface), it would be very nice to be able to do the same with Thermal Expansion Energy Cells: stuff them into minecarts for the same kind of support as the IC2 batboxes (MFE etc.). Personally I don't play with IC2 in my modpack anymore, so I don't really have all that great support for electric loco's because of that, which is why I'm sticking with steam loco's for the most part as they can easily go the long distances, where my electric trains only do local station jobs. Most of the major mods these days support RF in one form or another, while EU is less and less supported by other mod authors.

Thanks for taking the time and thanks for a great mod!

**Comment by Vexatos** [comment]
If I recall correctly, he stated that there won't ever be RF battery carts powering electric locomotives. But there will be RF battery carts, they will just be _only_ for energy transfer. And the EU battery carts may or may not be changed into Charge battery carts instead, not sure though.

**Comment by liach** [comment]
#397

**Comment by McSharidan** [comment]
Well, it seems I missed that other suggestion when I was trying to trawl through entries looking for it. My apologies for double posting the suggestion.

Thank you both for the information and cross reference. It's appreciated! Looking forward to seeing what mr. CovertJaguar comes up with.
