### ISSUE TITLE
Railcraft 9.6.1.0 - all anchors chunkloading when player offline

### ISSUE THREAD

**Issue by b0bst3r** [CovertJaguar/Railcraft#646]
Passive and personal ones are doing offline chunkloading.

Only config change I have is world anchors are set to false on craftable and ability to pipe pearls in is also set to false.

Now have reports from several players on the server that this happens.

Happened with Forge 1391 and recently moved to 1448, happens on both.

**Comment by wshadow** [comment]
I think for the passive one, this is intended. The changelog says "NEW: Add Passive Anchor, does not force load chunks on game load, only when visited."

For the personal one this sounds like a bug. How did you test this? Do you have other mods installed as well, or does this happen with just Railcraft?

**Comment by b0bst3r** [comment]
Whole host of other mods whilst we knew the passive was new and could be open to interpretation if it was meant as an online or offline chunkloader the personal one is apparently doing the same.

We have players using personal and passive and they all say that chunkloading is still going on when they log off and we're all miles apart.  

So the first thing that needs clearing up is the wording around the passive anchor on whether it's an online or offline chunk loader and you simply visit to "spin" the anchor up.

Here's a mod list and we are currently on Forge 1448 http://pastebin.com/mXY8xkBU

**Comment by b0bst3r** [comment]
Oh err interesting, just had a report from a player that says his stuff is chunkloading and he has no chunkloader so not sure what's going on right now.

Looks possible the whole map is being chunkloaded.

**Comment by b0bst3r** [comment]
Ok after further testing the passive anchor is offline chunkloading.  If it is meant to do this (which makes it kinda pointless) then close this incident.  If it's meant to function as an offline anchor which you have to visit to enable then it's bugged.

**Comment by Landrash** [comment]
Passive Anchors should only chunkload after they have been visited by a player.They do on the other hand keep the chunk loaded after even if the player is offline.

#520 & #489 has some information on them and the discussion around them.

**Comment by CovertJaguar** [comment]
The Personal Anchor will continue to load chunks for either 5 or 15 minutes after the player logs off. I can't remember which. This is to allow players to reconnect in the case of a disconnect.
