### ISSUE TITLE
Wrong keyword in routing table

### ISSUE THREAD

**Issue by harvald** [CovertJaguar/Railcraft#648]
Railcraft 9.6.1.0

In help page of routing table is specified keyword "Rider" but this not work. In fact mod has implemented keyword "Riding" instead with the same function. 

(This is something other than keyword "Ridden")

**Comment by Yopu** [comment]
For backwards compatibility reasons, I changed the description rather than the implementation.

**Comment by CovertJaguar** [comment]
Yeah, that's fine. I probably derped the description.
