### ISSUE TITLE
oreDict support needs some polish

### ISSUE THREAD

**Issue by SlightlyVisible** [CovertJaguar/Railcraft#650]
Railcraft is currently lacking ore dictionary support in select areas which can be quite annoying when playing or building a mod pack.  Using railcraft's own ingots or blocks does not always make the most sense in mod packs.  There are many mods out there that deal with a far greater number of metals then railcraft and so, for the case of texture consistency, it makes very much sense to use other mods objects.

There are cases where Railcraft does not resort to the ore dictionary when railcrafts own metal blocks are disabled via config.

![steelblocks](https://cloud.githubusercontent.com/assets/13194020/8516117/023845ac-237e-11e5-9e93-a1db6b2ba70e.png)

Others cases include the blast furnace not converting iron blocks when railcraft's own steel is disabled and the Electric Shutting Wire becoming un craft-able and not searching the oreDict for lead.

Lastly, the metals chest seems to default to converting all ingot to their railcraft equivalents.  A config option to change this behavior so that it always prioritized the oreDICT, or at the very least stop converting all ingots to railcraft form, would be nice.

**Comment by CovertJaguar** [comment]
What you are asking for is likely to cause more problems than it solves.
