### ISSUE TITLE
[Suggestion] Addons for Rock Crusher

### ISSUE THREAD

**Issue by SJ1133** [CovertJaguar/Railcraft#652]
Would it be possible to add a way (Upgrade?) to increase the speed, improve secondary output or perhaps both?

**Comment by Vexatos** [comment]
This is not how Railcraft works...

**Comment by SJ1133** [comment]
Oh sorry :/  
How about an advanced tier of the rock crusher? Would that work better or am i way off the mark?

**Comment by Vexatos** [comment]
There are rumours about improving the rock crusher already...

**Comment by SJ1133** [comment]
Ill just close this. Sorry to waste your time.
