### ISSUE TITLE
Crash on Startup - NoClassDefFoundError

### ISSUE THREAD

**Issue by Kupanfu** [CovertJaguar/Railcraft#653]
Starting to get a crash on startup with Railcraft installed. When i remove the mod the crash stops.
Latest version of Railcraft is the one i have installed. 9.6.1.0

here's the crash log: http://pastebin.com/Btfzetv3

**Comment by liach** [comment]
It seems this is an IC2 API issue? Poke @CovertJaguar to tell him that he might need to stop shipping IC2 API and use  `@Optional.Interface()`?

**Comment by liach** [comment]
It seems this is an IC2 API issue? Poke @CovertJaguar to tell him that he might need to stop shipping IC2 API and use  `@Optional.Interface()`?

**Comment by Kupanfu** [comment]
So just an update, did a fresh clean install, and reinstalled mods a few at a time. I did not install some of the mods i had previously, and now the game works with railcraft installed and no crashes.

The mods i removed are -

Additional Build Craft Objects
Buildcraft and Buildcraft Compat
extrautilities
mantle - was a leftover from tinkers construct that i missed when i removed TC
MFR magical crops compat
openblocks
randomthings

**Comment by liach** [comment]
You mean adding any one of them will cause crash? If is that's weird.

**Comment by Kupanfu** [comment]
Yeah, i havn't actually put those mods back in to test it, cause i didn't want to take the chance of corrupting the fresh install, plus i don't plan on actually using them anymore so i just left em out

**Comment by liach** [comment]
Okay... I'd report it to bccompat.
