### ISSUE TITLE
Item Loader/Unloader strange redstone behaviour

### ISSUE THREAD

**Issue by dunkfordyce** [CovertJaguar/Railcraft#654]
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/blocks/machine/gamma/TileLoaderBase.java#L125

This is weird and stops us using other redstone stuff from other mods like redstone conduits and wire. Also just a simple redstone torch wont work as an inverted signal. The correct thing to do seems to be to just return isPowered without the strange block checking. 

I had a look at the history of the file but this change was from the initial import so I cant tell if there is a good reason for this and I dont know it or if its just some ancient weirdness.

**Comment by dunkfordyce** [comment]
A commit to do it https://github.com/dunkfordyce/Railcraft/commit/c352b66cb7a758b7c47c54cf50db4187cbd36806

For what its worth, Iv been using this for 17 days without any issues, just smaller contraptions

**Comment by Yopu** [comment]
See: https://github.com/CovertJaguar/Railcraft/issues/674

At current it is working as intended.
