### ISSUE TITLE
Engines does not implement IEnergyProvider

### ISSUE THREAD

**Issue by ruifung** [CovertJaguar/Railcraft#661]
See https://github.com/aidancbrady/Mekanism/issues/2825

**Comment by CovertJaguar** [comment]
This is intentional. You are not supposed to be able to access the Engines stored Energy. IEnergyConnection is the correct interface.

**Comment by artturnip** [comment]
Is the effect of Engines not interacting with Mekanism Universal Cable intended?

**Comment by CovertJaguar** [comment]
This has been fixed on Mekanism's side.
