### ISSUE TITLE
[Request] Move recipes to Init instead of PreInit

### ISSUE THREAD

**Issue by BluSunrize** [CovertJaguar/Railcraft#662]
Basically, people keep filing error reports that Immersive Engineering's creosote bottles+buckets do not work to create wooden ties. The reason for that is that IE registers it's FluidContainers in PreInit, but not before Railcraft has already registered it's recipes for wooden ties. @malte0811 on my issue tracker has already traced this:

https://github.com/BluSunrize/ImmersiveEngineering/issues/101

The obvious solution would be to move the registration of those recipes to the init phase, assuming that this does mess up other parts of the code (Haven't checked that yet ^^"). A different, probably less breakage inducing way (but not as pretty) would be to not use defineRecipes() in ItemTie and instead register the recipes manually in the init phase.

**Comment by JonathanMH** [comment]
yes please +1 :)

**Comment by smbarbour** [comment]
Recipes should not be done in preInit.  Recipes should be done in init or postInit so that all mods have a chance to register their items before recipes are set.

**Comment by BluSunrize** [comment]
Thank you. Now if only Covert or one of the Railcraft maintainers (provided there are some) would aid with this >_>

**Comment by vpontin** [comment]
related to my issue regrading CraftGuide? #679

**Comment by CovertJaguar** [comment]
Hmm...yes fair point.
