### ISSUE TITLE
Village workshop sometimes floats

### ISSUE THREAD

**Issue by notabadminer** [CovertJaguar/Railcraft#665]
The railcraft componentworkshop does not generate a foundation like the default village worldgen buildings and will sometimes float midair or on water. The first two screenshots are of the issue. The third is of one of my shops using the functions in StructureVillagePieces to generate a foundation. I recently fixed my worldgen buildings and would gladly submit a fix for this issue if you'd like.

![2015-07-24_22 08 10](https://cloud.githubusercontent.com/assets/5705846/8888047/8d2c478a-3251-11e5-8869-849270bfb646.png)
![2015-07-24_22 13 48](https://cloud.githubusercontent.com/assets/5705846/8888048/96488cfc-3251-11e5-8ee6-30bdfb1667ac.png)
![2015-07-24_22 14 18](https://cloud.githubusercontent.com/assets/5705846/8888057/0b64e7ba-3252-11e5-9148-09b0faf23a89.png)

**Comment by Landrash** [comment]
Submit a fix but dont forget the (CLA){https://www.clahub.com/agreements/CovertJaguar/Railcraft)

**Comment by CovertJaguar** [comment]
Fixed by #669
