### ISSUE TITLE
Unable to craft normal rails with mod installed.

### ISSUE THREAD

**Issue by AshenFlames** [CovertJaguar/Railcraft#668]
So I have Version 9.6.1.0 installed and for some reason I can't craft normal rails (3 iron ingots on each side with a stick in the center) or the vanilla powered rails while it is installed.

**Comment by Landrash** [comment]
Recipes for rails are changed to a more favourable recipe.
It's on the wiki and the recipe should be visible in NEI.

**Comment by Yopu** [comment]
http://railcraft.info/wiki/track:track
http://railcraft.info/wiki/part:rails
http://railcraft.info/wiki/part:railbeds
