### ISSUE TITLE
Problem with worldgen

### ISSUE THREAD

**Issue by Tomson124** [CovertJaguar/Railcraft#670]
I made new modpack for my community but unfortunatly there are no railcraft ores  generated... that's really weird.
Does anyone have an idea why?

**Comment by Forecaster** [comment]
Railcraft ores spawn in large veins and can be difficult to find.
You should keep looking. Wednesday, 29 July 2015, 10:19pm +02:00 from Thomas Wolfgruber < notifications@github.com> :

**Comment by Yopu** [comment]
Did you find any? Or is this still an open issue?

**Comment by Tomson124** [comment]
No I didn't found any as I tweaked the oregen with ThermalFoundation Worldgen options. I copied this file from the Feed The Beast Infinity PAck but the *.json file was not right formatted so there was no orespawn :D 
But it's fixed now.

**Comment by Yopu** [comment]
Cool, thanks!
