### ISSUE TITLE
Item loaders/unloaders only emitting redstone signals to vanilla redstone

### ISSUE THREAD

**Issue by TheQuantumGeneral** [CovertJaguar/Railcraft#674]
Item loaders and unloaders, I didn't test the fluid ones, will only output a redstone signal to vanilla redstone items like dust and repeaters, cannot make them emit into wireless redstone transmitters, project red cables, or zetta industries redstone wires or computercraft computers. 

Some pictures. Using version 9.7.0.0

![2015-08-11_15 07 17](https://cloud.githubusercontent.com/assets/7843312/9190648/f0dcd3c0-403a-11e5-8440-d44b17d4a470.png)
![2015-08-11_15 06 11](https://cloud.githubusercontent.com/assets/7843312/9190646/f0db3c86-403a-11e5-8300-d48c596d0578.png)
![2015-08-11_15 06 30](https://cloud.githubusercontent.com/assets/7843312/9190649/f0dd32fc-403a-11e5-9aa5-b4dc1e0f9290.png)
![2015-08-11_15 06 40](https://cloud.githubusercontent.com/assets/7843312/9190647/f0dbabe4-403a-11e5-97f7-24c292f6f36d.png)
![2015-08-11_15 25 29](https://cloud.githubusercontent.com/assets/7843312/9190819/4e33db7a-403d-11e5-8a64-cf240ed20753.png)

**Comment by CovertJaguar** [comment]
This is intended, as there is no way to me to possibly whitelist everything, and emitting random redstone near tracks tends to cause strange behaivor.

**Comment by AEnterprise** [comment]
would it be possible to toggle a side for this? so you can select sides on the gui to emit redstone?

**Comment by CovertJaguar** [comment]
My gui skills are not that great. I should also note that Repeaters work as well.
