### ISSUE TITLE
[Enhancement] Add Tin Gear Bushings to Dungeon Loot

### ISSUE THREAD

**Issue by abculatter2** [CovertJaguar/Railcraft#676]
As things are now, without other mods adding their own sources of tin, tin is an extremely limiting resource for the mod, due to the tin gear bushings. Adding these to the list of dungeon loot seems like an appropriate way to make acquiring them a bit less of a grind, without removing the desire to go searching for tin ore.

**Comment by CovertJaguar** [comment]
I like this!
