### ISSUE TITLE
Smoker's smoke covered by water

### ISSUE THREAD

**Issue by elifoster** [CovertJaguar/Railcraft#680]
Here's what I mean: ![Screenshot](http://puu.sh/jNLZK/0968d54ac1.png)

Running 9.6.1.0 for 1.7.10.

**Comment by cabralRodrigo** [comment]
@elifoster It's a vanilla bug. Nothing that CJ can do about it.

**Comment by elifoster** [comment]
Huh. I've never noticed it before.
