### ISSUE TITLE
RFTools compatibility

### ISSUE THREAD

**Issue by VashaTS** [CovertJaguar/Railcraft#681]
Railcraft materials in RFTools dimlets show as unknown dimlet
These ones:

> milte.railcraft.brick.nether2
> milte.railcraft.brick.bloodstained2
> milte.railcraft.brick.infernal2
> milte.railcraft.brick.infernal5
> milte.railcraft.brick.abyssal2
> milte.railcraft.brick.sandy2
> milte.railcraft.brick.quarried2
> milte.railcraft.brick.frostbound2

Example screenshot: http://i.imgur.com/rIxfXsU.png

I dont know if this is Railcraft issue or RFTools issue, but I also opened an issue at RFTools:
https://github.com/McJty/RFTools/issues/299

Modpack Direwolf20 1.7
`Railcraft_1.7.10-9.6.1.0`
`mcjtylib-1.2.0`

**Comment by smbarbour** [comment]
I have both RFTools and Railcraft.  The "is missing!" message indicates that dimlets for those blocks previously existed but no longer exist.  Perhaps they were added by config and the config was subsequently wiped out?

**Comment by CovertJaguar** [comment]
Dimlet??

**Comment by bookerthegeek** [comment]
Dimlet, think rf powered mystcraft. 

Most likey NOT a railcraft issue.
