### ISSUE TITLE
The bedrock can be poached by undercutter cart

### ISSUE THREAD

**Issue by IamAchang** [CovertJaguar/Railcraft#682]
I notice this details In many version .Using an undercutter cart can get bedrock. 
![qq 20150829011101](https://cloud.githubusercontent.com/assets/12226796/9552809/665bfd5a-4ded-11e5-9087-2bed474342ca.png)

**Comment by liach** [comment]
Somewhat  the cart never cares about the hardness of the block but just drop the item. I am wondering why bedrock drops itself?

**Comment by Yopu** [comment]
Reopened via https://github.com/CovertJaguar/Railcraft/commit/62b543f79eb2cbd2e6edc3f7c7998d7fbb896cc2#commitcomment-12967120
