### ISSUE TITLE
Texture Loading Improvment

### ISSUE THREAD

**Issue by Speiger** [CovertJaguar/Railcraft#683]
It is not really much an improvement but it removes the requirement of Java Reflection and has the same effect:

You are using Currently Fields to load the minimapLevels:
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/client/util/textures/TextureAtlasSheet.java#L90
But you can load it direclty from the GameSettings without the case of crashing something.
I hope that helps a little bit

**Comment by CovertJaguar** [comment]
Probably just old code here. This is much nicer indeed.
