### ISSUE TITLE
Routing Motor Switches do not detect trains, unless Loco is present at FRONT of train.

### ISSUE THREAD

**Issue by PitchBright** [CovertJaguar/Railcraft#686]
Routing Motor Switches don't detect linked carts at all (and consequently, won't send them down the correct fork of a switch track)… unless the train is LEAD by a Locomotive.

If the Locomotive is at the back of the train, the problem still exists. The detector does NOT detect the train, and route it accordingly.

My Routing Table was simply:
Ridden=False

**Comment by Forecaster** [comment]
I'm sure someone submitted something related to the "Ridden" key recently, but I can't for the life of me find it...

I think @Yopu made a change to the description or something like that.

**Comment by PitchBright** [comment]
Definitely not tied to the Ridden key issue. I've also tested it against "Type:minecraft:chest_minecart", and the results are that a single chestcart triggers the switch, but 2 linked chestcarts do not.

**Comment by PitchBright** [comment]
I can confirm that this issue exists when Railcraft is the only mod present.
Forge 1448

**Comment by PitchBright** [comment]
@Forecaster Are you talking about #648 ?

**Comment by Forecaster** [comment]
That was the one

**Comment by PitchBright** [comment]
Sept 9th commit solves Train with Back-Loco problem and triggering issue when checked against "Ridden" key. 

"Type" and "Name" keys do not work (as mentioned by CJ).

Linked carts without Locos do not trigger routing logic, however this is expected, and probably not considered a bug.

**Comment by Yopu** [comment]
The change I made was to the localization. The wrong keyword was being displayed in the help text.

**Comment by CovertJaguar** [comment]
Closed by 5877e4eaf7ba6834b48e254e99deb5341b776680

**Comment by PitchBright** [comment]
Thanks so much for doing that, CJ.
