### ISSUE TITLE
Feature Request: Smoke Particles rising from Running Locomotives

### ISSUE THREAD

**Issue by PitchBright** [CovertJaguar/Railcraft#687]
I'm sure it's been suggested before… but if it hasn't… it would be sooo cool to have bellows of smoke rising from a running loco.

**Comment by Forecaster** [comment]
That would require a lot of particles, which aren't very performance friendly.

**Comment by PitchBright** [comment]
Feature Request: Make locomotive smoke particles configgable as true/false for people who have bad computers, or people who don't like cool effects.

**Comment by CovertJaguar** [comment]
Um....they should already do this...

**Comment by PitchBright** [comment]
Yeah they do… there was a problem my resourcepack's particles.png that I didn't realize was interfering with it. That said… if the amount of particles could be configgable that'd be awesome. I would really like to have the smoke justa pumpin' out.

I'll close this as I was mistaken in thinking that smoke didn't rise from the locos at all. Sorry I forgot to come back and close, after I solved the RP issue on my end.
