### ISSUE TITLE
[Suggestion] Active personnal anchor

### ISSUE THREAD

**Issue by ExDomino** [CovertJaguar/Railcraft#690]
My idea is simple: the active personnal anchor would work only if the player is connected, but force chunkloading chunks when the player become connected, like the normal world anchor. So the actual personnal anchor would be called passive personnal anchor.

And for more protections if the player become connected and disconnected on a very short amount of time, personnal anchors could have an option in the setting to choice after how many time the player chunks are unloaded after his disconnection. Something like 1 minute per default would be fine. And it would take another 1 minute to reload the chunks again if the player become online just after the chunk was unloaded. For exemple, the player goes offline and goes online again after 1 minute and 5 secondes, so 5 secondes after the chunks was unloaded, they loads again and cause lag to the server.

**Comment by CovertJaguar** [comment]
This is hard because it requires you to create your own system for serializing the anchor data to the disk. Forge won't do it for you.
