### ISSUE TITLE
[Suggestion]--"Advanced" electric tracks

### ISSUE THREAD

**Issue by WolfAmaril** [CovertJaguar/Railcraft#698]
Possibly add electric versions of the lockdown track, boarding/disembarcation track, ect, to allow for more complex and functional electrical rail-systems.

**Comment by Vexatos** [comment]
That's what shunting wire and wire support frames are for: To bridge the gap inbetween electric tracks. while on the track the locomotive doesn't consume any energy due to not moving, so it should be fine.

**Comment by WolfAmaril** [comment]
Ahhh, this makes more sense, thanks!
