### ISSUE TITLE
Apparently EnderIO thinks your RF API is outdated

### ISSUE THREAD

**Issue by dualinfinities** [CovertJaguar/Railcraft#705]
Check it when you get time.

**Comment by LizzyTrickster** [comment]
EnderIO/RC versions? Examples of it saying so perhaps?

Just saying 'X said Y' doesn't help anything unless you can back it up

On 8 October 2015 at 21:25, dualinfinities <notifications@github.com> wrote:

> Check it when you get time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CovertJaguar/Railcraft/issues/705>.
>



-- 
Regards,
Josh Green

**Comment by dualinfinities** [comment]
Ender IO was 2.3.0.417, Railcraft was 9.7.0.0. The complaint was about Railcraft packaging RFAPI RC1.0.1 instead of RC1.0.2 and appeared at the bottom of an unrelated startup crash. Probably not that important, which is why I was saying to check it whenever is convenient rather than as soon as possible.

**Comment by CovertJaguar** [comment]
Next release with package the latest version as usual.
