### ISSUE TITLE
Little Request for IC2 Classic

### ISSUE THREAD

**Issue by Speiger** [CovertJaguar/Railcraft#707]
Your EnergyCarts from EU store the amount which is based on IC2 Exp.
Could you add a ModDetection (via modID) that adjust the EnergyStorage to the old values if IC2 Classic is loaded?

**Comment by CovertJaguar** [comment]
Tell me what values you want.

**Comment by Speiger** [comment]
The orignal ones.
BatBox: 40k Storage 32 Transfer (should be like the same but just to list them all)
MFE: 600k Storage 128 Transfer
MFSU: 10M Storage, 512 Transfer.

**Comment by liach** [comment]
MFSU cart was removed.

**Comment by Speiger** [comment]
ok did not know. But since the MFSU cart is a little bit bigger in then the MFE cart from Exp it should be enabled then... Maybe changing the CESU Cart to an MFSU cart if classic is loaded :3

**Comment by mikeloeven** [comment]
Why not just copy the NBT data directly from the power storage unit used to craft the power cart. that way it will always have the proper capacity and it will also fix the bug where crafting a full MFE/MFSU into a cart resets energy storage

**Comment by CovertJaguar** [comment]
@mikeloeven that would require custom recipe handlers to transfer the power levels over to the cart. Is it even possible to query an item for the max capacity?

**Comment by Speiger** [comment]
@CovertJaguar i am closing this because i already did the patch.
But there is 2 things i want to say:
- 1: Do you keep EU Support in Railcraft?
- 2: Yes it is possible to make that happen what he said. The Item that has to be used has to be implementing IElectricItem of any kind to make that happen. IC2C Energy Storages do not implement that in item form because it would cluster your inventory in general....

Anyway thanks for letting me add the MFSU cart when Classic is installed XD

**Comment by CovertJaguar** [comment]
EU support isn't going anywhere. The changes to the API for 1.9 were pretty minor so far.
