### ISSUE TITLE
Anchor carts load 25 chunks instead of 9.

### ISSUE THREAD

**Issue by DashFury** [CovertJaguar/Railcraft#708]
the ticket registered by anchor carts ask for 25 chunks instead of the 9 mentioned on http://railcraft.info/wiki/cart:anchor_cart.

Is it a bug, or is the wiki a little outdated on that point? I'd like to be sure before submitting any edit anywhere.

(This was tested on version 9.7.0.0 for Minecraft 1.7.10 with Forge 10.13.4.1517)

**Comment by Forecaster** [comment]
The wiki is outdated. The anchor carts loading radius was increased in a recent release.

**Comment by DashFury** [comment]
Okay. I'll update it.
