### ISSUE TITLE
Issue with Railcraft tanks

### ISSUE THREAD

**Issue by mostwanted12354** [CovertJaguar/Railcraft#711]
1.7.10 version 9.7.0.0 My steel tanks are not rendering as a multiblock structure upon login and i have to break a block and replace it to render correctly, If a picture of mod list or a screen shot of the tanks are needed please let me know.

Thank you =)

**Comment by CovertJaguar** [comment]
This is usually caused by Cauldron.

**Comment by mostwanted12354** [comment]
i do not have Cauldron installed. These are the Mods I have installed. Here is my mods list: http://pastebin.com/sA7wne3a   

It is an updated version of Bevo's Tech Pack

**Comment by ranger135xp** [comment]
Can confirm, Cauldron is not installed

**Comment by reteo** [comment]
I'm encountering this issue as well, but Ender IO is not installed on my modpack.

**Comment by CovertJaguar** [comment]
Possibly fixed by 1fa265ff0d14dab2b71f0fae47417831da4361a7
