### ISSUE TITLE
[Suggestion] Coal Coke torch recipe

### ISSUE THREAD

**Issue by Ianaver** [CovertJaguar/Railcraft#714]
Allow torch recipe: normal recipe but give 8 torches instead of 4

**Comment by CovertJaguar** [comment]
I am not opposed to this.

**Comment by Ianaver** [comment]
@CovertJaguar what do you mean?

**Comment by CovertJaguar** [comment]
Means that if someone wants to make a PR it will get accepted.

**Comment by Ianaver** [comment]
oh ok XD
