### ISSUE TITLE
Game crash (repeated) .. railcraft?

### ISSUE THREAD

**Issue by Cronosus** [CovertJaguar/Railcraft#716]
crashes beginns after disabling tracks (B:track=false) in blocks.cfg
now i enable it again and disable only tracks i dont want and crashes stops.
here my configs now:
http://pastebin.com/TaQbvNCs
http://pastebin.com/TJTGCjBG
http://pastebin.com/9xjju71D
http://pastebin.com/YzvdXVRJ

crash log: http://pastebin.com/zgDFVHpd
fml latest log: https://gist.github.com/Cronosus/b923a95491e7c9984259
latest: http://pastebin.com/s2bwELZa

after enabling again, i find in chunk i try to load notgenerated building from railcraft.. 
see image below

**Comment by CovertJaguar** [comment]
Please post the entire FML log, not the crash log. And please use [gist](https://gist.github.com/) or something... 

It would also be helpful to know if you are using any custom config settings, disabled modules etc...

**Comment by Cronosus** [comment]
hello
it think i fix it
i only disable anchors, chunkloading module and tracks
crashes beginns after disabling tracks (B:track=false) in blocks.cfg
now i enable it again and disable only tracks i dont want and crashes stops.
here my configs now:
http://pastebin.com/TaQbvNCs
http://pastebin.com/TJTGCjBG
http://pastebin.com/9xjju71D
http://pastebin.com/YzvdXVRJ

**Comment by Cronosus** [comment]
now i try again with "B:track=false" and voila, crashes again when loading new chunks.
crash log: http://pastebin.com/zgDFVHpd
fml latest log: https://gist.github.com/Cronosus/b923a95491e7c9984259
latest: http://pastebin.com/s2bwELZa

**Comment by CovertJaguar** [comment]
Ok, that's along the same lines of what I was expecting and definitely lines up with #500.

**Comment by CovertJaguar** [comment]
A possible work around would be to disable the Track Modules instead of the Track Block. I'm not sure if that will work, but it is worth a try.

**Comment by Cronosus** [comment]
i disable tracks module and crashes again.. :D

**Comment by CovertJaguar** [comment]
Well it should be fixed in 9.8 either way.
