### ISSUE TITLE
Add NEI handler for Railcraft machines.

### ISSUE THREAD

**Issue by halvors** [CovertJaguar/Railcraft#717]
Add NEI handler for Railcraft machines.

Rolling Machine, Coke Oven etc.

**Comment by Vexatos** [comment]
Doesn't one of the NEI addons already do that?

**Comment by liach** [comment]
Nope. Railcraft supports CraftGuide instead of NEI. You can use NEIPlugin for NEI integration. The actual reason that Railcraft does not support NEI was the chunk loading ability incompatibility between codechickencore and railcraft.

**Comment by CovertJaguar** [comment]
Chunk loading incompatibility? No, I just really dislike NEI's code. I tried once, it was way too much of a headache to support.
