### ISSUE TITLE
[Enhancement] RF Locomotive 

### ISSUE THREAD

**Issue by mikeloeven** [CovertJaguar/Railcraft#718]
any chance you can make a variation of the electric locomotive that runs on RF drawn from energy cells or flux capacitors ?

generally speaking IC2's EU system is kinda like the red headed stepchild of minecraft energynets and in packs with Immersive engineering or power converters everything is pretty much pure RF including the backbone networks that power any EU conversion block

**Comment by CovertJaguar** [comment]
The current Electric Locomotive can already be powered by RF (see Flux Transformer).
