### ISSUE TITLE
Emit Redstone signal for Switches

### ISSUE THREAD

**Issue by Cronosus** [CovertJaguar/Railcraft#719]
This is not issue, only request
when i create some systems, i miss on switches RS emit.

is please possible make switches (switch lever examle) emit redstone signal when activated?

thanks in advance

**Comment by CovertJaguar** [comment]
This would likely cause issues. Redstone near tracks makes things weird.

**Comment by Cronosus** [comment]
hmm.. then maybe configurable, in config, or block under switch which emit rs when switch activated...
possible?

**Comment by Aleszp** [comment]
Maybe making them interact with analog comparator would be safe way?
