### ISSUE TITLE
Compatibility Request Ic2 Classic (Speiger)

### ISSUE THREAD

**Issue by Okkasionen** [CovertJaguar/Railcraft#725]
Allow the painters to paint iron tanks, post etc.

**Comment by LuigiHutch** [comment]
Railcraft already has support for IC2 and/or IC2 Classic; the painters work on tanks and posts, and the energy carts are also added which shows that the IC2 module is loaded when IC2 classic is installed.

Tested With Railcraft_1.7.10-9.8.0.0 and IC2 Classic 1.1.2.1
