### ISSUE TITLE
[Mod Integration] Steam locomotive draws endlessly from thermal expansion portable tanks

### ISSUE THREAD

**Issue by EntropicPariah** [CovertJaguar/Railcraft#726]
If you use the thermal expansion portable tanks to fill the steam locomotive it will draw water but it continues to pull water even after it's full. I can take a resonant portable tank and use that, the steam locomotive will draw water until it's dry even if the train has no fuel. This has persisted through the last patch as well. I don't know whose end the problem is on but maybe it's easier for you to contact whoever develops thermal expansion if they are at "fault".

**Comment by EntropicPariah** [comment]
I need to update this. The steam locomotive now no longer accepts the portable tank as a water source. I accidentally had 9.7 instead of 9.8 in the mod folder. 9.7 had the endless water bug I described. In 9.8 I can't even insert the portable tank.

**Comment by CovertJaguar** [comment]
This is working as intended then. I added a limit to the size of containers that can be put in locomotives.
