### ISSUE TITLE
Elevator track powers one extra above top of redstone signal

### ISSUE THREAD

**Issue by NixillUmbreon** [CovertJaguar/Railcraft#727]
![image](https://cloud.githubusercontent.com/assets/1627071/10962182/24009f9a-8364-11e5-8e7d-87aab53e6092.png)

**Comment by AEnterprise** [comment]
elevator tracks only pass their redstone signal down if they receive one, the signal goes up 1 in this case due to how MC redstone works, power the tracks from the top and it will work

**Comment by NixillUmbreon** [comment]
Thing is I'm trying to build a multi-floor elevator that stops at multiple
spots midway up the shaft.

**Comment by Forecaster** [comment]
The track is on because the block behind it is being powered by the lever. It is not an issue with the track. You need to take this into account when using redstone.

**Comment by CovertJaguar** [comment]
Yep, this is just how levers work.
