### ISSUE TITLE
An unsupportted old RF API is installed

### ISSUE THREAD

**Issue by shader301202** [CovertJaguar/Railcraft#728]
Since the newest version of Ender IO, I have this crash:
 "EnderIO: Found the following problem(s) with your installation: "An unsupportted old RF API is installed (1.7.10R1.0.1 from Railcraft_1.7.10-9.8.0.0.jar). Ender IO needs at least 1.7.10R1.0.2 and will NOT work with older versions." This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it."

So, can You (The author of Railcraft) update the RF API?

**Comment by CovertJaguar** [comment]
Hmm...I am rather confused here. It appears that my dev environment has been set to use 1.7.10R1.0.2 since February. But you are correct, 9.8 shipped with 1.7.10R1.0.1. I have no idea how that is possible.

**Comment by CovertJaguar** [comment]
Problem located.

Despite having the latest version of the RF API in my dev env, I also had an outdated version of Buildcraft. Gradle was pulling the RF API from the Buildcraft jar instead of the source files. Updating Buildcraft has fixed the issue.

**Comment by spannerman79** [comment]
I was *just* about to report this issue.  I came across this exact error a moment ago - it wasn't Railcraft that caused the issue for my crash but I always read my crash logs fully

I've seen that approx 7 hours ago it was fixed via a commit :+1:

**Comment by t4kumi** [comment]
I also have the same problem about how astronomy space ftb resolve sorry for my english google translation thank you.	* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	EnderIO: Found the following problem(s) with your installation: "An unsupportted old RF API is installed (1.7.10R1.0.1 from Railcraft_1.7.10-9.8.0.0.jar). Ender IO needs at least 1.7.10R1.0.2 and will NOT work with older versions." This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

**Comment by spannerman79** [comment]
Wait until @CovertJaguar releases a new version @t4kumi 

I have to wait myself as I cannot use the updated GitHub commits in a private modpack due to licencing.
