### ISSUE TITLE
[Enhancement] Machine To Recharge Firestone Via Pipe Systems

### ISSUE THREAD

**Issue by mikeloeven** [CovertJaguar/Railcraft#729]
Can you please add a machine block that recharges fire stones from Fluid Pipes

I love using these to prime new boilers and i have few big reactor systems that are hooked up to magma crucibles and generate a large quantity of lava. however the only way to recharge the Firestone is to pump it into a hole using a flood gate and than it leaves me with a ton of obsidian i need to get rid of. Its just impossible to automate the recharging process of the stone and frankly i see no reason why you cant stick it in a machine and pump lava directly into the stone

Heck you could even just toss together a script to recharge it in a TE fluid transposer

**Comment by mikeloeven** [comment]
So Found another issue that supports my idea I designed a recharging system using floodgates and block breakers however to my horror after the stone was fully charged it dropped it'self and despawned. This Should NEVER HAPPEN since these items are so expensive having them auto drop themselves when charged is just a recipe for disaster but also highlights the need for a recharging station

**Comment by CovertJaguar** [comment]
There is no code that will self break the Firestone. It must be broken by an outside force.

**Comment by CovertJaguar** [comment]
The Firestone is powerful, manual intervention is required.
