### ISSUE TITLE
Diesel Locomotive?

### ISSUE THREAD

**Issue by excelcrafter** [CovertJaguar/Railcraft#733]
Maybe new locomotive which can use diesel, fuel ( buildcraft ) biodiesel ( immersive engineering )
methanol, ethanol, or some other liquid fuel?

MFE cart is just too heavy to pull with electric loco to use it like mobile battery.

I was thinking about to use tank cart filled with steam as "fuel source" for steam loco, didnt try yet :D but I will try asap, haha

**Comment by Forecaster** [comment]
Duplicate of #651
