### ISSUE TITLE
Locking Track wont change mode

### ISSUE THREAD

**Issue by dodzh** [CovertJaguar/Railcraft#734]
ive notice in some of my maps, (think is in maps where railcraft was not present when created, not sure) i cant change the mode for the locking track

it gets stuck on "Lockdown Mode"

http://i64.tinypic.com/35bftlc.jpg

**Comment by CovertJaguar** [comment]
Strange. Does it change if you log out and back in?

**Comment by dodzh** [comment]
nope, give me a day or so and ill try to find a way to reproduce this issue 100% 1/2 my maps happens 1/2 works fine
 sad thing my main server map i cant get it to work

**Comment by dodzh** [comment]
sory for the delay, with the hollydays and such been crazy, i havent been able to find a specific thing that triggers this behavior, however ive noticed that the direction how is placed sometimes fixes the issue. if palce east to west sometimes fixes.

im planning to upgrade forge version in our server but is something that might have to wait til next year since dont want to cause problems now to people playing since i dont have the time to troubleshoot much .

thank you

**Comment by CovertJaguar** [comment]
Can't duplicate, old issue.
