### ISSUE TITLE
[Enhancement] Routing table condition - Locomotive type

### ISSUE THREAD

**Issue by Cream-Tea** [CovertJaguar/Railcraft#736]
I am suggesting this enhancement to the Routing Tables. So depending on the type of Locomotive (Steam or Electric, Or even others depending if any other types will be added) will be able to activate switches etc...

**Comment by wshadow** [comment]
@Cream-Tea:  fixed by #738 ? Or is this still open?

**Comment by Cream-Tea** [comment]
This shouldn't be open, perhaps Jaguar forgot to close it.
