### ISSUE TITLE
Electric Locomotives just stop on my tracks

### ISSUE THREAD

**Issue by whitestarx0312** [CovertJaguar/Railcraft#737]
Issue:
I have an electric locomotive attached to Botania's mana cart. The locomotive pulls the cart, stops to let it refill with mana, and then carries the cart to two destination along the rail before coming back to refill. I'm not sure what is causing it, but after refilling with mana, the locomotive just stops in place. In the GUI it shows as running at full speed with full electricity. Please note that the issue occurs even when my base is completely loaded.
(Picture 1) 

My fix:
The only way for me to temporarily fix this is to shut the cart down, unlink the locomotive/mana cart, link them again, and then press running. I have placed pictures of the mana refill station (2), and the rail immediately following where it gets stuck. (3/4)

Railcraft: Railcraft_1.7.10-9.8.0.0
Botania: Botania r1.7-233
Pictures: http://imgur.com/a/e8j5M

**Comment by CovertJaguar** [comment]
Try moving the walls back?

**Comment by whitestarx0312** [comment]
I don't think it's the walls. The train got messed up and instead of the locomotive pulling the mana cart, it is just pushing it forward. The train is still connected since the train detectors are still going off, but it works fine this way, oddly enough.

http://imgur.com/9FGEwdM
(Notice the direction of the locomotive)

**Comment by CovertJaguar** [comment]
Entities are derpy sometimes, I doubt that will ever change.
