### ISSUE TITLE
The "About The Mod" page on the website links to a wikispaces wiki, demands email addresses from everyone

### ISSUE THREAD

**Issue by Moleculor** [CovertJaguar/Railcraft#739]
Pretty sure that this is something broken/incorrect. The "About The Mod" page

http://www.railcraft.info/about-the-mod/

Has a link to a supposed wiki at wikispaces.

Said wiki seems to be blank, and demands a username, password, and email from everyone who attempts to navigate it.

Pretty sure the wiki is still at http://railcraft.info/wiki/start, not http://railcraft.wikispaces.com/.

**Comment by Forecaster** [comment]
Yes, that is where the old wiki was located. It has since been replaced by the one at Railcraft.info

**Comment by CovertJaguar** [comment]
Fixed
