### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by kittykiller** [CovertJaguar/Railcraft#740]
Not sure which mod is causing it so reporting it to both mods.

http://pastebin.com/NhzpR3Qg

**Comment by Forecaster** [comment]
You should link to the other issue in one of them so both potential discussions can be found.

**Comment by kittykiller** [comment]
https://github.com/McJty/DeepResonance/issues/39

**Comment by liach** [comment]
You should close this one @kittykiller
