### ISSUE TITLE
[Enhancement] New Track so locomotives can couple automaticlly

### ISSUE THREAD

**Issue by Cream-Tea** [CovertJaguar/Railcraft#741]
The idea is that when a locomotive passes the this track it will be tagged as "ready to link up" so when it touches a cart it will automatically link up with it. This is useful for when your at the end of the line, and you want a locomotive to reverse into the cart and then link its self up. I think this track would be even more useful if it then put the locomotive into the slowest forward speed after it has linked. So this track would mainly be used as a for shunting yards. Because currently dead end sidings are quite a pain, and are pretty much useless without the ability to automatically link up and then go forward.

I already have this being worked on, and am testing it currently.

**Comment by Forecaster** [comment]
You can already do this with some problem solving using the current tracks.

**Comment by Forecaster** [comment]
Here's an example: http://imgur.com/bRolJeD
Locomotive comes in from the bottom right with no carts, gets put in reverse by top left limiter track, backs onto coupler tracks and links to carts, keeps backing onto limiter tracks and gets set to forward again, leaves with carts.

**Comment by Cream-Tea** [comment]
My idea was a similar layout to that, the problem I found was that it didn't support different cart lengths, like it could be designed for 3, but what if you had a train come in with 5? Unless that design does it perfectly?

**Comment by Forecaster** [comment]
That shouldn't matter as long as there is enough space for the length you need, in section 1 to clear the switch before the train is reversed and in section 2 for the locomotive to reach the limiter track before the back hits the buffer track.

**Comment by Forecaster** [comment]
Here, have a video:
https://youtu.be/PJ-lb1jYtXM - Railcraft [Episode 1] - Backing Up To Couple

**Comment by CovertJaguar** [comment]
The main problem with the Coupler Track is that both carts must pass over it. However, I'd be ok with a new Coupler Mode that causes any Train that runs over to couple to the next Cart is collides with. Also a new hotkey would be nice as well.

**Comment by Cream-Tea** [comment]
Yeah that's one problem I noticed, even if you did manage to set up a system you'd only be able to have a set amount of carts. And I believe it's just more complicated than it's worth, hence people just use the old loop method.

**Comment by Forecaster** [comment]
Adding a track doesn't solve the fact that you still need space for the train. There is always going to be an upper limit.

**Comment by Cream-Tea** [comment]
I think it could, I may be wrong but here's a concept video showing the new track on my test client.
https://www.youtube.com/watch?v=Zaxqc7XZ3P8

I'd say it is necessary to sort of trains that have reached the end of the line, but may need a few adjustments.

**Comment by Forecaster** [comment]
Space is still limited by the space between the switches.

Here's how to do that with current tools:
https://youtu.be/0jBVU8vOgkQ - Railcraft [Episode 2] - Turning Around
