### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bookerthegeek** [CovertJaguar/Railcraft#742]
Sorry to post this here but could not find another place for it...

Is it possible to add valid fuels to the boilers? Either through minetweaker or a configuration options I just an not seeing?

**Comment by Forecaster** [comment]
Mods can add fuels with inter mod communications, but I don't think minetweaker supports that. I assume you are talking about fluid fuels. If you're talking about solid fuels anything that has a fuel value should work.

**Comment by bookerthegeek** [comment]
Yes mostly fluid fuels. 

Hm... I don't know java so imc is out.

Is the modtweaker support on railcraft side or modtweakers? Just so I know where to ask for it.

**Comment by CovertJaguar** [comment]
ModTweaker handles all integration from their end. The tools they need to interface with Railcraft are present in the Railcraft source already.
