### ISSUE TITLE
Conflict with FMP

### ISSUE THREAD

**Issue by Carbon-Ghost** [CovertJaguar/Railcraft#743]
Hello, just wanted to notify instances closes/crashes due to null items which is caused by RC and FMP, to reproduce go in a world with both latest versions, click R in NEI or go in creative mode search function and you will crash :/

**Comment by Carbon-Ghost** [comment]
This is a major problem as it prevent users to play with RC and Project red for example without crashing :/

**Comment by liach** [comment]
Give a log please...

**Comment by Carbon-Ghost** [comment]
I would love to have given one if I could, unfortunately it's on my other pc that is elsewhere :/

Erm, try it with RC, Project Red and NEI ( optionally BC and IC2 classic ) and run it in a test world, ofc everything in latest ^-^

**Comment by CovertJaguar** [comment]
I was recently given code that I was assured would detect when this happened and tell my why. I ran said code on a clean install (Forge+Railcraft) and it found no issues. I can only assume that what you are reporting is the result of non-standard configs or a mod conflict.

**Comment by Carbon-Ghost** [comment]
From modmuss or Speiger ?

**Comment by Carbon-Ghost** [comment]
Also, do you want the pack(s) I've been experiencing the bug with, also I am back home, I can give you a crash-log if you want..

**Comment by CovertJaguar** [comment]
Speiger gave me the code. And crash logs are always recommended. Though the ones Speiger gave me basically just said "There is an ERROR! Fix it!" without actually saying where the error was.

**Comment by Carbon-Ghost** [comment]
Can I link you the modpack I use ? Yes it is WIP due to minetweaker script but ignore that, even when doing it in stable packs it still crashes.

**Comment by Landrash** [comment]
Link the modpack and your crash logs. There's more folk that can help than @CovertJaguar.

**Comment by Carbon-Ghost** [comment]
Here you go ( sorry for late response ) : https://www.dropbox.com/sh/7lst72u89ge6qlc/AAB0QclJ6vFCDmJ_pkfSZOOla?dl=1

**Comment by CovertJaguar** [comment]
Yeah, unfortunately the logs are about as helpful as I expected. I don't really have any idea what causes it.

**Comment by liach** [comment]
More likely to be related to @Speiger's null item detector, as it shows up in one crash report and two logs. The `fml-client-latest.log` is fine, though. Among four crash reports two are caused by NEI, one null item detector, one quadrum.

**Comment by Speiger** [comment]
well the problem we try to solve is rather simple: get it to work that people can you the search function in the creative tab... Ghoest Carbone came to me with the problem that it crashes when he opens the search tool tip. What i have simply done is simulate a search creative tab in secured area so nothing crashes... and these mod came out... ^^" (Sry but no idea what i have to say)

**Comment by Carbon-Ghost** [comment]
:/
