### ISSUE TITLE
Bore Speed not responding to cfg edit

### ISSUE THREAD

**Issue by EntropicPariah** [CovertJaguar/Railcraft#749]
I started incrementally increasing the bore speed and I'm not sure I ever noticed a difference when I loaded the game. This time I maxed it out at 50 and I'm lucky if the bore mines 1 block laterally every two seconds. Could something be messed up in the config, am I doing something wrong? I even broke and replaced the bore several times and it crawls along at the same speed using steel or diamond heads.

**Comment by EntropicPariah** [comment]
I started a new world, deleted the old config and let it create a new one and I still can't tell any difference between the default and 50 for the bore.

**Comment by CovertJaguar** [comment]
The code appears correct. It divides the total calculated block hardness by the multiplier from the config. The result is used to determine how long each layer takes to mine. There is however a limit to how fast the Bore can advance safely. After mining each layer it must pause and wait for any blocks to fall that might fall before moving forward, perhaps this is what you see?

**Comment by EntropicPariah** [comment]
I'm wondering if there isn't another mod in there somewhere causing a conflict also.
![mcmodslist](https://cloud.githubusercontent.com/assets/9326097/11800003/8c0e03c8-a2a6-11e5-978d-890af46b4453.JPG)
That's everything in my mods directory if anything jumps out at you.

**Comment by liach** [comment]
Try to reproduce this issue just with Railcraft.

**Comment by EntropicPariah** [comment]
I got rid of every mod except railcraft and optifine and it's still going at the same pace. Framerate is better but nothing else changed. What kind of speed should it be capable of at 50? I'm seeing 1 block of travel every 1.5-2 seconds. It does pause for a bit after digging out the blocks, that's probably cutting the speed in half. I don't know how it works, if it checks for blocks every single time it mines them out or only if it detects blocks that will fall but I had it digging just below the dirt and there was nothing there to fall.

**Comment by CovertJaguar** [comment]
It doesn't try to determine if blocks will fall (that's nearly impossible to do for mods that add more falling blocks). It just waits the necessary time regardless.
