### ISSUE TITLE
Interlock - Signal receiver Issue

### ISSUE THREAD

**Issue by SamDiego** [CovertJaguar/Railcraft#751]
Keeps happening from time to time. The signal receiver seems to not update itself when an interlock box is linked to it. The only way to fix it is changing the position of the receiver. Breaking and re-linking doesn't work. Also, doesn't seem to matter if the area is fully chunk loaded by the anchors.

This is in a multiplayer server with the modpack Infinity Evolved 2.2.2, hard mode. Railcraft 9.8.0.0
[Video 1](https://www.youtube.com/watch?v=1O-BGOc2nww)
[Video 2](https://www.youtube.com/watch?v=KT_-oFbDPXI)

**Comment by Forecaster** [comment]
Have you tried having the server restarting after connecting them? See if it fixes itself then?

**Comment by SamDiego** [comment]
Well even if a restart fixes it, it would go bad after a time anyway. The server restarts automatically every 6 hours or so I think. About the interlock having to be connected to other interlock, i did test that before setting up, and it seemed to work fine with the receiver between the 2. All tho that is only set that way in the first video, which has only 2 interlocks, the second video has the main line with many more and they are connected to each other.

**Comment by Forecaster** [comment]
I tested before I wrote that, and two interlocks separated by a receiver box were both green, which they shouldn't be able to be.

As for the issue, it would appear to be a bug, especially if it reoccurs after some time.

**Comment by SamDiego** [comment]
Yeah you are right, I tested again with more possibilities and in some cases they allow 2 trains. Fixed that section. Still, the second video, the interlocks are all connected in line, so has nothing to do with this I suspect.

**Comment by Forecaster** [comment]
It doesn't.

**Comment by SamDiego** [comment]
[Vídeo 3](https://www.youtube.com/watch?v=oAjewZg8hL4)
Well, it seems that the issue persists no matter what. I think it might have something to do with loading and unloading of chunks, since that receiver was in a border of a chunk. (I will post a screenshot soon)

Well the video extends with me testing high speed with big trains, after a lot of testing(much after the vídeo) it seems that the train explodes if no one is around it to load the chunks properly. The carts get too apart making the train longer than the 5 chunks radius of the anchor, maybe would work with more anchors but another problem that might be exploding the train is entities getting in the carts. The locomotives only protect the front of it but as the carts get very separated, some zombie or chicken can cross the track "in" between the train and cause it to explode. Maybe one way to 'fix' it would be making any linked cart to a locomotive indestructible as the locomotive is. Well anyway, I wanted to add that, maybe i'm forcing the limits of the mod with this xD but since I never saw anyone do it, I had to try.   I'm having lots of fun doing it, I hope maybe CovertJaguar can improve this but its ok if not, i know very very few people do it. For now I'm moving to reinforced tracks. (just so you guys know, english is not my first language so, sorry for any weird speaking ^_^')

**Comment by CovertJaguar** [comment]
That's a crazy long train!

I'll look at making explosions not happen for carts in the same train. But that won't help if the train become disconnected.
