### ISSUE TITLE
Passive Anchor NullPointerException 

### ISSUE THREAD

**Issue by Yopu** [CovertJaguar/Railcraft#753]
Crash dump: https://gist.github.com/Yopu/ba2a71c3b265f571a441

SSP crash, unknown if it affects SMP.
~~Possible factor: playing with anchor fuel disabled.~~
~~Edit: fuel being disabled appears to be the deciding factor.~~
Edit: it was because it wasn't running otherwise. Doh!

Steps to reproduce:
1. Load world with passive anchor placed.
2. Save and quit to main menu.
3. Reload world without restarting Minecraft.

**Comment by Yopu** [comment]
Found the issue. 
Forge appears to not check when you force a chunk if it is already in the forced chunk map.
Solution is checking before we request the unforce operation.

**Comment by CovertJaguar** [comment]
I swear it used too...
