### ISSUE TITLE
Exception in server tick loop caused by world anchor

### ISSUE THREAD

**Issue by vagaprime** [CovertJaguar/Railcraft#754]
Received a crash log through Yampst about a world anchor crash

http://pastebin.com/ufDALjW9

I am not sure what caused it due to not receiving any feed back from the user about what they where doing at the times of the crash.

**Comment by Yopu** [comment]
Fixed via:
https://github.com/CovertJaguar/Railcraft/issues/753

**Comment by vagaprime** [comment]
Crash appears to till be present in 9.10.0 recieved a new crash report through yampst on 4/14/16

https://github.com/MageTech-gate/Release/issues/17

**Comment by CovertJaguar** [comment]
@vagaprime You are not using 9.10, you are using 9.9.

**Comment by vagaprime** [comment]
So I am. Though I had updated it before I pushed that release.
