### ISSUE TITLE
Traveling Trunk and H.S. Track

### ISSUE THREAD

**Issue by Yopu** [CovertJaguar/Railcraft#756]
For the unaware, Thaumcraft adds a traveling trunk entity. This entity follows its owner and has an inventory that its owner can make use of. It also possesses the ability to teleport to a position near the player if they get too far apart. It is akin to mods that add backpacks or storage bags.

As it currently stands, it is impossible to utilize H.S. track while a traveling trunk is following you. There is a large danger that the trunk will teleport into your path causing an explosion and almost certain death.

I propose an exception is made for the traveling trunk when utilizing H.S. track. Or alternatively a config option which would allow the exception of pre-selected entities.

**Comment by Landrash** [comment]
Shouldn't this be solved on Thaumcraft side?  
Blacklisting which this essentially would be is rarely a good solution in any situation since it quickly gets very hard to manage these lists.

**Comment by Yopu** [comment]
In theory yes, however I assume that an IMC solution would be a much more difficult fix. Not to mention that I assume Thaumcraft won't be updated for 1.7.10 again.

**Comment by XFactHD** [comment]
Thaumcraft for 1.7.10 is not developed anymore, even the repository is gone.

**Comment by Yopu** [comment]
@XFactHD I figured as much. This would also enable the end user or ops to add other entities of their choosing. I suppose adding IMC at the same time wouldn't be too difficult.

**Comment by XFactHD** [comment]
Either IMC or some sort of JSON config.

**Comment by Yopu** [comment]
I have some time off from school. I can work on this provided @CovertJaguar has no objections.
