### ISSUE TITLE
Disabled Rolling Machine's recipes aren't transferring to the crafting table

### ISSUE THREAD

**Issue by PikadudeNo1** [CovertJaguar/Railcraft#758]
I have machine.alpha.rolling.machine set to false. I see from reading the code that in this case, its crafting recipes should become usable on the crafting table, but for whatever reason this isn't happening.

I have a few other config changes, so let me know if you can't reproduce it and I'll see what else is needed to trigger the bug.

**Comment by Yopu** [comment]
Unable to reproduce in my dev environment. Post your config file please.

**Comment by PikadudeNo1** [comment]
Sorry for the delay; here are my config files.

[railcraft.cfg.txt](https://github.com/CovertJaguar/Railcraft/files/87231/railcraft.cfg.txt)
[blocks.cfg.txt](https://github.com/CovertJaguar/Railcraft/files/87229/blocks.cfg.txt)
[items.cfg.txt](https://github.com/CovertJaguar/Railcraft/files/87230/items.cfg.txt)
[modules.cfg.txt](https://github.com/CovertJaguar/Railcraft/files/87232/modules.cfg.txt)

**Comment by CovertJaguar** [comment]
I suspect some kind of mod interaction is interfering.
