### ISSUE TITLE
MC CRITICAL CRASH

### ISSUE THREAD

**Issue by keomate88** [CovertJaguar/Railcraft#763]
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 05/01/16 17.32
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.google.common.collect.LinkedHashMultimap.create(LinkedHashMultimap.java:119)
	at net.minecraftforge.common.ForgeChunkManager.unforceChunk(ForgeChunkManager.java:783)
	at mods.railcraft.common.blocks.machine.alpha.TileAnchorWorld.setTicket(TileAnchorWorld.java:370)
	at mods.railcraft.common.blocks.machine.alpha.TileAnchorWorld.forceChunkLoading(TileAnchorWorld.java:385)
	at mods.railcraft.common.util.misc.ChunkManager.ticketsLoaded(ChunkManager.java:174)
	at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:523)
	at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:64)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_23_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 356205752 bytes (339 MB) / 1774714880 bytes (1692 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -Xms256M -Xmx2048M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 76, tallocated: 62
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 118 mods loaded, 117 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAA	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) 
	UCHIJAAAAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAAAAA	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
	UCHIJAAAAAAA	WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar) 
	UCHIJAAAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAAAAA	AccidentallyCircumstantialEvents{1.10.0} [Accidentally Circumstantial Events] (accidentallycircumstantialevents-1.10.0.jar) 
	UCHIJAAAAAAA	AgriCraft{1.7.10-1.4.5} [AgriCraft] (AgriCraft-1.7.10-1.4.5.jar) 
	UCHIJAAAAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAAAAA	arcanearteries{5} [Arcane Arteries] (ArcaneArteries0.7.2.jar) 
	UCHIJAAAAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAAAAA	Automagy{0.27} [Automagy] (Automagy-1.7.10-0.27.jar) 
	UCHIJAAAAAAA	bagginses{2.1.1} [Bagginses] (Bagginses-2.1.1.jar) 
	UCHIJAAAAAAA	BiblioCraft{1.11.3} [BiblioCraft] (BiblioCraft[v1.11.3][MC1.7.10].jar) 
	UCHIJAAAAAAA	ExtrabiomesXL{3.16.1} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.1.jar) 
	UCHIJAAAAAAA	BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition] (BiblioWoods[ExtraBiomesXL][v1.4].jar) 
	UCHIJAAAAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.1a2.jar) 
	UCHIJAAAAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAAAAA	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
	UCHIJAAAAAAA	Forestry{3.6.6.24} [Forestry for Minecraft] (forestry_1.7.10-3.6.6.24.jar) 
	UCHIJAAAAAAA	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
	UCHIJAAAAAAA	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHIJAAAAAAA	BinnieCore{2.0-pre14} [Binnie Core] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAAAAA	Botany{2.0-pre14} [Botany] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAAAAA	ExtraBees{2.0-pre14} [Extra Bees] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAAAAA	ExtraTrees{2.0-pre14} [Extra Trees] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAAAAA	Genetics{2.0-pre14} [Genetics] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAAAAA	BiomeTweaker{2.0.161} [BiomeTweaker] (BiomeTweaker-1.7.10-2.0.161.jar) 
	UCHIJAAAAAAA	BlockProperties{0.1.2} [Block Properties] (BlockProperties-1.7.10-0.1.2.jar) 
	UCHIJAAAAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-13.jar) 
	UCHIJAAAAAAA	Botania{r1.8-245} [Botania] (Botania r1.8-245.jar) 
	UCHIJAAAAAAA	ForbiddenMagic{1.7.10-0.572} [Forbidden Magic] (Forbidden Magic-1.7.10-0.572.jar) 
	UCHIJAAAAAAA	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UCHIJAAAAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAAAAA	BloodArsenal{1.2-3} [Blood Arsenal] (BloodArsenal-1.7.10-1.2-3.jar) 
	UCHIJAAAAAAA	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
	UCHIJAAAAAAA	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
	UCHIJAAAAAAA	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
	UCHIJAAAAAAA	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
	UCHIJAAAAAAA	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
	UCHIJAAAAAAA	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
	UCHIJAAAAAAA	BuildCraft|Compat{7.1.3} [BuildCraft Compat] (buildcraft-compat-7.1.3.jar) 
	UCHIJAAAAAAA	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCHIJAAAAAAA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAAAAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJAAAAAAA	CarpentersBlocks{3.3.8_dev_r6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8_dev_r6 - MC 1.7.10.jar) 
	UCHIJAAAAAAA	ChiselFacades{1.7.10-2.10-cricket} [Chisel Facades] (ChiselFacades-1.7.10-2.10-cricket.jar) 
	UCHIJAAAAAAA	climatecontrol{0.4} [Climate Control] (ClimateControl-0.4.beta28.jar) 
	UCHIJAAAAAAA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCHIJAAAAAAA	companions{1.7.10-0.1.2} [Companions] (companions-1.2.jar) 
	UCHIJAAAAAAA	craftingtweaks{1.0.57} [Crafting Tweaks] (craftingtweaks-mc1.7.10-1.0.57.jar) 
	UCHIJAAAAAAA	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCHIJAAAAAAA	CreeperCollateral{1.7.10R1.0.0B3} [CreeperCollateral] (CreeperCollateral-[1.7.10]1.0.0B3-6.jar) 
	UCHIJAAAAAAA	CustomMainMenu{1.1} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.1.jar) 
	UCHIJAAAAAAA	Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJAAAAAAA	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJAAAAAAA	endercore{1.7.10-0.0.1.10_alpha} [EnderCore] (EnderCore-1.7.10-0.0.1.10_alpha.jar) 
	UCHIJAAAAAAA	EnderZoo{1.7.10-1.0.15.32} [Ender Zoo] (EnderZoo-1.7.10-1.0.15.32.jar) 
	UCHIJAAAAAAA	EnhancedInventories{1.7.10-1.1.8} [Enhanced Inventories] (EnhancedInventories-1.7.10-1.1.8.jar) 
	UCHIJAAAAAAA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHIJAAAAAAA	GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAAAAA	GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAAAAA	GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAAAAA	GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAAAAA	GraveStone{2.15.2} [GraveStone] (GraveStone-2.15.2.jar) 
	UCHIJAAAAAAA	HardcoreQuesting{4.4.4} [Hardcore Questing Mode] (HQM-The Journey-4.4.4.jar) 
	UCHIJAAAAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJAAAAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAAAAA	launchgui{1.0.0} [LaunchGUI] (LaunchGui-1.7.10-1.5-8-client.jar) 
	UCHIJAAAAAAA	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1.jar) 
	UCHIJAAAAAAA	MagicBees{1.7.10-2.3.6} [Magic Bees] (magicbees-1.7.10-2.3.6.jar) 
	UCHIJAAAAAAA	Mariculture{1.7.10-1.2.4.2a} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJAAAAAAA	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJAAAAAAA	Mekanism{8.1.7} [Mekanism] (Mekanism-1.7.10-8.1.7.252.jar) 
	UCHIJAAAAAAA	MekanismGenerators{8.1.7} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.7.252.jar) 
	UCHIJAAAAAAA	millenaire{6.0.0} [Millénaire] (millenaire-6.0.0.jar) 
	UCHIJAAAAAAA	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) 
	UCHIJAAAAAAA	MobProperties{0.3.3} [Mob Properties] (MobProperties-1.7.10-0.3.4.jar) 
	UCHIJAAAAAAA	modtweaker2{0.9.4} [Mod Tweaker 2] (ModTweaker2-0.9.4.jar) 
	UCHIJAAAAAAA	NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAAAAA	NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAAAAA	NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAAAAA	NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAAAAA	NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAAAAA	NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAAAAA	NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAAAAA	neiintegration{1.0.12} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.12.jar) 
	UCHIJAAAAAAA	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCHIJAAAAAAA	Quadrum{1.2.0} [Quadrum] (Quadrum-1.7.10-1.2.0.B13-universal.jar) 
	UCHIJAAAAAAA	ResourceLoader{1.0} [Resource Loader] (ResourceLoader-1.0.jar) 
	UCHIJAAAAAAA	AS_Ruins{14.6} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCHIJAAAAAAA	Sanguimancy{1.7.10-1.1.9-32} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-32.jar) 
	UCHIJAAAAAAA	SimilsaxTranstructors{1.7.10.15} [Similsax Transtructors] (SimilsaxTranstructors-1.7.10.15.jar) 
	UCHIJAAAAAAA	StorageDrawers{1.7.10-1.7.5} [Storage Drawers] (StorageDrawers-1.7.10-1.7.5.jar) 
	UCHIJAAAAAAA	StorageDrawersForestry{1.7.10-1.1.0} [Storage Drawers: Forestry Pack] (StorageDrawers-Forestry-1.7.10-1.1.0.jar) 
	UCHIJAAAAAAA	StorageDrawersMisc{1.7.10-1.1.0} [Storage Drawers: Misc Pack] (StorageDrawers-Misc-1.7.10-1.1.0.jar) 
	UCHIJAAAAAAA	StorageDrawersNatura{1.7.10-1.1.0} [Storage Drawers: Natura Pack] (StorageDrawers-Natura-1.7.10-1.1.0.jar) 
	UCHIJAAAAAAA	supercraftingframe{1.7.10.3} [Super Crafting Frame] (supercraftingframe-1.7.10.3.jar) 
	UCHIJAAAAAAA	tcnodetracker{1.1.2} [TC Node Tracker] (tcnodetracker-1.7.10-1.1.2.jar) 
	UCHIJAAAAAAA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAAAAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJAAAAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJAAAAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAAAAA	wailaplugins{MC1.7.10-0.1.2-19} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.1.2-19.jar) 
	UCHIJAAAAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAAAAA	WitchingGadgets{1.1.10} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.10.jar) 
	UCHIJAAAAAAA	XaeroMinimap{1.7.3} [Xaero's Minimap] (xaeros_minimap_v1.7.3_Forge_1.7.10.jar) 
	UCHIJAAAAAAA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAAAAA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	UCHIJAAAAAAA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UD	BiomeTweakerCore{2.0.161} [BiomeTweaker Core] (minecraft.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Mantle Environment: Environment healthy.
	CoFHCore: -[1.7.10]3.0.3-303
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.0-12
	Forestry : Info: The following plugins have been disabled in the config: propolis.pipe
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Yopu** [comment]
See https://github.com/CovertJaguar/Railcraft/issues/753
