### ISSUE TITLE
Compatibility - should Railcraft engines implement IEnergyProvider in the RF API?

### ISSUE THREAD

**Issue by radfast** [CovertJaguar/Railcraft#765]
I notice that the [engines](https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/blocks/machine/beta/TileEngine.java) (e.g. Steam Engine) implement **cofh.api.energy.IEnergyConnection** but not **cofh.api.energy.IEnergyProvider**.

I think they should implement IEnergyProvider, because they do output energy.

The failure to implement IEnergyProvider causes a minor issue in Galacticraft (up to versions 3.0.12.408).  The issue is that Galacticraft's aluminium wires will not render as connected to Railcraft engines, even though energy is in fact transferred into the wires.  It's because the GC wires seek specifically for an IEnergyReceiver or an IEnergyProvider to connect to.

Although the issue is now [worked around](https://github.com/micdoodle8/Galacticraft/commit/8726ea61eb5bb644cd3b3c367a2ec8a392f723d2) in future versions of Galacticraft, it would be helpful if Railcraft would implement IEnergyProvider still - this will aid compatibility for players/modpacks who choose to use future versions of Railcraft with pre-latest versions of Galacticraft.

**Comment by VirusSE** [comment]
This patch should fix it. Unfortunately i'll get a Field not found exception, if i run build 408 of GalaxyCraft (one before work around). Maybe someone can review it and do a test run.
[patch.txt](https://github.com/CovertJaguar/Railcraft/files/134768/patch.txt)

**Comment by CovertJaguar** [comment]
IEnergyProvider allows other blocks to muck around with the internal power storage of the provider. This isn't how Engines work.
