### ISSUE TITLE
Forestry WaxCapsules and Tin Cans cannot be filled  with Railcraft creosote oil in any way

### ISSUE THREAD

**Issue by damnedsky** [CovertJaguar/Railcraft#766]
Railcraft_1.7.10-9.8.0.0
forestry_1.7.10-4.2.4.52
What I tried so far:
- right clicking with a stack of capsules on a Coke Oven
- placed a stack then a single capsule in the Coke Oven slot
- filled a Forestry Bottler with creosote and tried the capsules there

Sooooo... all the Forestry capsules are called "Forestry:waxCapsule<LiquidName>" while the Railcraft one is "Railcraft:fluid.creosote.wax". Buckets and bottles filled with creosote work fine with all Forestry machines. Capsules do not. I am also reporting this on the Forestry GitHub.

**Comment by O13SC3N3** [comment]
I can verify this, 9.8 it worked fine, once 9.9 or 9.10 it doesnt work.

Forestry versions 4 to 4.2.11.59 all worked with Railcraft 9.8, there a config fix or script fix we can place?

**Comment by Generalcamo** [comment]
Will be fixed when Railcraft switches to Universal Fluids, per #996

**Comment by liach** [comment]
![2017-03-13_16 29 43](https://cloud.githubusercontent.com/assets/7806504/23879456/6a1bea08-080a-11e7-9882-9ada144aed59.png)
This is the way you are supposed to use it.
