### ISSUE TITLE
Branch Version Release Request - 1.8.9

### ISSUE THREAD

**Issue by DPxKnightxZero** [CovertJaguar/Railcraft#767]
I have been using this mod since 1.6.4 can you do me a huge favor and create a 1.8.9 release?

**Comment by liach** [comment]
Somehow @CovertJaguar is not active recently- pinging @Yopu for help.

**Comment by Yopu** [comment]
@CovertJaguar is, indeed, a bit elusive as of late. I, on the other hand, am somewhat active yet busy starting a new semester. This is a huge undertaking and there is no current ETA on when it would be completed.

**Comment by Yopu** [comment]
It is also worth mentioning that API upgrades may possibly also slow the upgrade.

**Comment by DPxKnightxZero** [comment]
I understand please just don't forget but life comes first :P

**Comment by Yopu** [comment]
I've started some of the monkey work. Converting to BlockPos and EnumFacing. I fear that the rendering will be beyond me though.

**Comment by Yopu** [comment]
Their numbers keep multiplying. 

![capture](https://cloud.githubusercontent.com/assets/3004433/12338330/0e464852-badd-11e5-85f4-510e830dd5ea.PNG)

**Comment by CovertJaguar** [comment]
Yeah, rendering will be fun, I'll probably have to start with the simpler blocks and work my way up to complex stuff like signals.

**Comment by liach** [comment]
Glad to see CJ here. It looks like that @Yopu has done a lot of work already. API needs an update also.

**Comment by Yopu** [comment]
I did a fair amount of grunt work over this last week. Schoolwork is picking up for the time being, thus I will try and find more time to contribute but I can't make any promises.
Progress so far is in [branch update-1.8.9](https://github.com/CovertJaguar/Railcraft/tree/update-1.8.9).

**Comment by CovertJaguar** [comment]
As the 1.8 branch is being actively developed, and this issue doesn't really add much beyond the obvious, I'm going to close it.

**Comment by rcistano** [comment]
Cant wait for an Alpha/Beta. I am definitely going to have this in my pack.
