### ISSUE TITLE
Coal Coke-{suggestion-ish}

### ISSUE THREAD

**Issue by EndermanParty** [CovertJaguar/Railcraft#770]
The blast furnace does not accept Coal Coke from Immersive Engineering. IE 1.7 Railcraft 9.8.0.0

**Comment by CovertJaguar** [comment]
The ability to add new fuels to the Blast Furnace was intentionally left out of the API. It's intended to be rather particular.

**Comment by bookerthegeek** [comment]
Understandable that you would want it balanced against your mod.

Other mods also add gated fuels. Would it be possible to add an imc ability for those mod authors to add their fuels also to your blast furnace, would you be willing to add them as a compatible option, or are both of those out of the question?

I know that their have been a rash of issues both here and over at IE about their coal coke not working, but other mods also add a refined version of coal.

**Comment by Forecaster** [comment]
Describe how it is made, how long it takes (approx), it's fuel value in a furnace if applicable and any others details that could be relevant. We'll need to know how it compares to Railcraft coal coke before deciding whether it should be added or not.

**Comment by bookerthegeek** [comment]
Ok. I'll get you that after I get off of work.

**Comment by EndermanParty** [comment]
You see the entire reason why I wanted to use your blast furnace for steel was due to IE making so many frustrating changes. Their "Improved" blast furnace didn't work whatsoever when I tried using it last time, Ill need to test it again but I don't think it will work still. I was thinking about adding mekanism since it makes steel crafting so much easier but I didn't want to add it since I had railcraft. Although I deleted that world soooo, If you want you can delete this issue unless @bookerthegeek wants to continue it. I essentially wanted this as a "quality of life" change but it isn't necessary anymore.

**Comment by Forecaster** [comment]
Nobody's provided the information we asked for yet.

**Comment by Cracks777** [comment]
Use minetweaker and modtweaker.

**Comment by bookerthegeek** [comment]
Sorry, life happened. If it is still interested I'll post my findings.

**Comment by CovertJaguar** [comment]
More information is always good.

**Comment by vagaprime** [comment]
The IE coal coke shares the same production method as the RC coal coke as well as the same burn time.

**Comment by CovertJaguar** [comment]
@vagaprime production time?

**Comment by Forecaster** [comment]
Out of curiosity, why do you want to use IE coal coke with Railcrafts blast furnace? Last time I checked IE had its own?

**Comment by vagaprime** [comment]
I will have to time the amount of time it takes to convert coal into coal coke.

**Comment by bookerthegeek** [comment]
50% of yours

**Comment by CovertJaguar** [comment]
If the production time is 50% less, then no, I will not be adding as a Blast Furnace fuel for sure.

**Comment by vagaprime** [comment]
Bookerthegeek is wrong about the time. Both IE and RC will turn coal into coal coke in 1800 ticks.

**Comment by bookerthegeek** [comment]
Hm... that must be a recent change. I'll test tonight on the latest.

**Comment by vagaprime** [comment]
have the latest release of both IE and RC in the dev build for my pack and NEI shows a total time of 1800 ticks for both coke ovens to turn coal into coal coke.

**Comment by CovertJaguar** [comment]
Well then, I'm not exactly sure the best way to add support, but since they do appear to be truly identical I have no problem with it being added.

**Comment by vagaprime** [comment]
Might I suggest talking to blu about adding an ore dic for coal coke that both RC and IE could use?

**Comment by CovertJaguar** [comment]
I'm not sure I'd want to open it up with an Ore Dict tag.
