### ISSUE TITLE
Linked carts get unlinked after traveled to a far away place

### ISSUE THREAD

**Issue by xingrz** [CovertJaguar/Railcraft#772]
Here's my situation:

I created a very long bridge with Reinforced Booster Track above the sea connecting two island.
How far between the two island? If you fly from one to another, the system lazily load and render its appearance.

I linked 4 Minecarts into a train.

If I jump into the train and push it through the bridge to another island, every thing works properly.

If just push the train without getting on it, letting it travel to the other island, its first cart gets unlinked somewhere during the journey.

Seems due to the world is not loaded while it traveling?

**Comment by liach** [comment]
Try with an admin anchor cart linked with the other carts.

**Comment by xingrz** [comment]
@liach oh I see, thank you!
