### ISSUE TITLE
Railcraft has Dependency on BC brought to surface by Electricraft.

### ISSUE THREAD

**Issue by bookerthegeek** [CovertJaguar/Railcraft#774]
[fml-client-lates.log](https://gist.github.com/bookerthegeek/8683173f552230266bb4)
[Crash Report](https://gist.github.com/bookerthegeek/ceb61a5e7c3d92e68f4a)

It seems that there is an issue with Railcraft and ElectriCraft. As stated in the post [HERE](https://github.com/CovertJaguar/Railcraft/issues/622#issuecomment-115155174) that you would need full logs to see what is happening, I have linked them above. This is the smallest set of mods I can get to have both Railcraft & ElectriCraft.

Relevant Parts of the Crash Report: (Truncated) 
````
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mods/railcraft/common/items/ItemCrowbar
Caused by: java.lang.NoClassDefFoundError: mods/railcraft/common/items/ItemCrowbar
Caused by: java.lang.ClassNotFoundException: mods.railcraft.common.items.ItemCrowbar
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/tools/IToolWrench
Caused by: java.lang.ClassNotFoundException: buildcraft.api.tools.IToolWrench
````
Mod List
````
Forge 10.13.4.1614 
DragonAPI 1.7.10 V10d.jar
RotaryCraft 1.7.10 V10d.jar
ElectriCraft 1.7.10 V10b.jar
Railcraft 1.7.10-9.8.0.0.jar
````
If any other information is needed I'll be more then happy to provide asap. I just need to know what is needed.

Thanks and have a wonderful day.

Cross posted [HERE](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/622)

Related Issues:
 - Railcraft [#622](https://github.com/CovertJaguar/Railcraft/issues/622)
 - Reika Mods [#110](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/110)

**Comment by Vexatos** [comment]
But... Railcraft is shipping the BuildCraft Tools API. [It is even the one actually loaded](https://gist.github.com/bookerthegeek/8683173f552230266bb4#file-fml-client-latest-L467)...

**Comment by ReikaKalseki** [comment]
Welcome to classloading issues...

**Comment by Vexatos** [comment]
So... the only coremods inside that could mess up are DragonAPI and RotaryCraft...

@ReikaKalseki Is either of those mods shipping the BuildCraft tools API or parts of it?

**Comment by bookerthegeek** [comment]
````
Buildcraft 7.1.14
DragonAPI 1.7.10 V10d
ElectriCraft 1.7.10 V10b
Railcraft_1.7.10-9.8.0.0
RotaryCraft 1.7.10 V10d
````

Modpack loads up as expected with no glaring issues.

**Comment by Vexatos** [comment]
@bookerthegeek As expected. Thanks for the investigation.

**Comment by bookerthegeek** [comment]
@Vexatos May I ask what the resolution is? I am curious as to what the original issue is in a very non-finger-pointy kind of way. Mainly so I can figure out how to solve it easier next time.

**Comment by Vexatos** [comment]
@bookerthegeek Usually FML tells you in the log which .jar file an API is loaded from if multiple jar files are shipping it. Railcraft crashes because it cannot find the Wrench API class. FML, however, says that it did load the API from the Railcraft file which most definitely contains the Wrench class unless someone tampered with it. Adding BuildCraft fixes the issue because it guarantees the API is there in its entirety.

Would you mind checking if the file `buildcraft/api/tools/IToolWrench` actually exists in the Railcraft jar file?

**Comment by bookerthegeek** [comment]
This? If so then Yes. If you mean something else then I have no idea.

![IToolWrench.class](http://goo.gl/nsid6I)

**Comment by Vexatos** [comment]
@bookerthegeek So the class was there, supposedly detected by FML... But couldn't be loaded. This is a really strange issue.

**Comment by bookerthegeek** [comment]
@Vexatos Can you reproduce in your environment?

Can you push a version with more logging options I could run for you?

**Comment by ReikaKalseki** [comment]
The problem is an FML classloading error, and there is [no fix outside of simply copying the classes into the DragonAPI jar](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/622#issuecomment-183309395).
