### ISSUE TITLE
Switch Levers causing massive chunk updates and FPS drop

### ISSUE THREAD

**Issue by SirSmashy** [CovertJaguar/Railcraft#775]
Hey there,
I stumbled across this glitch in my 1.7.10 world running Railcraft_1.7.10-9.8.0.0:

### Description
When Switch Levers are placed adjacent to two Switch Tracks, depending on the tracks' orientation, the number of chunk updates increases drastically and permanently (until the setup is modified), eventually crippling performance and FPS in more busy worlds.

### Test Setup
Having the tracks in this orientation is fine, there are 0 chunk updates as this is a clean superflat test world with only Railcraft installed.
![2016-02-16_18 40 34](https://cloud.githubusercontent.com/assets/5280384/13085030/8beeeb7e-d4dc-11e5-8c48-19fe55e20669.png)

### The Issue
This screenshot shows the Switch Tracks in their problematic orientation. There are now 40 chunk updates. There is no FPS penalty yet since there is nothing else going on in the world. My modded Survival World drops from 120 to ~10 FPS from just a single problematic junction.
![2016-02-16_18 40 39](https://cloud.githubusercontent.com/assets/5280384/13085037/90985642-d4dc-11e5-9ccf-d906d2b02f91.png)

### Additional Information
Each copy of the "broken" setup adds another (exaclty!) 20 or 40 chunk updates. Having more than one setup of this type in a chunk only adds the penalty once (highest one). This problem also occurs when using the Switch Motors/Routing Switch Motor instead. Different types of Switch Track as well as the Wye Tracks are also affected.

I assume the Levers are trying to render the red/white indicators in two conflicting orientations based on the adjacent Switch Tracks and this is causing some major confusion.

For now I have worked around this issue by avoiding this particular setup of tracks. Of course I would still appreciate a fix in a future version.

Cheers

**Comment by CovertJaguar** [comment]
Successfully reproduced in my dev env.
