### ISSUE TITLE
Problem with boilers and liquids in stackable containers

### ISSUE THREAD

**Issue by n65** [CovertJaguar/Railcraft#776]
I noticed something strange, when i right-click on a boiler or steam locomotive with stacked Forestry capsules/cans or IC2 cells with water, they consume all stack at once, resulting in 1000 mB at internal tank, like i poured 1 bucket in it. Same thing with liquid boiler and fuel. Is that a bug?

**Comment by CovertJaguar** [comment]
Confirmed.
