### ISSUE TITLE
Turn aspect lights into TESRs

### ISSUE THREAD

**Issue by Vexatos** [CovertJaguar/Railcraft#777]
Currently, the aspect light is part of the ISBRH which makes blinking aspects cause a chunk render update every 16 ticks. This could be massively optimized by exporting the lights into a TESR (which should probably all extend `RenderTESRSignals` for the goggles to still work).

**Comment by xingrz** [comment]
Yes, I just found what make my game very slow are blinking red lights…

**Comment by CovertJaguar** [comment]
Closed by c1930c67d1844afca24a8e6b4f743f497fb6dc48
