### ISSUE TITLE
ProjectRed Framed Insulated Wire could not be connected to the bottom side of a Detector Block

### ISSUE THREAD

**Issue by xingrz** [CovertJaguar/Railcraft#778]
<img width="1552" alt="2016-03-04 17 59 45" src="https://cloud.githubusercontent.com/assets/288288/13524381/d733619e-e235-11e5-9607-93b95b133921.png">

**Comment by xingrz** [comment]
Oops, forgot to provide versions:

- Minecraft 1.7.10
- Railcraft_1.7.10-9.8.0.0
- ProjectRed-1.7.10-4.7.0pre12.95

**Comment by Forecaster** [comment]
Does this also apply to vanilla redstone?

**Comment by xingrz** [comment]
<img width="1552" alt="2016-03-09 18 20 40" src="https://cloud.githubusercontent.com/assets/288288/13632246/aa03d36a-e623-11e5-9b4b-30211b4912c9.png">

- vanilla Redstone: works
- PR Framed Red Alloy Wire / Insulated Wire: not works

**Comment by Forecaster** [comment]
Now try forcing the framed wire to attach to the detector using normal alloy wire?

**Comment by xingrz** [comment]
<img width="1552" alt="2016-03-10 09 04 16" src="https://cloud.githubusercontent.com/assets/288288/13656215/01a94506-e6a0-11e5-984b-96b907c4f7c7.png">

@Forecaster 
Works this way
So I've edited the title to describe this issue more exactly.

(updated to 9.9.0.0)
