### ISSUE TITLE
Tin plate can't make

### ISSUE THREAD

**Issue by siguma0013** [CovertJaguar/Railcraft#781]
Tin plate can't make

forge 10.13.4.1614
railcraft 9.9.0.0
buildcraft 7.1.14

**Comment by Forecaster** [comment]
Uhh. Not enough information. Try again.

**Comment by siguma0013** [comment]
Tin plate can make at Railcraft 9.8.0.0 
But I can't make tin plate at RailCraft 9.9.0.0

**Comment by CovertJaguar** [comment]
Screenshots please.

**Comment by Kupferdrache** [comment]
Does this  fix the tin alloy issue in GT5U as well?
