### ISSUE TITLE
locking track don't work 

### ISSUE THREAD

**Issue by Jamie787** [CovertJaguar/Railcraft#788]
when i right click a locking track with a crowbar it changes it to train lockdown mode and when i shift right click it turn into a train boarding track and nothing else.

**Comment by Forecaster** [comment]
Too little information. What version of Railcraft, other mods present, cauldron or similar installed, forge version.

**Comment by Jamie787** [comment]
mod list 
Baubles-1.7.10-1.0.1.10
CodeChickenLib-1.7.10-1.1.3.138-universal
commons-codec-1.9
commons-compress-1.8.1
ForgeMultipart-1.7.10-1.2.0.345-universal
[1-7-10]_Lucky_Block_v5-1-0
1.7.10-MB_Battlegear2-Bullseye-1.0.8.2
Anti-Gravity-Mod-1.7.10
appliedenergistics2-rv2-stable-10
ArchimedesShips-1.7.1
autopackager-1.5.5
Bagginses-2.1.1
bdlib-1.9.3.107-mc1.7.10
BetterFps-1.0.1
BiblioCraft[v1.11.4][MC1.7.10]
BloodMagic-1.7.10-1.3.3-17
BluePower-1.7.10-0.2.962-universal
Cars_and_Drives_Mod_V-1.0.9.1
ChickenChunks-1.7.10-1.3.4.19-universal
CodeChickenCore-1.7.10-1.0.7.47-universal
CoFHCore-[1.7.10]3.0.3-303
CustomMainMenu-MC1.7.10-1.9.2
CustomNPCs_1.7.10c
D3Core-1.7.10-1.1.0.31
darkcore-0.3-86
EnderIO-1.7.10-2.2.8.381
EnderStorage-1.7.10-1.4.7.37-universal
ExtraCells-1.7.10-2.3.8b185
extrautilities-1.2.12
fastcraft-1.21
FlatSigns-1.7.10-universal-2.1.0.19
FTBLib-1.7.10-1.0.11
FTBUtilities-1.7.10-1.0.11
GreenThumb-1.7.10-1.1.0.8
INpureCore-[1.7.10]1.0.0B9-62
InventoryTweaks-1.59-dev-152
Jabba-1.2.1a_1.7.10
journeymap-1.7.10-5.1.0-unlimited
Mantle-1.7.10-0.3.2b
MineFactoryReloaded-[1.7.10]2.8.0-104
Morpheus-1.7.10-1.6.10
neiaddons-1.12.14.40-mc1.7.10
NEIIntegration-MC1.7.10-1.1.1
NotEnoughItems-1.7.10-1.0.5.118-universal
NotEnoughKeys-1.7.10-3.0.0b43-universal
ObsidiPlates-1.7.10-universal-3.0.0.18
OpenBlocks-1.7.10-1.5
OpenComputers-MC1.7.10-1.5.22.43-universal
OpenModsLib-1.7.10-0.9
pressure-1.2.4.124-mc1.7.10
ProgressiveAutomation-1.7.10-1.6.27
QmunityLib-1.7.10-0.1.114-universal
Railcraft_1.7.10-9.6.1.0
RedstoneArsenal-[1.7.10]1.1.1-89
ResourceLoader-1.2
SimplyJetpacks-MC1.7.10-1.5.2
SolarFlux-1.7.10-0.8b
StorageDrawers-1.7.10-1.6.2
supercraftingframe-1.7.10.3
tardismod-1.7.10-0.994-124-DS
TConstruct-1.7.10-1.8.8
Thaumcraft-1.7.10-4.2.3.5
thaumcraftneiplugin-1.7.10-1.7a
ThaumicExploration-1.7.10-1.1-53
ThaumicTinkerer-2.5-1.7.10-164
ThermalDynamics-[1.7.10]1.1.0-161
ThermalExpansion-[1.7.10]4.0.3B1-218
ThermalFoundation-[1.7.10]1.2.0-102
TMechworks-1.7.10-0.2.15.106
Torcherino-1.7.10-2.2s
TorchTools-1.7.10-1.2.0.27
Translocator-1.7.10-1.1.2.15-universal
TravellersGear-1.7.10-1.16.6
Waila-1.5.10_1.7.10
WailaHarvestability-mc1.7.10-1.1.5
WitchingGadgets-1.7.10-1.1.8
WR-CBE-1.7.10-1.4.1.9-universal
works like a charm!(and when i say that i mean 15fps(i've gotten use to it))

[config.zip](https://github.com/CovertJaguar/Railcraft/files/172871/config.zip)
don't have cauldron
forge-10.13.4.1448
 this should be enough information

**Comment by Jamie787** [comment]
a video of it in action
[https://www.youtube.com/watch?v=Nv-FEwUKURk](url)

**Comment by Forecaster** [comment]
Does this happen if you remove everything except forge and railcraft?

**Comment by enki1337** [comment]
I think I've figured this one out, as I've been dealing with it for some time in FTB Vanilla+. It seems to be an interaction with TorchTools mod. TT tries to place the adjacent block in your hotbar instead of using the Crowbar's right-click ability properly. I'm not sure if this is a configuration problem, a TorchTools problem or a Railcraft problem.

The workaround is pretty easy. Just make sure there is an empty inventory slot to the right of the crowbar.

**Comment by CovertJaguar** [comment]
Yeah, that's probably not Railcraft.

**Comment by enki1337** [comment]
That was my guess as well, but figured I'd leave a comment anyways in case someone else had the same problem and wanders across this. TT hasn't been updated in over a year, so even if it's something they could fix, I doubt there's much point in reporting it to them. Work around is pretty trivial anyways once you understand the problem. Cheers and thanks for the awesome mod!
