### ISSUE TITLE
Adv. Item Loader won't fill Cargo Cart

### ISSUE THREAD

**Issue by ShaneCourtrille** [CovertJaguar/Railcraft#790]
My Adv. Item Loader works fine if I push a Chest Cart onto the locking track in front of it.  If I do the same thing with a Cargo Cart the cart won't get filled even though the cart filter matches the item in the loader buffer.

Thoughts?

**Comment by CovertJaguar** [comment]
Possibly related to c20f5e76fe700d9ced601834e422ac11f2afeefd
