### ISSUE TITLE
Suggestion - Cart/Locomotive/Loader template

### ISSUE THREAD

**Issue by Landrash** [CovertJaguar/Railcraft#791]
The one thing I feel Railcraft is missing at the moment is a easy way to duplicate settings from loaders and/or add carts that's already in use without picking them up.

Loader template
 - Book, paper or tool that's right clicked on the thing you want to template(cart, locomotive).
 - Could optionally be clicked on a already setup loader to duplicate it's settings.
 - When encoded it can be clicked or placed in the loader to encode the setting that are being set.
 - Cheap to craft and most likely one time use. Once encoded it stays encoded.
 
Information to copy
 -Same information as when cart/locomotive is placed inside loader.

**Comment by CovertJaguar** [comment]
Would be a fairly simple addition.

**Comment by Vexatos** [comment]
> Loaders keep their setting when picked up with crowbar.

I don't think loaders should be picked up with a crowbar. I think a recent change made sure that can't be done.

For locomotives, make sure the template doesn't copy over a destination if the ticket owner isn't you.

**Comment by Landrash** [comment]
@Vexatos Edited to correspond to that change.

On second thought maybe the routing table book could be extended to do this?
Use the magnifying glas with a book routing table book in inventory to write down corresponding information about a cart/locomotive and use the book in a loader in the same way as a switch or detector?

**Comment by CovertJaguar** [comment]
@Landrash overly complicated?

**Comment by Landrash** [comment]
@CovertJaguar My second suggestion most likely is.

**Comment by Forecaster** [comment]
I am working on this, but I have some questions:

It being single-use, is there a point to that?
The way I see it is that this is a convenience tool, and having it be single-use doesn't serve a whole lot of purpose.
I'm currently thinking making the recipe a magnifying-glass and a piece of paper, and having the icon reflect this.

Also currently the tool copies all the filters in the block. So both the cart filter and the item/fluid filter.
Should it also copy the button states? It currently does not, but that is part of how the filtering works, so it might be desirable to include that.

Currently if the tool is used to copy an item filter, then pasted on a fluid loader/unloader it will only paste the cart filter. Should it do nothing in this case?

**Comment by CovertJaguar** [comment]
I say "no" to single use.

Forecaster, a hint on implementation: TileEntity.writeToNBT()
