### ISSUE TITLE
Add info of which blocks are controllers and receivers to tooltips

### ISSUE THREAD

**Issue by Forecaster** [CovertJaguar/Railcraft#792]
As an example, the block signal could say:

> Block Signal
> 1x Controller

The dual head distant signal would say:

> 2x Receiver

And the dual head block signal:

> Block Signal
> 1x Controller
> 1x Receiver

**Comment by CovertJaguar** [comment]
Closed by cfde38fe00431ec37209048b3443138bd12ea183
