### ISSUE TITLE
Suggestion: Item loader modification

### ISSUE THREAD

**Issue by bosto2** [CovertJaguar/Railcraft#794]
The ability to extract from item loaders
it would allow more control over loading systems.

**Comment by CovertJaguar** [comment]
Going to need a more detailed use case than that.

**Comment by bosto2** [comment]
It would be useful for any rail system that has multiple loaders, is backlogging or simply wants more control over the amount of items its sending
e.g. [The current system i am working on](http://prntscr.com/akb8th)
The system above is meant to keep a massive controlled backlog of items ,but there is no space for comparators and i cant measure the amount of items backlogging in the loaders
There is no real reason i can think of why extraction should be prohibited and i see plenty of uses for it.

**Comment by CovertJaguar** [comment]
Use chests? Loaders will pull from adjacent inventories.

**Comment by bosto2** [comment]
I was not aware of this
Thanks

**Comment by iceman11a** [comment]
Or use a AE2 Network,
