### ISSUE TITLE
Mekanism mod compat (minecart stuff for mekanism´s Gasses)

### ISSUE THREAD

**Issue by mariodk** [CovertJaguar/Railcraft#800]
well
mekanism is starting to become abit mainstream tech mod
so was thinking for a Minecart / loader & unloader for Mekanism´s Gasses 
thats all
just discovered i needed it for my railway system
and im pretty sure other ppls do too 
right now i just use block breaker to break/placer for gas tanks and put them in chest cart
but im sure it will be more Server/FPS friendly to have a offcial Gas minecart

**Comment by Landrash** [comment]
@mariodk As a in between you could just use a rotary condensator to convert the gas into a fluid that can be transported in in a railcraft cart.

**Comment by mariodk** [comment]
ohh i forgot about that but still would be nice to have gas support so you dont waste power on 2x of rotary condensators

**Comment by CovertJaguar** [comment]
Sounds like an existing solution is available. I don't see any reason to add yet another build dependency to Railcraft.
