### ISSUE TITLE
Force Track can be purchased in a Railcraft Villager Shop

### ISSUE THREAD

**Issue by MyNameIsKodos** [CovertJaguar/Railcraft#806]
I can successfully purchase the Force Track, as well as placing it. The first track that's placed will stay, but when I place a second one adjacent to the first, it causes a block update which forces both tracks to disappear.

**Comment by Landrash** [comment]
My guess would be the function adding the trades for tracks is in `Railcraft/src/main/java/mods/railcraft/common/worldgen/VillagerTradeHandler.java` and that it's adding all the tracks available.  Maybe low hanging fruit for anyone who feels like they want to contribute.

```
for (EnumTrack track : EnumTrack.VALUES) {
            if (track.isEnabled())
                addTrade(recipeList, rand, 0.1F, new Offer(track.getItem(), track.recipeOutput - 2, track.recipeOutput + 2), new Offer(Items.emerald, 2, 3));
        }
```

**Comment by liach** [comment]
Add something like `#isCraftable` to limit the presense of the track in the creative menu and trade and other survival usages?

**Comment by CovertJaguar** [comment]
I have to rewrite this code for 1.8 anyway.

**Comment by CovertJaguar** [comment]
This should no longer be an issue.
