### ISSUE TITLE
Add passive anchor cart

### ISSUE THREAD

**Issue by liach** [CovertJaguar/Railcraft#807]

**Comment by Landrash** [comment]
I'm a bit confused of how this one would work?

>Passive Anchor - From railcraft wiki
>Similar to Personal Anchor it does not force load chunks, but keeps them loaded once they have been visited.

Would you want it to function as a normal anchor cart if it has been loaded by a player or only let it continue loading a chunk that it's in with the player? Only keeping chunks loaded if they already been loaded doesn't really work with a moving anchor does it?

**Comment by liach** [comment]
Just add it like personal anchor cart. Whatsoever.

**Comment by liach** [comment]
@CovertJaguar Passive anchor is the only anchor without a cart. Why?

**Comment by CovertJaguar** [comment]
Because I didn't see the use case.

**Comment by liach** [comment]
Is personal anchor cart passive?

**Comment by CovertJaguar** [comment]
The issue here is that the World Anchor Cart is technically a Passive Anchor already.
