### ISSUE TITLE
Tracks next to switch tracks unable to make corners

### ISSUE THREAD

**Issue by knoeki** [CovertJaguar/Railcraft#808]
As seen in this screenshot:

![2016-04-24_15 40 20](https://cloud.githubusercontent.com/assets/12951121/14768013/7208557c-0a35-11e6-969e-b7a6ddf00c39.png)

Works fine with normal tracks:

![2016-04-24_15 48 05](https://cloud.githubusercontent.com/assets/12951121/14768015/7e1d065a-0a35-11e6-8341-7d81e5cbcf48.png)

**Comment by LizzyTrickster** [comment]
Did you try breaking and re-placing the track going to the detector?

**Comment by CovertJaguar** [comment]
This is both known and expected because of how the switches work. Placing tracks side-by-side like that is not recommended for various reasons. This is only one of them.
