### ISSUE TITLE
Other mod ores spawn in abyssal stone veins, most notably Mek, AE2 and TiCo.

### ISSUE THREAD

**Issue by MineWitherMC** [CovertJaguar/Railcraft#809]
http://imgur.com/a/o9sk3
The ores: aluminum/tin/copper and oreberry from TCo, certus quartz (AE2) and osmium (Mek).

**Comment by CovertJaguar** [comment]
As far as I can tell, this is on the other mods to call Block.isReplaceableOreGen(x,y,z, Blocks.stone) before generating Ore. I don't think there is much I can do about this.
