### ISSUE TITLE
[Suggestion] Bi-Directional Locomotive

### ISSUE THREAD

**Issue by LizzyTrickster** [CovertJaguar/Railcraft#810]
Originally suggested this in the RC Dev channel then @Forecaster suggested to raise a ticket so here's that ticket :)

The idea for the locomotive is that it can go in either direction but only at a max speed of 2 (compared to a normal locomotive's 4-forward and 1-back). It'd be useful for builds/setups where you have a locomotive on each end and want it to come back out of a station the same way that it went in (for instance, at terminal stations).

for working out if it was going forward or back, perhaps have some way of designating a loco as "A" and the other as "B" (also perhaps any more locomotives linked get unlinked automatically or something?) and then having a small indicator above the directional arrows to indicate which 'direction' this loco is. 

Not entirely sure how feasable this would be what with locomotives randomly changing directions.

**Comment by CovertJaguar** [comment]
I could probably just add more reverse gears for the electric locomotive, since orientation based safety issues isn't something that Electric or Diesel locomotives suffer from like Steam Locomotives do.

**Comment by Forecaster** [comment]
That would require changing the locomotive track as well then

**Comment by LizzyTrickster** [comment]
Perhaps have a standard (current form of the loco track) and an advanced one?

The advanced one would behave similarly to the standard one but would allow for differentiating which direction its for perhaps? Maybe visualized by the "A" side having some pixels respresenting it? (will do a concept art thingy in a bit

**Comment by CovertJaguar** [comment]
I'd prefer not to add an additional track, but I'm open to suggestions on how to improve the existing one. Completely changing the design is ok if it makes for a better track.

**Comment by Forecaster** [comment]
Just allowing the full range to be used for both forward or reverse speeds should suffice I'd think. Just need to use a different pattern of colour to indicate direction.

**Comment by CyanideCarrot** [comment]
This is a good idea, but there are workarounds from other mods. I have created a system where once the train reaches the station, an autonomous activator from Thermal Expansion filled with crowbars turns the train around. Maybe adding a similar block would do the trick for modpacks without Thermal Expansion?

**Comment by KnightMiner** [comment]
I feel like the train magically flipping would just break immersion. It may work as a temporary solution, but a two directional train sounds like it would be better in the long run

**Comment by CovertJaguar** [comment]
I need to check and make sure I didn't miss anything (GUI maybe?), but the Electric Loco should be able to range from -3 to 4 in terms of speed settings now and the track supports it.
