### ISSUE TITLE
Recipes that use glass do not accept oredict glass entires

### ISSUE THREAD

**Issue by skyboy** [CovertJaguar/Railcraft#812]
We have `blockGlassColorless` for unstained glass blocks and `blockGlass` for any glass block, as well as the various individual colors. Entries mirrored for panes in the same format: `paneGlass`

**Comment by Vexatos** [comment]
Which recipes are you talking about, specifically? I should have moved over most recipes to use appropriate OreDict entries.

**Comment by skyboy** [comment]
At a glance it appears to be "all of them." Give me a moment to make a list and I will edit.

**Comment by Vexatos** [comment]
[The magnifying glass does use oredict entries, for instance](https://github.com/CovertJaguar/Railcraft/pull/567/files#diff-cb9f776b032242bce9d6ec55960f4a0eR57).

**Comment by skyboy** [comment]
Then it would appear few mods actually use the colorless oredict. That's irritating.

So a few recipes would continue to not accept incorrectly categorized other mod items, but things such as engines, the fluid (un)loaders, and the surveyor should not require colorless glass; where the gauges and strengthened glass are more debatable.

**Comment by Vexatos** [comment]
I think colorless glass should be used anywhere a clear pane is necessary for visuals. And that's usually the case.

**Comment by CovertJaguar** [comment]
So is this invalid?

**Comment by Vexatos** [comment]
I am pretty sure I replaced every instance of `Blocks.glass` and `Blocks.glass_pane` in that commit.
