### ISSUE TITLE
Signal lights are extremely dark

### ISSUE THREAD

**Issue by LizzyTrickster** [CovertJaguar/Railcraft#814]
The aspect lights on both the Signal blocks and the various boxes is very dark but if they are named and you are looking at the signal/box, it will show it at full brightness (see example screenshots below).
![2016-05-02_14 40 34](https://cloud.githubusercontent.com/assets/3775521/14955839/8c4148dc-1074-11e6-8e65-d5bdbf906c13.png)
![2016-05-02_14 40 35](https://cloud.githubusercontent.com/assets/3775521/14955838/8c412d7a-1074-11e6-8d8e-0bd615b20a91.png)
Mod list: http://pb.i0i0.me/p/4t6fyAyC

**Comment by CovertJaguar** [comment]
Known

**Comment by liach** [comment]
Might that be caused by commits in https://github.com/CovertJaguar/Railcraft/commits?author=Vexatos on March 7?

**Comment by CovertJaguar** [comment]
Actually I think it was @sfPlayer1's commits on the same topic, it's probably just a missing opengl state variable. I'll look at it for 10.1.0 when I fix the signals.

**Comment by Player3324** [comment]
Yes, GL lighting may still be on or the 2nd texture unit which applies MC's sun+block light is still active.

**Comment by liach** [comment]
c77b6cee2b72f72d9780c7ca91ee4b448c767552
