### ISSUE TITLE
[Request] Getting the Charge Level via Redstone Comparators

### ISSUE THREAD

**Issue by kremsy** [CovertJaguar/Railcraft#815]
It would be amazing for some automatization to be able to get the charge level of electric tracks with putting an redstone comparator next to it.

**Comment by CovertJaguar** [comment]
I plan to rewrite the charge code at some point, this may no longer be valid at that point.

**Comment by CovertJaguar** [comment]
Feeders and the planned Batteries will have Comparator support.
