### ISSUE TITLE
Idea for Loaders & Unloaders

### ISSUE THREAD

**Issue by Speiger** [CovertJaguar/Railcraft#816]
Loaders & Unloaders can see between Minecart Types in the filters.
But with a big Cargo Trains you can have only so much of these filters. And the amount of Minecarts are very limited.
Since you added the feature that Locomotive show their names in the world when they got special Names in item form,
why dont we put that a step further.
You can set the Minecart type in the filter, but why not make a Type + CustomName?
Or is that already a feature?
That you can say that this Minecart type (chest cart for example) with the Name "Coal Cart" will be only unloaded from or loaded to.

(Just had that in mind.)

**Comment by Landrash** [comment]
You can already use named carts in filters.
