### ISSUE TITLE
An option in config to disable enchantments

### ISSUE THREAD

**Issue by VincentVan91** [CovertJaguar/Railcraft#819]
I get railcraft enchantments like most of the time when i enchant books

**Comment by liach** [comment]
It'd be better to add a config to adjust the weight of the enchantments.

**Comment by CovertJaguar** [comment]
There are weights?

**Comment by hea3ven** [comment]
Lol, it's the second parameter of the Enchantment constructor. In 1.9 it's an enum
 * 10 -> common
 * 5 -> uncommon
 * 2 -> rare
 * 1 -> very rare
