### ISSUE TITLE
[RC 9.12.1.0] RF Unloader not emitting redstone flux

### ISSUE THREAD

**Issue by pricindalas** [CovertJaguar/Railcraft#821]
Hello,
It says RF Unloader only emits redstone flux but it is not emitting any RF neither with redstone signal on or off. It unloads RF from the cart but I can't extract any RF from Unloader. I tried EnderIO conduits (with and without extraction options) and Builcraft pipes (tried with autarchic pulsars on too).

- FML 7.10.99.99
- Forge 10.13.4.1558

Other mods I use:

- CodeChichenCore
- NEI 1.0.5.120
- BuildCraft 7.1.16
- Forestry 3.6.12.3
- EnderIO 1.7.10-2.2.8.381

**Comment by CovertJaguar** [comment]
I seem to have made a fatal flaw in my assumptions about how RF works.

**Comment by CovertJaguar** [comment]
Fixed by 319296753e0de6a9c28dc869f71db67296455203
