### ISSUE TITLE
hidden tile entities

### ISSUE THREAD

**Issue by lunchboxxx19** [CovertJaguar/Railcraft#822]
i loaded my world in mcedit and found hundreds of the textureless blocks everywhere and when i analyzed them it said they were hidden tile entities from railcraft. is this supposed to happen? and if so why?

this picture is a screenshot of what mcedit has to say after i analyze the block

http://i.imgur.com/wDEEbUV.png

and this is a picture of the spread from this block. i have cleaned the area up a bit for a build

http://i.imgur.com/snU3zQo.png

**Comment by williewillus** [comment]
in short: yes

**Comment by lunchboxxx19** [comment]
in long? like seriously why is this happening?

**Comment by CovertJaguar** [comment]
Its fake air, for logic purposes for the player tracking mode of the Trackman's Goggles.

You can make a good argument that it's a lousy implementation of a niche feature and you wouldn't be wrong. However, It's not really that harmful these days and has done wonders for the fake air compatability movement.

The blocks themselves expire after 20 minutes real time.

**Comment by lunchboxxx19** [comment]
ah ok, so it couldnt be the cause of my lag spikes then?

**Comment by CovertJaguar** [comment]
I wouldn't say they were lag free (one of the points one could make against them).

**Comment by lunchboxxx19** [comment]
ok then, thanks for the info. ill close this issue now
