### ISSUE TITLE
Locomotives jump while turning when first placed

### ISSUE THREAD

**Issue by Forecaster** [CovertJaguar/Railcraft#825]
When a new locomotive is placed and let run at speed 4 in a small loop the model "jumps" up while it is turning. This stops happening once the world is reloaded.

It seems to happen from 9.10 through 9.12.2

Here's a gif of it happening: http://imgur.com/mtpKqTJ

It consistently happens for me, but I have no idea if it's reproducible for anyone else.

**Comment by LizzyTrickster** [comment]
It's just excited to get going!

**Comment by CovertJaguar** [comment]
Meh, this is Minecraft being stupid again. Something about improper syncing of some variable or something in the base entity code.

**Comment by Forecaster** [comment]
Ah, I've never seen it before

**Comment by CovertJaguar** [comment]
I've seen it while messing with the tunnel bore.

**Comment by CovertJaguar** [comment]
This seems to be fixed in 1.10.
