### ISSUE TITLE
Minecraft 1.8.9 or 1.9.x?

### ISSUE THREAD

**Issue by rcistano** [CovertJaguar/Railcraft#826]
Are there any plans for Railcraft 1.8.9?

**Comment by LizzyTrickster** [comment]
Yes, look at the branch for it

**Comment by rcistano** [comment]
Thanks, I'll be on the look out for the 1.8.9 version. I dont expect it to come out any time soon, when it does it will be welcomed in my pack.

**Comment by CovertJaguar** [comment]
There is some debate at the moment about whether to drop 1.8 and go straight to 1.9. There are various pressures for doing this: several other major mods are skipping 1.8, Forge 1.9 brings Java 8 warning screens, 1.9 changes some rendering stuff,  etc....

**Comment by liach** [comment]
IMO you should make an official release for major version 10 for 1.9, but a pre-release for 1.8.9.

**Comment by CovertJaguar** [comment]
That doesn't make much sense, as there an additional effort cost in supporting 1.8.9 at all. If I was going to release anything, I might as well do a full release.

**Comment by octarine-noise** [comment]
I think you should go straight to 1.9 - especially if your modding time is at a premium.

Remember, it's not just the time cost of doing a port. If you release for 1.8.9, you'll have two different versions to maintain too - at least for a while. It's not 2x the time, but still...

**Comment by rcistano** [comment]
Right now I see more Mods coming from 1.7.10 to 1.8.9. They have not done much from 1.7.10 to 1.9

**Comment by Forecaster** [comment]
Railcraft going to 1.9 might encourage more mods to do that as well though.

**Comment by rcistano** [comment]
Yes, but for those that have started designing their modpack towards 1.8.9 wouldn't be able to have this mod included.

**Comment by CovertJaguar** [comment]
Forestry is also skipping 1.8.9.

**Comment by liach** [comment]
1.9. It seems that 1.9.4 mappings had been published, and you need to hurry.

**Comment by CovertJaguar** [comment]
@liach in the future, assume that if I don't specify the last number of the version string that I'm referring to the entire collection of releases that fall under the first two numbers. -.-

**Comment by liach** [comment]
Actually I mean if you focus on 1.8.9 too much, then you'd not have enough time working on 1.9 and its series releases.

**Comment by LuxusDarkangel** [comment]
You should skip 1.8.9, at this point is already an outdated version, no point on putting the effort in a port to 1.8.9 and right after that start moving to 1.9.

**Comment by erindalc** [comment]
If this is still an active discussion, the only major mods still on 1.8.9 are Thaumcraft 5 and Immersive Engineering iirc. A direct 1.9.4 port would be better.

**Comment by williewillus** [comment]
it's already on 1.9

**Comment by CovertJaguar** [comment]
1.8 is officially off the table. Closing.
