### ISSUE TITLE
Train Locking Track does not turn OFF

### ISSUE THREAD

**Issue by JasonMcRay** [CovertJaguar/Railcraft#828]
In RC 9.12.2.0 (dont know if the issue is present in previous versions too) Locking Track for trains is bugged to the state its useless for Locomotives.

It doesn't turn off after receiving redstone signal with the locomotive passing by.

I guess recreation steps will be nice in here:
1) Put down Locking track
2) Set it to any of the Train modes (for example Train Lockdown Mode)
3) Put lever next to the track
4) Flip the lever on and off.
4a) The Track will correctly turn ON, and then OFF

but...

5) Now if you will let Locomotive pass on that track
6) Flip the lever to let the Locomotive go
7) ???
8) You no longer can turn the track off. Even if you remove the lever, it will still act like its receiving redstone signal.

Classic holding mode (or any other non-locomotive affecting modes) work fine.

**Comment by Forecaster** [comment]
Reproduced in dev-environment

**Comment by CovertJaguar** [comment]
It does not respond instantly to redstone signals, it stays on as long as it would continue to boost the Train.

**Comment by CovertJaguar** [comment]
Tested, seems to be working as intended. Waits 10 seconds before turning off, resets immediately if a different train comes past. I see no issue here.

**Comment by Forecaster** [comment]
Ah, I guess I didn't have a big enough loop for it : P

**Comment by JasonMcRay** [comment]
Oh. I had no idea that it waits couple of seconds to turn off... Thanks for information and sorry about the misreport

**Comment by knopfm** [comment]
Why does it take so long to turn off the redstone?
In another modpack it works without the long waiting time.
