### ISSUE TITLE
Lead Plated shows up the wrong name and is not ordicted

### ISSUE THREAD

**Issue by Dream-Master** [CovertJaguar/Railcraft#831]
Lead Plateds shows up the wrong name and are not oredicted.

Mincraft 1.7.10 and Railcraft 9.12.2.0

![image](https://cloud.githubusercontent.com/assets/2970688/15455148/e5cd5850-204b-11e6-94b2-7b315c4a3d88.png)

**Comment by CovertJaguar** [comment]
None of the plates are OreDicted.

**Comment by Dream-Master** [comment]
Maybe Greg did it. So have to look into gt code.

**Comment by liach** [comment]
By the way why don't you oredict them?

**Comment by CovertJaguar** [comment]
Because everyone has different recipes for plates. 

And it's an intermediate item designed to help reduce the chance of recipe collision with other mods. Adding it to the Ore Dictionary defeats that purpose and I might as well just use ingots and not even have plates.
