### ISSUE TITLE
[RFC] Splitting Railcraft modules into independently installable mod

### ISSUE THREAD

**Issue by lokkenmor** [CovertJaguar/Railcraft#838]
I wanted to know if there would be any support for the idea of splitting the Railcraft modules into separately installable mods, linked together using the Forge dependency system (I'm assuming that the dep. system is fit-for-purpose, I haven't looked too deeply into the idea yet).

I'm willing to have a go at doing the work myself (I've already forked the repo and had a look at the code), I just wanted know whether this would be accepted as a merge back or not.

**Comment by CovertJaguar** [comment]
Nope, sorry. At one point in time in the past I had to manage several files at once and it was a pain. I have no desire to make my release cycle any more painful than it already is. Its not a very popular change among users either historically.

Railcraft already has an integrated internal module system where you can via config disable any portion of the mod you may dislike.

**Comment by lokkenmor** [comment]
Ack, very well
