### ISSUE TITLE
Crash with Tile Entity

### ISSUE THREAD

**Issue by Eufranio** [CovertJaguar/Railcraft#840]
I got a crash randomly when i started my server, with this:

java.lang.NoClassDefFoundError: Could not initialize class mods.railcraft.common.blocks.machine.alpha.TileBlastFurnace

Full crash-report: http://pastebin.com/R5xbU80F

**Comment by CovertJaguar** [comment]
Class loader errors are not something I can easily debug. You'll probably need to start removing stuff until it starts working.

These kinds of crashes are usually caused because something else broke during Forge initialization.

**Comment by Eufranio** [comment]
Could you then auto-remove these blocks? Forge "Remove Erroring Entities" didn't work with this, and the server is crashing a lot of times. Something to remove it automatically?

**Comment by CovertJaguar** [comment]
I have no way to detect when the classloader fails to load a class, nor any reasonable way to respond when it happens. You will need to first identify what mod is causing the classloader to fail (it's probably not Railcraft).

**Comment by Eufranio** [comment]
Okay :/

**Comment by AEnterprise** [comment]
from the log it looks like you are running thermos, that's a pretty good candidate for being the cause
