### ISSUE TITLE
Increase Turbine Steam Usage/Output to match Boiler Output

### ISSUE THREAD

**Issue by CovertJaguar** [CovertJaguar/Railcraft#841]
The Steam Turbine currently uses 320 mB of Steam per tick.

A 36LP Boiler outputs 360 mB per tick.

A 18HP Boiler outputs 360 mB per tick.

A 36HP Boiler outputs 720 mB per tick (360 x 2).

It would make sense for the Steam Turbine to use 360 mB of Steam per tick in order to match the boiler outputs.

This would result in about a 1.125x increase of usage and output. Going from 200 EU/t to 225 EU/t.

Comments.

**Comment by Forecaster** [comment]
Sounds Reasonable. I can't think of a reason to not do this.
